In [1]:
import numpy as np
import pandas as pd
import polars as pl
import seaborn as sns

import matplotlib.pyplot as plt
from sklearn.tree import plot_tree
from sklearn.model_selection import train_test_split
from sksurv.ensemble import RandomSurvivalForest
from sksurv.linear_model import CoxPHSurvivalAnalysis
from sksurv.metrics import concordance_index_censored , concordance_index_ipcw
from sklearn.impute import SimpleImputer
from sksurv.util import Surv

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.ensemble import RandomForestRegressor

In [2]:
# Molecular Data
mol_df = pl.read_csv("../data/raw/X_train/molecular_train.csv")
mol_eval = pl.read_csv("../data/raw/X_test/molecular_test.csv" , ignore_errors=True)

cl_df = pl.read_csv("../data/raw/X_train/clinical_train.csv")

y_train = pl.read_csv("../data/raw/target_train.csv")

In [11]:
mol_df["REF"].value_counts().sort(by=pl.col("REF").str.len_chars() , descending=True)

shape: (407, 2)
┌─────────────────────────────────┬───────┐
│ REF                             ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ null                            ┆ 114   │
│ ACAGGTGAGGCACCTGAGATTAGAGCAGGA… ┆ 1     │
│ TCCGTAGCCACCGCCCCCGTACCTGCGGGG… ┆ 1     │
│ CAGCGGCAACGCCTCGCTCATCTTGCCTGG… ┆ 2     │
│ AGCAGAGGCTTAAGGAGGAGGAAGAAGACA… ┆ 11    │
│ …                               ┆ …     │
│ AT                              ┆ 48    │
│ A                               ┆ 1234  │
│ G                               ┆ 2965  │
│ C                               ┆ 3199  │
│ T                               ┆ 1771  │
└─────────────────────────────────┴───────┘

In [195]:
mol_df.filter(pl.col("PROTEIN_CHANGE").is_null())

# p.?

shape: (12, 11)
┌─────────┬─────┬────────────┬────────────┬───┬────────────────┬───────────────────┬───────┬───────┐
│ ID      ┆ CHR ┆ START      ┆ END        ┆ … ┆ PROTEIN_CHANGE ┆ EFFECT            ┆ VAF   ┆ DEPTH │
│ ---     ┆ --- ┆ ---        ┆ ---        ┆   ┆ ---            ┆ ---               ┆ ---   ┆ ---   │
│ str     ┆ str ┆ f64        ┆ f64        ┆   ┆ str            ┆ str               ┆ f64   ┆ f64   │
╞═════════╪═════╪════════════╪════════════╪═══╪════════════════╪═══════════════════╪═══════╪═══════╡
│ P100378 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ null           ┆ 2KB_upstream_vari ┆ 0.513 ┆ 46.0  │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
│ P102718 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ null           ┆ 2KB_upstream_vari ┆ 0.267 ┆ 54.0  │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
│ P105914 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ null           ┆ 2KB_upstream_vari ┆ 0.232 ┆ 59.0  │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
│ P120956 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ null           ┆ 2KB_upstream_vari ┆ 0.202 ┆ 92.0  │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
│ P120967 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ null           ┆ 2KB_upstream_vari ┆ 0.052 ┆ 112.0 │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
│ …       ┆ …   ┆ …          ┆ …          ┆ … ┆ …              ┆ …                 ┆ …     ┆ …     │
│ P121131 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ null           ┆ 2KB_upstream_vari ┆ 0.316 ┆ 118.0 │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
│ P131530 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ null           ┆ 2KB_upstream_vari ┆ 0.115 ┆ 229.0 │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
│ P131838 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ null           ┆ 2KB_upstream_vari ┆ 0.151 ┆ 224.0 │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
│ P100357 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ null           ┆ 2KB_upstream_vari ┆ 0.519 ┆ 82.0  │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
│ P117175 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ null           ┆ 2KB_upstream_vari ┆ 0.569 ┆ 28.0  │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
└─────────┴─────┴────────────┴────────────┴───┴────────────────┴───────────────────┴───────┴───────┘

In [197]:


mol_df = mol_df.with_columns(
    pl.when(pl.col("PROTEIN_CHANGE").is_null())
    .then(pl.lit("p.?"))
    .otherwise(pl.col("PROTEIN_CHANGE"))
    .alias("PROTEIN_CHANGE")
)

In [201]:
mol_df.filter(pl.col("PROTEIN_CHANGE") == "p.?" , pl.col("GENE") == "TERT")

shape: (12, 11)
┌─────────┬─────┬────────────┬────────────┬───┬────────────────┬───────────────────┬───────┬───────┐
│ ID      ┆ CHR ┆ START      ┆ END        ┆ … ┆ PROTEIN_CHANGE ┆ EFFECT            ┆ VAF   ┆ DEPTH │
│ ---     ┆ --- ┆ ---        ┆ ---        ┆   ┆ ---            ┆ ---               ┆ ---   ┆ ---   │
│ str     ┆ str ┆ f64        ┆ f64        ┆   ┆ str            ┆ str               ┆ f64   ┆ f64   │
╞═════════╪═════╪════════════╪════════════╪═══╪════════════════╪═══════════════════╪═══════╪═══════╡
│ P100378 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ p.?            ┆ 2KB_upstream_vari ┆ 0.513 ┆ 46.0  │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
│ P102718 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ p.?            ┆ 2KB_upstream_vari ┆ 0.267 ┆ 54.0  │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
│ P105914 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ p.?            ┆ 2KB_upstream_vari ┆ 0.232 ┆ 59.0  │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
│ P120956 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ p.?            ┆ 2KB_upstream_vari ┆ 0.202 ┆ 92.0  │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
│ P120967 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ p.?            ┆ 2KB_upstream_vari ┆ 0.052 ┆ 112.0 │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
│ …       ┆ …   ┆ …          ┆ …          ┆ … ┆ …              ┆ …                 ┆ …     ┆ …     │
│ P121131 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ p.?            ┆ 2KB_upstream_vari ┆ 0.316 ┆ 118.0 │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
│ P131530 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ p.?            ┆ 2KB_upstream_vari ┆ 0.115 ┆ 229.0 │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
│ P131838 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ p.?            ┆ 2KB_upstream_vari ┆ 0.151 ┆ 224.0 │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
│ P100357 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ p.?            ┆ 2KB_upstream_vari ┆ 0.519 ┆ 82.0  │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
│ P117175 ┆ 5   ┆ 1.295228e6 ┆ 1.295228e6 ┆ … ┆ p.?            ┆ 2KB_upstream_vari ┆ 0.569 ┆ 28.0  │
│         ┆     ┆            ┆            ┆   ┆                ┆ ant               ┆       ┆       │
└─────────┴─────┴────────────┴────────────┴───┴────────────────┴───────────────────┴───────┴───────┘

In [90]:
mol_df.filter(pl.col("REF").str.len_chars() > 1 , pl.col("ALT").str.len_chars() > 1) 

# is_complex_nucleotide


def is_complex_nucleotide(ref , alt):
    if(isinstance(ref,str) and isinstance(alt,str)):
        return int(len(ref) > 1 and len(alt) > 1)


mol_df = mol_df.with_columns(
    pl.struct(["REF","ALT"]).map_elements(lambda row : is_complex_nucleotide(row["REF"] , row["ALT"])
                                          , return_dtype=pl.Int16 ).alias("is_complex_nucleotide")
)

In [91]:
mol_df = mol_df.with_columns(
    pl.col("REF").str.len_chars().alias("REF_length")
)

In [92]:
mol_df = mol_df.with_columns(
    pl.col("ALT").str.len_chars().alias("ALT_length")
)

In [93]:
mol_df.sort(pl.col("REF_length") , descending=True , nulls_last=True)

shape: (10_935, 14)
┌─────────┬──────┬─────────────┬─────────────┬───┬────────┬──────────────┬────────────┬────────────┐
│ ID      ┆ CHR  ┆ START       ┆ END         ┆ … ┆ DEPTH  ┆ is_complex_n ┆ REF_length ┆ ALT_length │
│ ---     ┆ ---  ┆ ---         ┆ ---         ┆   ┆ ---    ┆ ucleotide    ┆ ---        ┆ ---        │
│ str     ┆ str  ┆ f64         ┆ f64         ┆   ┆ f64    ┆ ---          ┆ u32        ┆ u32        │
│         ┆      ┆             ┆             ┆   ┆        ┆ i16          ┆            ┆            │
╞═════════╪══════╪═════════════╪═════════════╪═══╪════════╪══════════════╪════════════╪════════════╡
│ P117988 ┆ 2    ┆ 2.5966666e7 ┆ 2.5967241e7 ┆ … ┆ 1259.0 ┆ 0            ┆ 576        ┆ 1          │
│ P118264 ┆ 17   ┆ 7.4732895e7 ┆ 7.4732964e7 ┆ … ┆ 1422.0 ┆ 0            ┆ 70         ┆ 1          │
│ P102939 ┆ 21   ┆ 3.6259317e7 ┆ 3.6259372e7 ┆ … ┆ 1536.0 ┆ 0            ┆ 56         ┆ 1          │
│ P105849 ┆ 21   ┆ 3.6259317e7 ┆ 3.6259372e7 ┆ … ┆ 1147.0 ┆ 0            ┆ 56         ┆ 1          │
│ P102638 ┆ 19   ┆ 1.3054564e7 ┆ 1.3054616e7 ┆ … ┆ 1720.0 ┆ 0            ┆ 53         ┆ 1          │
│ …       ┆ …    ┆ …           ┆ …           ┆ … ┆ …      ┆ …            ┆ …          ┆ …          │
│ P131472 ┆ null ┆ null        ┆ null        ┆ … ┆ null   ┆ null         ┆ null       ┆ null       │
│ P131505 ┆ null ┆ null        ┆ null        ┆ … ┆ null   ┆ null         ┆ null       ┆ null       │
│ P131816 ┆ null ┆ null        ┆ null        ┆ … ┆ null   ┆ null         ┆ null       ┆ null       │
│ P132717 ┆ null ┆ null        ┆ null        ┆ … ┆ null   ┆ null         ┆ null       ┆ null       │
│ P132724 ┆ null ┆ null        ┆ null        ┆ … ┆ null   ┆ null         ┆ null       ┆ null       │
└─────────┴──────┴─────────────┴─────────────┴───┴────────┴──────────────┴────────────┴────────────┘

In [94]:
# Transitions

# purine : A <-> G 
# Pyrimidine : C <-> T


def is_transition(str1 , str2):
    # Purine
    if(isinstance(str1,str) & isinstance(str2,str)):
        if( (str1=="A" and str2 == "G") | (str1 == "G") and (str2 == "A")):
            return 1
        elif((str1=="C" and str2 == "T") | (str1 == "T") and (str2 == "C")):
            return 1
        else:
            return 0
    


mol_df = mol_df.with_columns(
    pl.struct(["REF", "ALT"]).map_elements(
        lambda row: is_transition(row["REF"], row["ALT"]) , return_dtype=pl.Int32
    ).alias("is_transition")
)

In [95]:
def is_transversion(str1 , str2):
    nucleotide = (str1,str2)
    trans_vers = [("A" ,"C") , ("C","A") , ("C" , "G") , ("G" , "C") , ("G" , "T" ) , ("T" ,  "G") , ("A" , "T") , ("T" , "A")]
    
    
    return int(nucleotide in trans_vers)


mol_df = mol_df.with_columns(
    pl.struct(["REF", "ALT"]).map_elements(
        lambda row: is_transversion(row["REF"], row["ALT"]) , return_dtype=pl.Int32
    ).alias("is_transversion")
)

In [96]:
# Insertion - deletion

def is_indel(str1 , str2):
    if(isinstance(str1,str) & isinstance(str2,str)):
        return int(len(str1) != len(str2))
    

mol_df = mol_df.with_columns(
    pl.struct(["REF", "ALT"]).map_elements(
        lambda row: is_indel(row["REF"], row["ALT"]) , return_dtype=pl.Int32
    ).alias("is_indel")
)

In [97]:
mol_df.filter(pl.col("REF").is_null())

shape: (114, 17)
┌─────────┬──────┬───────┬──────┬───┬────────────┬───────────────┬─────────────────┬──────────┐
│ ID      ┆ CHR  ┆ START ┆ END  ┆ … ┆ ALT_length ┆ is_transition ┆ is_transversion ┆ is_indel │
│ ---     ┆ ---  ┆ ---   ┆ ---  ┆   ┆ ---        ┆ ---           ┆ ---             ┆ ---      │
│ str     ┆ str  ┆ f64   ┆ f64  ┆   ┆ u32        ┆ i32           ┆ i32             ┆ i32      │
╞═════════╪══════╪═══════╪══════╪═══╪════════════╪═══════════════╪═════════════════╪══════════╡
│ P100016 ┆ null ┆ null  ┆ null ┆ … ┆ null       ┆ null          ┆ 0               ┆ null     │
│ P100022 ┆ null ┆ null  ┆ null ┆ … ┆ null       ┆ null          ┆ 0               ┆ null     │
│ P100123 ┆ null ┆ null  ┆ null ┆ … ┆ null       ┆ null          ┆ 0               ┆ null     │
│ P100348 ┆ null ┆ null  ┆ null ┆ … ┆ null       ┆ null          ┆ 0               ┆ null     │
│ P102822 ┆ null ┆ null  ┆ null ┆ … ┆ null       ┆ null          ┆ 0               ┆ null     │
│ …       ┆ …    ┆ …     ┆ …    ┆ … ┆ …          ┆ …             ┆ …               ┆ …        │
│ P131472 ┆ null ┆ null  ┆ null ┆ … ┆ null       ┆ null          ┆ 0               ┆ null     │
│ P131505 ┆ null ┆ null  ┆ null ┆ … ┆ null       ┆ null          ┆ 0               ┆ null     │
│ P131816 ┆ null ┆ null  ┆ null ┆ … ┆ null       ┆ null          ┆ 0               ┆ null     │
│ P132717 ┆ null ┆ null  ┆ null ┆ … ┆ null       ┆ null          ┆ 0               ┆ null     │
│ P132724 ┆ null ┆ null  ┆ null ┆ … ┆ null       ┆ null          ┆ 0               ┆ null     │
└─────────┴──────┴───────┴──────┴───┴────────────┴───────────────┴─────────────────┴──────────┘

# TRAITEMENT DE MOLECULAR DATA SET

In [98]:
df_mol_cl = mol_df.join(cl_df , on="ID" , how="left")

df_mol_cl

shape: (10_935, 25)
┌─────────┬──────┬──────────────┬──────────────┬───┬───────────┬───────┬───────┬───────────────────┐
│ ID      ┆ CHR  ┆ START        ┆ END          ┆ … ┆ MONOCYTES ┆ HB    ┆ PLT   ┆ CYTOGENETICS      │
│ ---     ┆ ---  ┆ ---          ┆ ---          ┆   ┆ ---       ┆ ---   ┆ ---   ┆ ---               │
│ str     ┆ str  ┆ f64          ┆ f64          ┆   ┆ f64       ┆ f64   ┆ f64   ┆ str               │
╞═════════╪══════╪══════════════╪══════════════╪═══╪═══════════╪═══════╪═══════╪═══════════════════╡
│ P100000 ┆ 11   ┆ 1.19149248e8 ┆ 1.19149248e8 ┆ … ┆ null      ┆ 8.8   ┆ 406.0 ┆ 46,xx,del(5)(q15q │
│         ┆      ┆              ┆              ┆   ┆           ┆       ┆       ┆ 33.3)[3]/46,x…    │
│ P100000 ┆ 5    ┆ 1.31822301e8 ┆ 1.31822301e8 ┆ … ┆ null      ┆ 8.8   ┆ 406.0 ┆ 46,xx,del(5)(q15q │
│         ┆      ┆              ┆              ┆   ┆           ┆       ┆       ┆ 33.3)[3]/46,x…    │
│ P100000 ┆ 3    ┆ 7.769406e7   ┆ 7.769406e7   ┆ … ┆ null      ┆ 8.8   ┆ 406.0 ┆ 46,xx,del(5)(q15q │
│         ┆      ┆              ┆              ┆   ┆           ┆       ┆       ┆ 33.3)[3]/46,x…    │
│ P100000 ┆ 4    ┆ 1.06164917e8 ┆ 1.06164917e8 ┆ … ┆ null      ┆ 8.8   ┆ 406.0 ┆ 46,xx,del(5)(q15q │
│         ┆      ┆              ┆              ┆   ┆           ┆       ┆       ┆ 33.3)[3]/46,x…    │
│ P100000 ┆ 2    ┆ 2.5468147e7  ┆ 2.5468163e7  ┆ … ┆ null      ┆ 8.8   ┆ 406.0 ┆ 46,xx,del(5)(q15q │
│         ┆      ┆              ┆              ┆   ┆           ┆       ┆       ┆ 33.3)[3]/46,x…    │
│ …       ┆ …    ┆ …            ┆ …            ┆ … ┆ …         ┆ …     ┆ …     ┆ …                 │
│ P131472 ┆ null ┆ null         ┆ null         ┆ … ┆ 0.65      ┆ 11.52 ┆ 16.0  ┆ 46,xy,del(20)(q)  │
│ P131505 ┆ null ┆ null         ┆ null         ┆ … ┆ null      ┆ 10.34 ┆ 66.0  ┆ 45,x,-y/46,xy     │
│ P131816 ┆ null ┆ null         ┆ null         ┆ … ┆ 19.4      ┆ 8.0   ┆ 155.0 ┆ 46,xx[20]         │
│ P132717 ┆ null ┆ null         ┆ null         ┆ … ┆ 0.1       ┆ 8.9   ┆ 51.0  ┆ 46,xx[20]trisomy8 │
│         ┆      ┆              ┆              ┆   ┆           ┆       ┆       ┆ onfish            │
│ P132724 ┆ null ┆ null         ┆ null         ┆ … ┆ 0.0       ┆ 10.4  ┆ 172.0 ┆ complex           │
└─────────┴──────┴──────────────┴──────────────┴───┴───────────┴───────┴───────┴───────────────────┘

In [99]:
df_mol_cl = df_mol_cl.join(y_train , on="ID"  , how="left")

df_mol_cl

shape: (10_935, 27)
┌─────────┬──────┬──────────────┬──────────────┬───┬───────┬────────────────┬──────────┬───────────┐
│ ID      ┆ CHR  ┆ START        ┆ END          ┆ … ┆ PLT   ┆ CYTOGENETICS   ┆ OS_YEARS ┆ OS_STATUS │
│ ---     ┆ ---  ┆ ---          ┆ ---          ┆   ┆ ---   ┆ ---            ┆ ---      ┆ ---       │
│ str     ┆ str  ┆ f64          ┆ f64          ┆   ┆ f64   ┆ str            ┆ f64      ┆ f64       │
╞═════════╪══════╪══════════════╪══════════════╪═══╪═══════╪════════════════╪══════════╪═══════════╡
│ P100000 ┆ 11   ┆ 1.19149248e8 ┆ 1.19149248e8 ┆ … ┆ 406.0 ┆ 46,xx,del(5)(q ┆ 5.819178 ┆ 0.0       │
│         ┆      ┆              ┆              ┆   ┆       ┆ 15q33.3)[3]/46 ┆          ┆           │
│         ┆      ┆              ┆              ┆   ┆       ┆ ,x…            ┆          ┆           │
│ P100000 ┆ 5    ┆ 1.31822301e8 ┆ 1.31822301e8 ┆ … ┆ 406.0 ┆ 46,xx,del(5)(q ┆ 5.819178 ┆ 0.0       │
│         ┆      ┆              ┆              ┆   ┆       ┆ 15q33.3)[3]/46 ┆          ┆           │
│         ┆      ┆              ┆              ┆   ┆       ┆ ,x…            ┆          ┆           │
│ P100000 ┆ 3    ┆ 7.769406e7   ┆ 7.769406e7   ┆ … ┆ 406.0 ┆ 46,xx,del(5)(q ┆ 5.819178 ┆ 0.0       │
│         ┆      ┆              ┆              ┆   ┆       ┆ 15q33.3)[3]/46 ┆          ┆           │
│         ┆      ┆              ┆              ┆   ┆       ┆ ,x…            ┆          ┆           │
│ P100000 ┆ 4    ┆ 1.06164917e8 ┆ 1.06164917e8 ┆ … ┆ 406.0 ┆ 46,xx,del(5)(q ┆ 5.819178 ┆ 0.0       │
│         ┆      ┆              ┆              ┆   ┆       ┆ 15q33.3)[3]/46 ┆          ┆           │
│         ┆      ┆              ┆              ┆   ┆       ┆ ,x…            ┆          ┆           │
│ P100000 ┆ 2    ┆ 2.5468147e7  ┆ 2.5468163e7  ┆ … ┆ 406.0 ┆ 46,xx,del(5)(q ┆ 5.819178 ┆ 0.0       │
│         ┆      ┆              ┆              ┆   ┆       ┆ 15q33.3)[3]/46 ┆          ┆           │
│         ┆      ┆              ┆              ┆   ┆       ┆ ,x…            ┆          ┆           │
│ …       ┆ …    ┆ …            ┆ …            ┆ … ┆ …     ┆ …              ┆ …        ┆ …         │
│ P131472 ┆ null ┆ null         ┆ null         ┆ … ┆ 16.0  ┆ 46,xy,del(20)( ┆ 0.671233 ┆ 0.0       │
│         ┆      ┆              ┆              ┆   ┆       ┆ q)             ┆          ┆           │
│ P131505 ┆ null ┆ null         ┆ null         ┆ … ┆ 66.0  ┆ 45,x,-y/46,xy  ┆ 3.69589  ┆ 0.0       │
│ P131816 ┆ null ┆ null         ┆ null         ┆ … ┆ 155.0 ┆ 46,xx[20]      ┆ 0.468493 ┆ 1.0       │
│ P132717 ┆ null ┆ null         ┆ null         ┆ … ┆ 51.0  ┆ 46,xx[20]triso ┆ 3.589041 ┆ 1.0       │
│         ┆      ┆              ┆              ┆   ┆       ┆ my8onfish      ┆          ┆           │
│ P132724 ┆ null ┆ null         ┆ null         ┆ … ┆ 172.0 ┆ complex        ┆ 0.347945 ┆ 1.0       │
└─────────┴──────┴──────────────┴──────────────┴───┴───────┴────────────────┴──────────┴───────────┘

In [100]:
def is_snv_REF(df , col , letter):
    df = df.with_columns(
        pl.when((pl.col(col) == letter))
        .then(1)
        .otherwise(0)
        .alias(f"{col}_{letter}")
    )
    
    return df

snv_REF  = ['A','C','G','T']

for snv in snv_REF:
    mol_df =  is_snv_REF(mol_df , "REF" , snv)
    
    
mol_df

shape: (10_935, 21)
┌─────────┬──────┬──────────────┬──────────────┬───┬───────┬───────┬───────┬───────┐
│ ID      ┆ CHR  ┆ START        ┆ END          ┆ … ┆ REF_A ┆ REF_C ┆ REF_G ┆ REF_T │
│ ---     ┆ ---  ┆ ---          ┆ ---          ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ str     ┆ str  ┆ f64          ┆ f64          ┆   ┆ i32   ┆ i32   ┆ i32   ┆ i32   │
╞═════════╪══════╪══════════════╪══════════════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ P100000 ┆ 11   ┆ 1.19149248e8 ┆ 1.19149248e8 ┆ … ┆ 0     ┆ 0     ┆ 1     ┆ 0     │
│ P100000 ┆ 5    ┆ 1.31822301e8 ┆ 1.31822301e8 ┆ … ┆ 0     ┆ 0     ┆ 1     ┆ 0     │
│ P100000 ┆ 3    ┆ 7.769406e7   ┆ 7.769406e7   ┆ … ┆ 0     ┆ 0     ┆ 1     ┆ 0     │
│ P100000 ┆ 4    ┆ 1.06164917e8 ┆ 1.06164917e8 ┆ … ┆ 0     ┆ 0     ┆ 1     ┆ 0     │
│ P100000 ┆ 2    ┆ 2.5468147e7  ┆ 2.5468163e7  ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 0     │
│ …       ┆ …    ┆ …            ┆ …            ┆ … ┆ …     ┆ …     ┆ …     ┆ …     │
│ P131472 ┆ null ┆ null         ┆ null         ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 0     │
│ P131505 ┆ null ┆ null         ┆ null         ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 0     │
│ P131816 ┆ null ┆ null         ┆ null         ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 0     │
│ P132717 ┆ null ┆ null         ┆ null         ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 0     │
│ P132724 ┆ null ┆ null         ┆ null         ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 0     │
└─────────┴──────┴──────────────┴──────────────┴───┴───────┴───────┴───────┴───────┘

In [101]:
for snv in snv_REF:
    mol_df = is_snv_REF(mol_df , "ALT" , snv)
    
mol_df

shape: (10_935, 25)
┌─────────┬──────┬──────────────┬──────────────┬───┬───────┬───────┬───────┬───────┐
│ ID      ┆ CHR  ┆ START        ┆ END          ┆ … ┆ ALT_A ┆ ALT_C ┆ ALT_G ┆ ALT_T │
│ ---     ┆ ---  ┆ ---          ┆ ---          ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ str     ┆ str  ┆ f64          ┆ f64          ┆   ┆ i32   ┆ i32   ┆ i32   ┆ i32   │
╞═════════╪══════╪══════════════╪══════════════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ P100000 ┆ 11   ┆ 1.19149248e8 ┆ 1.19149248e8 ┆ … ┆ 1     ┆ 0     ┆ 0     ┆ 0     │
│ P100000 ┆ 5    ┆ 1.31822301e8 ┆ 1.31822301e8 ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 1     │
│ P100000 ┆ 3    ┆ 7.769406e7   ┆ 7.769406e7   ┆ … ┆ 0     ┆ 1     ┆ 0     ┆ 0     │
│ P100000 ┆ 4    ┆ 1.06164917e8 ┆ 1.06164917e8 ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 1     │
│ P100000 ┆ 2    ┆ 2.5468147e7  ┆ 2.5468163e7  ┆ … ┆ 1     ┆ 0     ┆ 0     ┆ 0     │
│ …       ┆ …    ┆ …            ┆ …            ┆ … ┆ …     ┆ …     ┆ …     ┆ …     │
│ P131472 ┆ null ┆ null         ┆ null         ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 0     │
│ P131505 ┆ null ┆ null         ┆ null         ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 0     │
│ P131816 ┆ null ┆ null         ┆ null         ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 0     │
│ P132717 ┆ null ┆ null         ┆ null         ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 0     │
│ P132724 ┆ null ┆ null         ┆ null         ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 0     │
└─────────┴──────┴──────────────┴──────────────┴───┴───────┴───────┴───────┴───────┘

In [102]:
def complex_nucleotide(df , col ):
    df = df.with_columns(
        pl.when(pl.col(col).str.len_chars() > 1)
        .then(1)
        .otherwise(0)
        .alias(f"complex_nucleotide_{col}")
    )
    
    return df

mol_df = complex_nucleotide(mol_df , "REF")
mol_df = complex_nucleotide(mol_df , "ALT")

In [103]:
mol_df

shape: (10_935, 27)
┌─────────┬──────┬──────────────┬──────────────┬───┬───────┬───────┬───────────────┬───────────────┐
│ ID      ┆ CHR  ┆ START        ┆ END          ┆ … ┆ ALT_G ┆ ALT_T ┆ complex_nucle ┆ complex_nucle │
│ ---     ┆ ---  ┆ ---          ┆ ---          ┆   ┆ ---   ┆ ---   ┆ otide_REF     ┆ otide_ALT     │
│ str     ┆ str  ┆ f64          ┆ f64          ┆   ┆ i32   ┆ i32   ┆ ---           ┆ ---           │
│         ┆      ┆              ┆              ┆   ┆       ┆       ┆ i32           ┆ i32           │
╞═════════╪══════╪══════════════╪══════════════╪═══╪═══════╪═══════╪═══════════════╪═══════════════╡
│ P100000 ┆ 11   ┆ 1.19149248e8 ┆ 1.19149248e8 ┆ … ┆ 0     ┆ 0     ┆ 0             ┆ 0             │
│ P100000 ┆ 5    ┆ 1.31822301e8 ┆ 1.31822301e8 ┆ … ┆ 0     ┆ 1     ┆ 0             ┆ 0             │
│ P100000 ┆ 3    ┆ 7.769406e7   ┆ 7.769406e7   ┆ … ┆ 0     ┆ 0     ┆ 0             ┆ 0             │
│ P100000 ┆ 4    ┆ 1.06164917e8 ┆ 1.06164917e8 ┆ … ┆ 0     ┆ 1     ┆ 0             ┆ 0             │
│ P100000 ┆ 2    ┆ 2.5468147e7  ┆ 2.5468163e7  ┆ … ┆ 0     ┆ 0     ┆ 1             ┆ 0             │
│ …       ┆ …    ┆ …            ┆ …            ┆ … ┆ …     ┆ …     ┆ …             ┆ …             │
│ P131472 ┆ null ┆ null         ┆ null         ┆ … ┆ 0     ┆ 0     ┆ 0             ┆ 0             │
│ P131505 ┆ null ┆ null         ┆ null         ┆ … ┆ 0     ┆ 0     ┆ 0             ┆ 0             │
│ P131816 ┆ null ┆ null         ┆ null         ┆ … ┆ 0     ┆ 0     ┆ 0             ┆ 0             │
│ P132717 ┆ null ┆ null         ┆ null         ┆ … ┆ 0     ┆ 0     ┆ 0             ┆ 0             │
│ P132724 ┆ null ┆ null         ┆ null         ┆ … ┆ 0     ┆ 0     ┆ 0             ┆ 0             │
└─────────┴──────┴──────────────┴──────────────┴───┴───────┴───────┴───────────────┴───────────────┘

In [104]:
lst_ref = mol_df.filter(pl.col("REF").str.len_chars() > 1)["REF"].unique().to_list()

for ref in lst_ref:
    for ch in ref:
        if ch not in ['A','C','G','T']:
            print(ref)

In [105]:
def is_SNV(df , col):
    df = df.with_columns(
        pl.when(pl.col(col).str.len_chars() == 1)
        .then(1)
        .otherwise(0)
        .alias(f"{col} is_SNV")
    )
    
    return df

mol_df = is_SNV(mol_df,"REF")

mol_df

shape: (10_935, 28)
┌─────────┬──────┬──────────────┬─────────────┬───┬───────┬─────────────┬─────────────┬────────────┐
│ ID      ┆ CHR  ┆ START        ┆ END         ┆ … ┆ ALT_T ┆ complex_nuc ┆ complex_nuc ┆ REF is_SNV │
│ ---     ┆ ---  ┆ ---          ┆ ---         ┆   ┆ ---   ┆ leotide_REF ┆ leotide_ALT ┆ ---        │
│ str     ┆ str  ┆ f64          ┆ f64         ┆   ┆ i32   ┆ ---         ┆ ---         ┆ i32        │
│         ┆      ┆              ┆             ┆   ┆       ┆ i32         ┆ i32         ┆            │
╞═════════╪══════╪══════════════╪═════════════╪═══╪═══════╪═════════════╪═════════════╪════════════╡
│ P100000 ┆ 11   ┆ 1.19149248e8 ┆ 1.19149248e ┆ … ┆ 0     ┆ 0           ┆ 0           ┆ 1          │
│         ┆      ┆              ┆ 8           ┆   ┆       ┆             ┆             ┆            │
│ P100000 ┆ 5    ┆ 1.31822301e8 ┆ 1.31822301e ┆ … ┆ 1     ┆ 0           ┆ 0           ┆ 1          │
│         ┆      ┆              ┆ 8           ┆   ┆       ┆             ┆             ┆            │
│ P100000 ┆ 3    ┆ 7.769406e7   ┆ 7.769406e7  ┆ … ┆ 0     ┆ 0           ┆ 0           ┆ 1          │
│ P100000 ┆ 4    ┆ 1.06164917e8 ┆ 1.06164917e ┆ … ┆ 1     ┆ 0           ┆ 0           ┆ 1          │
│         ┆      ┆              ┆ 8           ┆   ┆       ┆             ┆             ┆            │
│ P100000 ┆ 2    ┆ 2.5468147e7  ┆ 2.5468163e7 ┆ … ┆ 0     ┆ 1           ┆ 0           ┆ 0          │
│ …       ┆ …    ┆ …            ┆ …           ┆ … ┆ …     ┆ …           ┆ …           ┆ …          │
│ P131472 ┆ null ┆ null         ┆ null        ┆ … ┆ 0     ┆ 0           ┆ 0           ┆ 0          │
│ P131505 ┆ null ┆ null         ┆ null        ┆ … ┆ 0     ┆ 0           ┆ 0           ┆ 0          │
│ P131816 ┆ null ┆ null         ┆ null        ┆ … ┆ 0     ┆ 0           ┆ 0           ┆ 0          │
│ P132717 ┆ null ┆ null         ┆ null        ┆ … ┆ 0     ┆ 0           ┆ 0           ┆ 0          │
│ P132724 ┆ null ┆ null         ┆ null        ┆ … ┆ 0     ┆ 0           ┆ 0           ┆ 0          │
└─────────┴──────┴──────────────┴─────────────┴───┴───────┴─────────────┴─────────────┴────────────┘

In [106]:
mol_df.group_by(["GENE", "EFFECT"]).agg(
        pl.len().alias("mutations_per_gene_effect")
    )

shape: (344, 3)
┌────────┬──────────────────────┬───────────────────────────┐
│ GENE   ┆ EFFECT               ┆ mutations_per_gene_effect │
│ ---    ┆ ---                  ┆ ---                       │
│ str    ┆ str                  ┆ u32                       │
╞════════╪══════════════════════╪═══════════════════════════╡
│ EGFR   ┆ non_synonymous_codon ┆ 10                        │
│ CEBPA  ┆ non_synonymous_codon ┆ 26                        │
│ FLT3   ┆ non_synonymous_codon ┆ 30                        │
│ TP53   ┆ inframe_codon_gain   ┆ 2                         │
│ ETV6   ┆ frameshift_variant   ┆ 32                        │
│ …      ┆ …                    ┆ …                         │
│ ARID1A ┆ splice_site_variant  ┆ 1                         │
│ CALR   ┆ inframe_codon_gain   ┆ 1                         │
│ SH2B3  ┆ splice_site_variant  ┆ 1                         │
│ DDX41  ┆ splice_site_variant  ┆ 5                         │
│ CTCF   ┆ frameshift_variant   ┆ 7                         │
└────────┴──────────────────────┴───────────────────────────┘

In [107]:
def add_mutation_density_features(mol_df):
    """Add mutation density features to the molecular dataframe"""

    # Count mutations per gene
    gene_counts = mol_df.group_by("GENE").agg(
        pl.len().alias("mutations_per_gene")
    )

    # Count mutations per gene and effect type
    gene_effect_counts = mol_df.group_by(["GENE", "EFFECT"]).agg(
        pl.len().alias("mutations_per_gene_effect")
    )

    # Count mutations per chromosome region (binned)
    region_counts = mol_df.group_by(["CHR", "START"]).agg(
        pl.count().alias("mutations_per_region")
    )

    # Join these counts back to the original dataframe
    mol_df = mol_df.join(gene_counts, on="GENE", how="left")

    # For gene-effect counts, we need to join on both columns
    mol_df = mol_df.join(gene_effect_counts, on=["GENE", "EFFECT"], how="left")
    
    # Join region counts
    mol_df = mol_df.join(region_counts, on=["CHR", "START"], how="left")

    return mol_df


mol_df = add_mutation_density_features(mol_df)

C:\Users\zakar\AppData\Local\Temp\ipykernel_16716\609172987.py:16: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
  pl.count().alias("mutations_per_region")

In [108]:
mol_df

shape: (10_935, 31)
┌─────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ ID      ┆ CHR  ┆ START      ┆ END        ┆ … ┆ REF is_SNV ┆ mutations_ ┆ mutations_ ┆ mutations_ │
│ ---     ┆ ---  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ per_gene   ┆ per_gene_e ┆ per_region │
│ str     ┆ str  ┆ f64        ┆ f64        ┆   ┆ i32        ┆ ---        ┆ ffect      ┆ ---        │
│         ┆      ┆            ┆            ┆   ┆            ┆ u32        ┆ ---        ┆ u32        │
│         ┆      ┆            ┆            ┆   ┆            ┆            ┆ u32        ┆            │
╞═════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ P100000 ┆ 11   ┆ 1.19149248 ┆ 1.19149248 ┆ … ┆ 1          ┆ 228        ┆ 163        ┆ 1          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 5    ┆ 1.31822301 ┆ 1.31822301 ┆ … ┆ 1          ┆ 22         ┆ 4          ┆ 1          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 3    ┆ 7.769406e7 ┆ 7.769406e7 ┆ … ┆ 1          ┆ 17         ┆ 3          ┆ 3          │
│ P100000 ┆ 4    ┆ 1.06164917 ┆ 1.06164917 ┆ … ┆ 1          ┆ 1663       ┆ 417        ┆ 4          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 2    ┆ 2.5468147e ┆ 2.5468163e ┆ … ┆ 0          ┆ 604        ┆ 93         ┆ 1          │
│         ┆      ┆ 7          ┆ 7          ┆   ┆            ┆            ┆            ┆            │
│ …       ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ P131472 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 96         ┆ 89         ┆ null       │
│ P131505 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 96         ┆ 89         ┆ null       │
│ P131816 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 96         ┆ 89         ┆ null       │
│ P132717 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 96         ┆ 89         ┆ null       │
│ P132724 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 96         ┆ 89         ┆ null       │
└─────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [109]:
mol_df.describe()

shape: (9, 32)
┌────────────┬─────────┬───────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ statistic  ┆ ID      ┆ CHR   ┆ START      ┆ … ┆ REF is_SNV ┆ mutations_ ┆ mutations_ ┆ mutations │
│ ---        ┆ ---     ┆ ---   ┆ ---        ┆   ┆ ---        ┆ per_gene   ┆ per_gene_e ┆ _per_regi │
│ str        ┆ str     ┆ str   ┆ f64        ┆   ┆ f64        ┆ ---        ┆ ffect      ┆ on        │
│            ┆         ┆       ┆            ┆   ┆            ┆ f64        ┆ ---        ┆ ---       │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆ f64        ┆ f64       │
╞════════════╪═════════╪═══════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ count      ┆ 10935   ┆ 10821 ┆ 10821.0    ┆ … ┆ 10935.0    ┆ 10935.0    ┆ 10935.0    ┆ 10821.0   │
│ null_count ┆ 0       ┆ 114   ┆ 114.0      ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 114.0     │
│ mean       ┆ null    ┆ null  ┆ 8.0783e7   ┆ … ┆ 0.8385     ┆ 576.027709 ┆ 283.047371 ┆ 65.785879 │
│ std        ┆ null    ┆ null  ┆ 5.6427e7   ┆ … ┆ 0.368008   ┆ 539.530171 ┆ 264.147822 ┆ 138.89073 │
│ min        ┆ P100000 ┆ 1     ┆ 394899.0   ┆ … ┆ 0.0        ┆ 1.0        ┆ 1.0        ┆ 1.0       │
│ 25%        ┆ null    ┆ null  ┆ 3.1022441e ┆ … ┆ 1.0        ┆ 149.0      ┆ 51.0       ┆ 1.0       │
│            ┆         ┆       ┆ 7          ┆   ┆            ┆            ┆            ┆           │
│ 50%        ┆ null    ┆ null  ┆ 7.4732959e ┆ … ┆ 1.0        ┆ 487.0      ┆ 166.0      ┆ 3.0       │
│            ┆         ┆       ┆ 7          ┆   ┆            ┆            ┆            ┆           │
│ 75%        ┆ null    ┆ null  ┆ 1.15258747 ┆ … ┆ 1.0        ┆ 775.0      ┆ 449.0      ┆ 33.0      │
│            ┆         ┆       ┆ e8         ┆   ┆            ┆            ┆            ┆           │
│ max        ┆ P132729 ┆ X     ┆ 2.26252135 ┆ … ┆ 1.0        ┆ 1663.0     ┆ 773.0      ┆ 485.0     │
│            ┆         ┆       ┆ e8         ┆   ┆            ┆            ┆            ┆           │
└────────────┴─────────┴───────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [110]:
mol_df.null_count()

shape: (1, 31)
┌─────┬─────┬───────┬─────┬───┬────────────┬──────────────────┬──────────────────┬─────────────────┐
│ ID  ┆ CHR ┆ START ┆ END ┆ … ┆ REF is_SNV ┆ mutations_per_ge ┆ mutations_per_ge ┆ mutations_per_r │
│ --- ┆ --- ┆ ---   ┆ --- ┆   ┆ ---        ┆ ne               ┆ ne_effect        ┆ egion           │
│ u32 ┆ u32 ┆ u32   ┆ u32 ┆   ┆ u32        ┆ ---              ┆ ---              ┆ ---             │
│     ┆     ┆       ┆     ┆   ┆            ┆ u32              ┆ u32              ┆ u32             │
╞═════╪═════╪═══════╪═════╪═══╪════════════╪══════════════════╪══════════════════╪═════════════════╡
│ 0   ┆ 114 ┆ 114   ┆ 114 ┆ … ┆ 0          ┆ 0                ┆ 0                ┆ 114             │
└─────┴─────┴───────┴─────┴───┴────────────┴──────────────────┴──────────────────┴─────────────────┘

In [111]:
def iqr_method(df , cl_lst):

    for (index , cl )  in enumerate(cl_lst):
        q1 = df.select(pl.col(cl).quantile(0.25)).item()
        q3 = df.select(pl.col(cl).quantile(0.75)).item()
        
        iqr = q3 - q1
        
        
        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr

        
        # Winsorisation : capped values
        df = df.with_columns(
            pl.when(pl.col(cl) < lower_bound).then(lower_bound)
            .when(pl.col(cl) > upper_bound).then(upper_bound)
            .otherwise(pl.col(cl))
            .alias(cl)
        )
        
        
        
    return df

mol_df = iqr_method(mol_df , ["VAF" , "DEPTH" , "START" , "END"])

In [112]:
mol_df.describe()

shape: (9, 32)
┌────────────┬─────────┬───────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ statistic  ┆ ID      ┆ CHR   ┆ START      ┆ … ┆ REF is_SNV ┆ mutations_ ┆ mutations_ ┆ mutations │
│ ---        ┆ ---     ┆ ---   ┆ ---        ┆   ┆ ---        ┆ per_gene   ┆ per_gene_e ┆ _per_regi │
│ str        ┆ str     ┆ str   ┆ f64        ┆   ┆ f64        ┆ ---        ┆ ffect      ┆ on        │
│            ┆         ┆       ┆            ┆   ┆            ┆ f64        ┆ ---        ┆ ---       │
│            ┆         ┆       ┆            ┆   ┆            ┆            ┆ f64        ┆ f64       │
╞════════════╪═════════╪═══════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ count      ┆ 10935   ┆ 10821 ┆ 10821.0    ┆ … ┆ 10935.0    ┆ 10935.0    ┆ 10935.0    ┆ 10821.0   │
│ null_count ┆ 0       ┆ 114   ┆ 114.0      ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 114.0     │
│ mean       ┆ null    ┆ null  ┆ 8.0783e7   ┆ … ┆ 0.8385     ┆ 576.027709 ┆ 283.047371 ┆ 65.785879 │
│ std        ┆ null    ┆ null  ┆ 5.6427e7   ┆ … ┆ 0.368008   ┆ 539.530171 ┆ 264.147822 ┆ 138.89073 │
│ min        ┆ P100000 ┆ 1     ┆ 394899.0   ┆ … ┆ 0.0        ┆ 1.0        ┆ 1.0        ┆ 1.0       │
│ 25%        ┆ null    ┆ null  ┆ 3.1022441e ┆ … ┆ 1.0        ┆ 149.0      ┆ 51.0       ┆ 1.0       │
│            ┆         ┆       ┆ 7          ┆   ┆            ┆            ┆            ┆           │
│ 50%        ┆ null    ┆ null  ┆ 7.4732959e ┆ … ┆ 1.0        ┆ 487.0      ┆ 166.0      ┆ 3.0       │
│            ┆         ┆       ┆ 7          ┆   ┆            ┆            ┆            ┆           │
│ 75%        ┆ null    ┆ null  ┆ 1.15258747 ┆ … ┆ 1.0        ┆ 775.0      ┆ 449.0      ┆ 33.0      │
│            ┆         ┆       ┆ e8         ┆   ┆            ┆            ┆            ┆           │
│ max        ┆ P132729 ┆ X     ┆ 2.26252135 ┆ … ┆ 1.0        ┆ 1663.0     ┆ 773.0      ┆ 485.0     │
│            ┆         ┆       ┆ e8         ┆   ┆            ┆            ┆            ┆           │
└────────────┴─────────┴───────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

# VAF , DEPTH TREATMENT (FAIT)

In [113]:
quant_vars = ["VAF" , "DEPTH"]
sub_df = mol_df.select(quant_vars)

# Conver to pandas
sub_pd = sub_df.to_pandas()
 
# Apply Model-Based Imputation (Random Forest)
imputer = IterativeImputer(estimator=RandomForestRegressor(), random_state=42)
imputed_data = imputer.fit_transform(sub_pd)

# 4. To Polars
imputed_pl = pl.DataFrame(imputed_data, schema=sub_df.columns)

# 5. Replace nulls
mol_df = mol_df.with_columns([imputed_pl[col].alias(col) for col in quant_vars])

c:\Users\zakar\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\impute\_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [114]:
mol_df

shape: (10_935, 31)
┌─────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ ID      ┆ CHR  ┆ START      ┆ END        ┆ … ┆ REF is_SNV ┆ mutations_ ┆ mutations_ ┆ mutations_ │
│ ---     ┆ ---  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ per_gene   ┆ per_gene_e ┆ per_region │
│ str     ┆ str  ┆ f64        ┆ f64        ┆   ┆ i32        ┆ ---        ┆ ffect      ┆ ---        │
│         ┆      ┆            ┆            ┆   ┆            ┆ u32        ┆ ---        ┆ u32        │
│         ┆      ┆            ┆            ┆   ┆            ┆            ┆ u32        ┆            │
╞═════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ P100000 ┆ 11   ┆ 1.19149248 ┆ 1.19149248 ┆ … ┆ 1          ┆ 228        ┆ 163        ┆ 1          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 5    ┆ 1.31822301 ┆ 1.31822301 ┆ … ┆ 1          ┆ 22         ┆ 4          ┆ 1          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 3    ┆ 7.769406e7 ┆ 7.769406e7 ┆ … ┆ 1          ┆ 17         ┆ 3          ┆ 3          │
│ P100000 ┆ 4    ┆ 1.06164917 ┆ 1.06164917 ┆ … ┆ 1          ┆ 1663       ┆ 417        ┆ 4          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 2    ┆ 2.5468147e ┆ 2.5468163e ┆ … ┆ 0          ┆ 604        ┆ 93         ┆ 1          │
│         ┆      ┆ 7          ┆ 7          ┆   ┆            ┆            ┆            ┆            │
│ …       ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ P131472 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 96         ┆ 89         ┆ null       │
│ P131505 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 96         ┆ 89         ┆ null       │
│ P131816 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 96         ┆ 89         ┆ null       │
│ P132717 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 96         ┆ 89         ┆ null       │
│ P132724 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 96         ┆ 89         ┆ null       │
└─────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [115]:
mol_df["CHR"].value_counts().to_numpy()

array([['11', 326],
       ['22', 55],
       [None, 114],
       ['18', 128],
       ['12', 596],
       ['1', 365],
       ['3', 115],
       ['10', 18],
       ['6', 3],
       ['8', 41],
       ['5', 369],
       ['16', 91],
       ['13', 42],
       ['X', 1204],
       ['21', 866],
       ['7', 537],
       ['15', 192],
       ['14', 4],
       ['20', 999],
       ['2', 1513],
       ['19', 155],
       ['9', 116],
       ['17', 1387],
       ['4', 1699]], dtype=object)

In [116]:
def to_int(str):
    if(str == 'X'):
        return 23 # A justifier ?
    else:
        return int(str)

mol_df = mol_df.with_columns(
    pl.col("CHR").map_elements(to_int , return_dtype=pl.Int64)
    .alias("CHR")
)

# ORDINAL ENCODING

In [117]:
def dna_to_array(dna):
    lst = []
    
    nitrogen_bases = ['a','g','t','c']
    dna = dna.lower()
    
    
    for ch in dna:
        if(ch in nitrogen_bases):
            lst.append(ch)
        else:
            lst.append('n')
        
        
    return lst

def ordinal_encoder_dna(dna):
    mapping = {'a' : 0.25 , 'c' : 0.5 ,'g':0.75 , 't' : 1.00}
    
    nitrogen_bases = ['a','g','t','c']
    
    return [mapping[x] if x in nitrogen_bases else 0.00 for x in dna ]

    


seq_test = 'TTCAGCCAGTG'
ordinal_encoder_dna(dna_to_array(seq_test))

[1.0, 1.0, 0.5, 0.25, 0.75, 0.5, 0.5, 0.25, 0.75, 1.0, 0.75]

# K-MER ENCODING

In [118]:
def extract_kmers(sequence, k):
    return [sequence[i:i+k] for i in range(len(sequence) - k + 1)]


def join_str(str):
    return ' '.join(str)



k = 7 # K-mer
mySeq= 'TCTCACACATGTGCCAATCACTGTCACCC' # DNA Sequence


print(f"Example of transformation of DNA sequence : {mySeq} with {k}-mer")
new_str = join_str(extract_kmers(mySeq, k=7))

print(f"Transformation : {new_str} ")

Example of transformation of DNA sequence : TCTCACACATGTGCCAATCACTGTCACCC with 7-mer
Transformation : TCTCACA CTCACAC TCACACA CACACAT ACACATG CACATGT ACATGTG CATGTGC ATGTGCC TGTGCCA GTGCCAA TGCCAAT GCCAATC CCAATCA CAATCAC AATCACT ATCACTG TCACTGT CACTGTC ACTGTCA CTGTCAC TGTCACC GTCACCC

In [119]:
from sklearn.feature_extraction.text import CountVectorizer


mySeq= 'TCTCACACATGTGCCAATCACTGTCACCC'
mySeq2 = 'GTGCCCAGGTTCAGTGAGTGACACAGGCAG'


DNA_list = [join_str(extract_kmers(mySeq,k=6)) , join_str(extract_kmers(mySeq2,k=6))]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(DNA_list).toarray()

print("Vocabulary: ", vectorizer.vocabulary_)


print(f"Encoded DNA : {X}")

Vocabulary:  {'tctcac': 41, 'ctcaca': 24, 'tcacac': 37, 'cacaca': 13, 'acacat': 2, 'cacatg': 15, 'acatgt': 4, 'catgtg': 20, 'atgtgc': 11, 'tgtgcc': 47, 'gtgcca': 34, 'tgccaa': 44, 'gccaat': 28, 'ccaatc': 21, 'caatca': 12, 'aatcac': 0, 'atcact': 10, 'tcactg': 39, 'cactgt': 16, 'actgtc': 5, 'ctgtca': 25, 'tgtcac': 46, 'gtcacc': 31, 'tcaccc': 38, 'gtgccc': 35, 'tgccca': 45, 'gcccag': 29, 'cccagg': 23, 'ccaggt': 22, 'caggtt': 18, 'aggttc': 7, 'ggttca': 30, 'gttcag': 36, 'ttcagt': 48, 'tcagtg': 40, 'cagtga': 19, 'agtgag': 9, 'gtgagt': 33, 'tgagtg': 43, 'gagtga': 27, 'agtgac': 8, 'gtgaca': 32, 'tgacac': 42, 'gacaca': 26, 'acacag': 1, 'cacagg': 14, 'acaggc': 3, 'caggca': 17, 'aggcag': 6}
Encoded DNA : [[1 0 1 0 1 1 0 0 0 0 1 1 1 1 0 1 1 0 0 0 1 1 0 0 1 1 0 0 1 0 0 1 0 0 1 0
  0 1 1 1 0 1 0 0 1 0 1 1 0]
 [0 1 0 1 0 0 1 1 1 1 0 0 0 0 1 0 0 1 1 1 0 0 1 1 0 0 1 1 0 1 1 0 1 1 0 1
  1 0 0 0 1 0 1 1 0 1 0 0 1]]

In [120]:
# TREAT THE REF with length <= 4 (arbitrary ?) and >4 differently ! 


k_mer_coef  = 4

mol_df = mol_df.with_columns(
    pl.when(pl.col("REF").str.len_chars() <= k_mer_coef)
    .then(pl.col("REF"))
    .otherwise(None) 
    .alias("REF_not_mer")
)

In [121]:
mol_df

shape: (10_935, 32)
┌─────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ ID      ┆ CHR  ┆ START      ┆ END        ┆ … ┆ mutations_ ┆ mutations_ ┆ mutations_ ┆ REF_not_me │
│ ---     ┆ ---  ┆ ---        ┆ ---        ┆   ┆ per_gene   ┆ per_gene_e ┆ per_region ┆ r          │
│ str     ┆ i64  ┆ f64        ┆ f64        ┆   ┆ ---        ┆ ffect      ┆ ---        ┆ ---        │
│         ┆      ┆            ┆            ┆   ┆ u32        ┆ ---        ┆ u32        ┆ str        │
│         ┆      ┆            ┆            ┆   ┆            ┆ u32        ┆            ┆            │
╞═════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ P100000 ┆ 11   ┆ 1.19149248 ┆ 1.19149248 ┆ … ┆ 228        ┆ 163        ┆ 1          ┆ G          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 5    ┆ 1.31822301 ┆ 1.31822301 ┆ … ┆ 22         ┆ 4          ┆ 1          ┆ G          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 3    ┆ 7.769406e7 ┆ 7.769406e7 ┆ … ┆ 17         ┆ 3          ┆ 3          ┆ G          │
│ P100000 ┆ 4    ┆ 1.06164917 ┆ 1.06164917 ┆ … ┆ 1663       ┆ 417        ┆ 4          ┆ G          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 2    ┆ 2.5468147e ┆ 2.5468163e ┆ … ┆ 604        ┆ 93         ┆ 1          ┆ null       │
│         ┆      ┆ 7          ┆ 7          ┆   ┆            ┆            ┆            ┆            │
│ …       ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ P131472 ┆ null ┆ null       ┆ null       ┆ … ┆ 96         ┆ 89         ┆ null       ┆ null       │
│ P131505 ┆ null ┆ null       ┆ null       ┆ … ┆ 96         ┆ 89         ┆ null       ┆ null       │
│ P131816 ┆ null ┆ null       ┆ null       ┆ … ┆ 96         ┆ 89         ┆ null       ┆ null       │
│ P132717 ┆ null ┆ null       ┆ null       ┆ … ┆ 96         ┆ 89         ┆ null       ┆ null       │
│ P132724 ┆ null ┆ null       ┆ null       ┆ … ┆ 96         ┆ 89         ┆ null       ┆ null       │
└─────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [122]:
import category_encoders as ce

mol_df_pd = mol_df.to_pandas()

encoder = ce.BinaryEncoder(cols=["REF_not_mer"])
mol_df = encoder.fit_transform(mol_df_pd)



mol_df = pl.from_pandas(mol_df)

mol_df

shape: (10_935, 38)
┌─────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ ID      ┆ CHR  ┆ START      ┆ END        ┆ … ┆ REF_not_me ┆ REF_not_me ┆ REF_not_me ┆ REF_not_me │
│ ---     ┆ ---  ┆ ---        ┆ ---        ┆   ┆ r_3        ┆ r_4        ┆ r_5        ┆ r_6        │
│ str     ┆ f64  ┆ f64        ┆ f64        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│         ┆      ┆            ┆            ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
╞═════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ P100000 ┆ 11.0 ┆ 1.19149248 ┆ 1.19149248 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 5.0  ┆ 1.31822301 ┆ 1.31822301 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 3.0  ┆ 7.769406e7 ┆ 7.769406e7 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│ P100000 ┆ 4.0  ┆ 1.06164917 ┆ 1.06164917 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 2.0  ┆ 2.5468147e ┆ 2.5468163e ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│         ┆      ┆ 7          ┆ 7          ┆   ┆            ┆            ┆            ┆            │
│ …       ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ P131472 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│ P131505 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│ P131816 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│ P132717 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│ P132724 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
└─────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

# GENE

In [123]:
mol_df["GENE"].unique()

shape: (124,)
Series: 'GENE' [str]
[
	"SETD2"
	"ARID2"
	"KIT"
	"STAT3"
	"ETV6"
	…
	"RUNX1"
	"SMG1"
	"ZRSR2"
	"JAK2"
	"DICER1"
]

# ANCIENNE NOMENCLATURE => NOUVELLES NOMENCLATURES

In [124]:
# MLL => KMT2A
# WHSC1 => NSD2
# H3F3A => H3-3A 
# FAM175A => ABRAXAS1
# PAPD5 => TENT4B

# NATIONAL LIBRARY OF MEDICINE

mapping = {'MLL' : 'KMT2A' , 'WHSC1' : 'NSD2' , 'H3F3A' : 'H3-3A' , 'FAM175A' : 'ABRAXAS1' , 'PAPD5' : 'TENT4B'}

mol_df = mol_df.with_columns(
    pl.col("GENE").map_elements(lambda g: mapping.get(g, g)).alias("GENE")
)

# EXPLIQUER CETTE ETAPE

C:\Users\zakar\AppData\Local\Temp\ipykernel_16716\126878532.py:11: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  mol_df = mol_df.with_columns(

In [125]:
mol_df

shape: (10_935, 38)
┌─────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ ID      ┆ CHR  ┆ START      ┆ END        ┆ … ┆ REF_not_me ┆ REF_not_me ┆ REF_not_me ┆ REF_not_me │
│ ---     ┆ ---  ┆ ---        ┆ ---        ┆   ┆ r_3        ┆ r_4        ┆ r_5        ┆ r_6        │
│ str     ┆ f64  ┆ f64        ┆ f64        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│         ┆      ┆            ┆            ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
╞═════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ P100000 ┆ 11.0 ┆ 1.19149248 ┆ 1.19149248 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 5.0  ┆ 1.31822301 ┆ 1.31822301 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 3.0  ┆ 7.769406e7 ┆ 7.769406e7 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│ P100000 ┆ 4.0  ┆ 1.06164917 ┆ 1.06164917 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 2.0  ┆ 2.5468147e ┆ 2.5468163e ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│         ┆      ┆ 7          ┆ 7          ┆   ┆            ┆            ┆            ┆            │
│ …       ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ P131472 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│ P131505 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│ P131816 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│ P132717 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│ P132724 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
└─────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

# CYTOGENETICS

In [126]:
import mygene

genes = list(mol_df["GENE"].unique())

mg = mygene.MyGeneInfo()

results = mg.querymany(genes, scopes="symbol", fields='go', species="human")

df_pathways = pd.DataFrame(results)

results

Input sequence provided is already in string format. No operation performed
Input sequence provided is already in string format. No operation performed

[{'query': 'H3-3A',
  '_id': '3020',
  '_score': 20.942583,
  'go': {'BP': [{'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0001556',
     'qualifier': 'involved_in',
     'term': 'oocyte maturation'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0001649',
     'qualifier': 'acts_upstream_of_or_within',
     'term': 'osteoblast differentiation'},
    {'evidence': 'IDA',
     'gocategory': 'BP',
     'id': 'GO:0006334',
     'pubmed': 21636898,
     'qualifier': 'involved_in',
     'term': 'nucleosome assembly'},
    {'evidence': 'IMP',
     'gocategory': 'BP',
     'id': 'GO:0006334',
     'pubmed': 25615412,
     'qualifier': 'involved_in',
     'term': 'nucleosome assembly'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0006997',
     'qualifier': 'acts_upstream_of_or_within',
     'term': 'nucleus organization'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0007283',
     'qualifier': 'acts_upstream_of_or_within',
     'term': 'spermatogenesis'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0007286',
     'qualifier': 'acts_upstream_of_or_within',
     'term': 'spermatid development'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0007338',
     'qualifier': 'acts_upstream_of_or_within',
     'term': 'single fertilization'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0007566',
     'qualifier': 'acts_upstream_of_or_within',
     'term': 'embryo implantation'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0008283',
     'qualifier': 'acts_upstream_of_or_within',
     'term': 'cell population proliferation'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0008584',
     'qualifier': 'acts_upstream_of_or_within',
     'term': 'male gonad development'},
    {'evidence': 'IMP',
     'gocategory': 'BP',
     'id': 'GO:0030307',
     'pubmed': 21274551,
     'qualifier': 'involved_in',
     'term': 'positive regulation of cell growth'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0031508',
     'qualifier': 'acts_upstream_of_or_within',
     'term': 'pericentric heterochromatin formation'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0031509',
     'qualifier': 'acts_upstream_of_or_within',
     'term': 'subtelomeric heterochromatin formation'},
    {'evidence': 'TAS',
     'gocategory': 'BP',
     'id': 'GO:0032200',
     'pubmed': 17675446,
     'qualifier': 'involved_in',
     'term': 'telomere organization'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0035264',
     'qualifier': 'acts_upstream_of_or_within',
     'term': 'multicellular organism growth'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0042692',
     'qualifier': 'acts_upstream_of_or_within',
     'term': 'muscle cell differentiation'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0048477',
     'qualifier': 'acts_upstream_of_or_within',
     'term': 'oogenesis'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0090230',
     'qualifier': 'acts_upstream_of_or_within',
     'term': 'regulation of centromere complex assembly'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:1902340',
     'qualifier': 'acts_upstream_of_or_within',
     'term': 'negative regulation of chromosome condensation'}],
   'CC': [{'evidence': 'IEA',
     'gocategory': 'CC',
     'id': 'GO:0000775',
     'qualifier': 'is_active_in',
     'term': 'chromosome, centromeric region'},
    {'evidence': 'IDA',
     'gocategory': 'CC',
     'id': 'GO:0000781',
     'pubmed': 20110566,
     'qualifier': 'located_in',
     'term': 'chromosome, telomeric region'},
    {'evidence': 'IEA',
     'gocategory': 'CC',
     'id': 'GO:0000785',
     'qualifier': 'is_active_in',
     'term': 'chromatin'},
    {'evidence': 'IDA',
     'gocategory': 'CC',
     'id': 'GO:0000786',
     'pubmed': [14718166, 19633671, 21636898, 25615412],
     'qualifier': 'part_of',
     'term': 'nucleosome'},
    {'evidence': 'IEA',
     'gocategory': 'CC',
     'id': 'GO:0000786',
     'qualifier': 'part_of',
     'term': 'nucleosome'},
    {'evidence': 'IEA',
     'gocategory': 'CC',
     'id': 'GO:0000939',
     'qualifier': 'part_of',
     'term': 'inner kinetochore'},
    {'evidence': 'IEA',
     'gocategory': 'CC',
     'id': 'GO:0001740',
     'qualifier': 'located_in',
     'term': 'Barr body'},
    {'evidence': 'TAS',
     'gocategory': 'CC',
     'id': 'GO:0005576',
     'qualifier': 'located_in',
     'term': 'extracellular region'},
    {'evidence': 'HDA',
     'gocategory': 'CC',
     'id': 'GO:0005634',
     'pubmed': 21630459,
     'qualifier': 'located_in',
     'term': 'nucleus'},
    {'evidence': 'IBA',
     'gocategory': 'CC',
     'id': 'GO:0005634',
     'qualifier': 'is_active_in',
     'term': 'nucleus'},
    {'evidence': 'IDA',
     'gocategory': 'CC',
     'id': 'GO:0005634',
     'pubmed': 21636898,
     'qualifier': 'located_in',
     'term': 'nucleus'},
    {'evidence': 'IEA',
     'gocategory': 'CC',
     'id': 'GO:0005634',
     'qualifier': 'located_in',
     'term': 'nucleus'},
    {'evidence': 'IMP',
     'gocategory': 'CC',
     'id': 'GO:0005634',
     'pubmed': 34876591,
     'qualifier': 'located_in',
     'term': 'nucleus'},
    {'evidence': 'IDA',
     'gocategory': 'CC',
     'id': 'GO:0005654',
     'qualifier': 'located_in',
     'term': 'nucleoplasm'},
    {'evidence': 'TAS',
     'gocategory': 'CC',
     'id': 'GO:0005654',
     'qualifier': 'located_in',
     'term': 'nucleoplasm'},
    {'evidence': 'IEA',
     'gocategory': 'CC',
     'id': 'GO:0005694',
     'qualifier': 'is_active_in',
     'term': 'chromosome'},
    {'evidence': 'IEA',
     'gocategory': 'CC',
     'id': 'GO:0005694',
     'qualifier': 'located_in',
     'term': 'chromosome'},
    {'evidence': 'IDA',
     'gocategory': 'CC',
     'id': 'GO:0032991',
     'pubmed': 14718166,
     'qualifier': 'part_of',
     'term': 'protein-containing complex'},
    {'evidence': 'HDA',
     'gocategory': 'CC',
     'id': 'GO:0070062',
     'pubmed': 20458337,
     'qualifier': 'located_in',
     'term': 'extracellular exosome'}],
   'MF': [{'category': 'MF',
     'evidence': 'IDA',
     'id': 'GO:0000978',
     'pubmed': 19633671,
     'qualifier': 'enables',
     'term': 'RNA polymerase II cis-regulatory region sequence-specific DNA binding'},
    {'category': 'MF',
     'evidence': 'IDA',
     'id': 'GO:0000979',
     'pubmed': 19633671,
     'qualifier': 'enables',
     'term': 'RNA polymerase II core promoter sequence-specific DNA binding'},
    {'category': 'MF',
     'evidence': 'IEA',
     'id': 'GO:0003677',
     'qualifier': 'enables',
     'term': 'DNA binding'},
    {'category': 'MF',
     'evidence': 'IPI',
     'id': 'GO:0005515',
     'pubmed': [19494831,
      19834512,
      20110566,
      20211137,
      20448663,
      20504901,
      20651253,
      20953165,
      23075851,
      23142979,
      24183680,
      24209620,
      24590075,
      24981860,
      25416956,
      26167883,
      26439302,
      32296183,
      33857403,
      33961781],
     'qualifier': 'enables',
     'term': 'protein binding'},
    {'category': 'MF',
     'evidence': 'IDA',
     'id': 'GO:0030527',
     'pubmed': 14718166,
     'qualifier': 'enables',
     'term': 'structural constituent of chromatin'},
    {'category': 'MF',
     'evidence': 'IEA',
     'id': 'GO:0030527',
     'qualifier': 'enables',
     'term': 'structural constituent of chromatin'},
    {'category': 'MF',
     'evidence': 'IDA',
     'id': 'GO:0031492',
     'pubmed': 19633671,
     'qualifier': 'enables',
     'term': 'nucleosomal DNA binding'},
    {'category': 'MF',
     'evidence': 'IEA',
     'id': 'GO:0046982',
     'qualifier': 'enables',
     'term': 'protein heterodimerization activity'}]}},
 {'query': 'JAK3',
  '_id': '3718',
  '_score': 17.859858,
  'go': {'BP': [{'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0002250',
     'qualifier': 'involved_in',
     'term': 'adaptive immune response'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0002376',
     'qualifier': 'involved_in',
     'term': 'immune system process'},
    {'evidence': 'ISS',
     'gocategory': 'BP',
     'id': 'GO:0002731',
     'qualifier': 'involved_in',
     'term': 'negative regulation of dendritic cell cytokine production'},
    {'evidence': 'ISS',
     'gocategory': 'BP',
     'id': 'GO:0007167',
     'qualifier': 'involved_in',
     'term': 'enzyme-linked receptor protein signaling pathway'},
    {'evidence': 'IBA',
     'gocategory': 'BP',
     'id': 'GO:0007259',
     'qualifier': 'involved_in',
     'term': 'cell surface receptor signaling pathway via JAK-STAT'},
    {'evidence': 'NAS',
     'gocategory': 'BP',
     'id': 'GO:0007259',
     'pubmed': 12574355,
     'qualifier': 'involved_in',
     'term': 'cell surface receptor signaling pathway via JAK-STAT'},
    {'evidence': 'TAS',
     'gocategory': 'BP',
     'id': 'GO:0007260',
     'pubmed': 19290934,
     'qualifier': 'involved_in',
     'term': 'tyrosine phosphorylation of STAT protein'},
    {'evidence': 'ISS',
     'gocategory': 'BP',
     'id': 'GO:0010561',
     'qualifier': 'involved_in',
     'term': 'negative regulation of glycoprotein biosynthetic process'},
    {'evidence': 'IBA',
     'gocategory': 'BP',
     'id': 'GO:0019221',
     'qualifier': 'involved_in',
     'term': 'cytokine-mediated signaling pathway'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0019221',
     'qualifier': 'involved_in',
     'term': 'cytokine-mediated signaling pathway'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0022407',
     'qualifier': 'involved_in',
     'term': 'regulation of cell-cell adhesion'},
    {'evidence': 'IBA',
     'gocategory': 'BP',
     'id': 'GO:0030154',
     'qualifier': 'involved_in',
     'term': 'cell differentiation'},
    {'evidence': 'ISS',
     'gocategory': 'BP',
     'id': 'GO:0030183',
     'qualifier': 'involved_in',
     'term': 'B cell differentiation'},
    {'evidence': 'ISS',
     'gocategory': 'BP',
     'id': 'GO:0032693',
     'qualifier': 'involved_in',
     'term': 'negative regulation of interleukin-10 production'},
    {'evidence': 'ISS',
     'gocategory': 'BP',
     'id': 'GO:0032695',
     'qualifier': 'involved_in',
     'term': 'negative regulation of interleukin-12 production'},
    {'evidence': 'IBA',
     'gocategory': 'BP',
     'id': 'GO:0035556',
     'qualifier': 'involved_in',
     'term': 'intracellular signal transduction'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0035556',
     'qualifier': 'involved_in',
     'term': 'intracellular signal transduction'},
    {'evidence': 'ISS',
     'gocategory': 'BP',
     'id': 'GO:0035556',
     'qualifier': 'involved_in',
     'term': 'intracellular signal transduction'},
    {'evidence': 'IDA',
     'gocategory': 'BP',
     'id': 'GO:0035723',
     'pubmed': 7568001,
     'qualifier': 'involved_in',
     'term': 'interleukin-15-mediated signaling pathway'},
    {'evidence': 'IDA',
     'gocategory': 'BP',
     'id': 'GO:0035771',
     'pubmed': 7538655,
     'qualifier': 'involved_in',
     'term': 'interleukin-4-mediated signaling pathway'},
    {'evidence': 'NAS',
     'gocategory': 'BP',
     'id': 'GO:0035771',
     'pubmed': 12574355,
     'qualifier': 'involved_in',
     'term': 'interleukin-4-mediated signaling pathway'},
    {'evidence': 'IDA',
     'gocategory': 'BP',
     'id': 'GO:0038110',
     'pubmed': 7973659,
     'qualifier': 'involved_in',
     'term': 'interleukin-2-mediated signaling pathway'},
    {'evidence': 'TAS',
     'gocategory': 'BP',
     'id': 'GO:0038110',
     'qualifier': 'involved_in',
     'term': 'interleukin-2-mediated signaling pathway'},
    {'evidence': 'IDA',
     'gocategory': 'BP',
     'id': 'GO:0038111',
     'pubmed': 9182906,
     'qualifier': 'involved_in',
     'term': 'interleukin-7-mediated signaling pathway'},
    {'evidence': 'IDA',
     'gocategory': 'BP',
     'id': 'GO:0038113',
     'pubmed': 18829468,
     'qualifier': 'involved_in',
     'term': 'interleukin-9-mediated signaling pathway'},
    {'evidence': 'IBA',
     'gocategory': 'BP',
     'id': 'GO:0042981',
     'qualifier': 'involved_in',
     'term': 'regulation of apoptotic process'},
    {'evidence': 'ISS',
     'gocategory': 'BP',
     'id': 'GO:0043029',
     'qualifier': 'involved_in',
     'term': 'T cell homeostasis'},
    {'evidence': 'TAS',
     'gocategory': 'BP',
     'id': 'GO:0043029',
     'pubmed': 19290934,
     'qualifier': 'involved_in',
     'term': 'T cell homeostasis'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0045087',
     'qualifier': 'involved_in',
     'term': 'innate immune response'},
    {'evidence': 'ISS',
     'gocategory': 'BP',
     'id': 'GO:0045626',
     'qualifier': 'involved_in',
     'term': 'negative regulation of T-helper 1 cell differentiation'},
    {'evidence': 'TAS',
     'gocategory': 'BP',
     'id': 'GO:0046425',
     'pubmed': 19290934,
     'qualifier': 'involved_in',
     'term': 'regulation of receptor signaling pathway via JAK-STAT'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0050865',
     'qualifier': 'involved_in',
     'term': 'regulation of cell activation'},
    {'evidence': 'ISS',
     'gocategory': 'BP',
     'id': 'GO:0050868',
     'qualifier': 'involved_in',
     'term': 'negative regulation of T cell activation'},
    {'evidence': 'IBA',
     'gocategory': 'BP',
     'id': 'GO:0060397',
     'qualifier': 'involved_in',
     'term': 'growth hormone receptor signaling pathway via JAK-STAT'},
    {'evidence': 'TAS',
     'gocategory': 'BP',
     'id': 'GO:0060397',
     'pubmed': 19290934,
     'qualifier': 'involved_in',
     'term': 'growth hormone receptor signaling pathway via JAK-STAT'},
    {'evidence': 'ISS',
     'gocategory': 'BP',
     'id': 'GO:0070232',
     'qualifier': 'involved_in',
     'term': 'regulation of T cell apoptotic process'},
    {'evidence': 'ISS',
     'gocategory': 'BP',
     'id': 'GO:0070244',
     'qualifier': 'involved_in',
     'term': 'negative regulation of thymocyte apoptotic process'},
    {'evidence': 'TAS',
     'gocategory': 'BP',
     'id': 'GO:0070669',
     'pubmed': 9973401,
     'qualifier': 'involved_in',
     'term': 'response to interleukin-2'},
    {'evidence': 'IDA',
     'gocategory': 'BP',
     'id': 'GO:0070670',
     'pubmed': [7538655, 7594533],
     'qualifier': 'involved_in',
     'term': 'response to interleukin-4'},
    {'evidence': 'TAS',
     'gocategory': 'BP',
     'id': 'GO:0070672',
     'pubmed': 7594533,
     'qualifier': 'involved_in',
     'term': 'response to interleukin-15'},
    {'evidence': 'TAS',
     'gocategory': 'BP',
     'id': 'GO:0071104',
     'pubmed': 7594533,
     'qualifier': 'involved_in',
     'term': 'response to interleukin-9'},
    {'evidence': 'IDA',
     'gocategory': 'BP',
     'id': 'GO:2000329',
     'pubmed': 20696842,
     'qualifier': 'involved_in',
     'term': 'negative regulation of T-helper 17 cell lineage commitment'}],
   'CC': [{'evidence': 'IEA',
     'gocategory': 'CC',
     'id': 'GO:0005737',
     'qualifier': 'located_in',
     'term': 'cytoplasm'},
    {'evidence': 'TAS',
     'gocategory': 'CC',
     'id': 'GO:0005768',
     'qualifier': 'located_in',
     'term': 'endosome'},
    {'evidence': 'IBA',
     'gocategory': 'CC',
     'id': 'GO:0005829',
     'qualifier': 'is_active_in',
     'term': 'cytosol'},
    {'evidence': 'TAS',
     'gocategory': 'CC',
     'id': 'GO:0005829',
     'qualifier': 'located_in',
     'term': 'cytosol'},
    {'evidence': 'IEA',
     'gocategory': 'CC',
     'id': 'GO:0005856',
     'qualifier': 'located_in',
     'term': 'cytoskeleton'},
    {'evidence': 'TAS',
     'gocategory': 'CC',
     'id': 'GO:0005886',
     'qualifier': 'located_in',
     'term': 'plasma membrane'},
    {'evidence': 'IC',
     'gocategory': 'CC',
     'id': 'GO:0009898',
     'pubmed': 7973659,
     'qualifier': 'is_active_in',
     'term': 'cytoplasmic side of plasma membrane'},
    {'evidence': 'IEA',
     'gocategory': 'CC',
     'id': 'GO:0012505',
     'qualifier': 'located_in',
     'term': 'endomembrane system'},
    {'evidence': 'IEA',
     'gocategory': 'CC',
     'id': 'GO:0016020',
     'qualifier': 'located_in',
     'term': 'membrane'},
    {'evidence': 'IC',
     'gocategory': 'CC',
     'id': 'GO:0019897',
     'pubmed': 7973658,
     'qualifier': 'is_active_in',
     'term': 'extrinsic component of plasma membrane'},
    {'evidence': 'IC',
     'gocategory': 'CC',
     'id': 'GO:0031234',
     'pubmed': [7973659, 18829468],
     'qualifier': 'is_active_in',
     'term': 'extrinsic component of cytoplasmic side of plasma membrane'},
    {'evidence': 'IDA',
     'gocategory': 'CC',
     'id': 'GO:0031234',
     'pubmed': 7568001,
     'qualifier': 'is_active_in',
     'term': 'extrinsic component of cytoplasmic side of plasma membrane'}],
   'MF': [{'category': 'MF',
     'evidence': 'IEA',
     'id': 'GO:0000166',
     'qualifier': 'enables',
     'term': 'nucleotide binding'},
    {'category': 'MF',
     'evidence': 'IEA',
     'id': 'GO:0004672',
     'qualifier': 'enables',
     'term': 'protein kinase activity'},
    {'category': 'MF',
     'evidence': 'IDA',
     'id': 'GO:0004713',
     'pubmed': [7973658, 7973659, 18829468],
     'qualifier': 'enables',
     'term': 'protein tyrosine kinase activity'},
    {'category': 'MF',
     'evidence': 'IEA',
     'id': 'GO:0004713',
     'qualifier': 'enables',
     'term': 'protein tyrosine kinase activity'},
    {'category': 'MF',
     'evidence': 'IMP',
     'id': 'GO:0004713',
     'pubmed': 18250158,
     'qualifier': 'enables',
     'term': 'protein tyrosine kinase activity'},
    {'category': 'MF',
     'evidence': 'ISS',
     'id': 'GO:0004713',
     'qualifier': 'enables',
     'term': 'protein tyrosine kinase activity'},
    {'category': 'MF',
     'evidence': 'TAS',
     'id': 'GO:0004713',
     'pubmed': 8022790,
     'qualifier': 'enables',
     'term': 'protein tyrosine kinase activity'},
    {'category': 'MF',
     'evidence': 'IBA',
     'id': 'GO:0004715',
     'qualifier': 'enables',
     'term': 'non-membrane spanning protein tyrosine kinase activity'},
    {'category': 'MF',
     'evidence': 'IEA',
     'id': 'GO:0004715',
     'qualifier': 'enables',
     'term': 'non-membrane spanning protein tyrosine kinase activity'},
    {'category': 'MF',
     'evidence': 'IBA',
     'id': 'GO:0005131',
     'qualifier': 'enables',
     'term': 'growth hormone receptor binding'},
    {'category': 'MF',
     'evidence': 'IPI',
     'id': 'GO:0005515',
     'pubmed': [9045636, 25852190, 32707033],
     'qualifier': 'enables',
     'term': 'protein binding'},
    {'category': 'MF',
     'evidence': 'IEA',
     'id': 'GO:0005524',
     'qualifier': 'enables',
     'term': 'ATP binding'},
    {'category': 'MF',
     'evidence': 'IEA',
     'id': 'GO:0016301',
     'qualifier': 'enables',
     'term': 'kinase activity'},
    {'category': 'MF',
     'evidence': 'IEA',
     'id': 'GO:0016740',
     'qualifier': 'enables',
     'term': 'transferase activity'},
    {'category': 'MF',
     'evidence': 'IPI',
     'id': 'GO:0019903',
     'pubmed': 11909529,
     'qualifier': 'enables',
     'term': 'protein phosphatase binding'}]}},
 {'query': 'ASXL1',
  '_id': '171023',
  '_score': 17.73174,
  'go': {'BP': [{'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0000902',
     'qualifier': 'acts_upstream_of_or_within',
     'term': 'cell morphogenesis'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0003007',
     'qualifier': 'acts_upstream_of_or_within',
     'term': 'heart morphogenesis'},
    {'evidence': 'IEA',
     'gocategory': 'BP',
     'id': 'GO:0006325',
     'qualifier': 'involved_in',

In [127]:
gene_to_go = {}
for res in results:
    gene = res.get('query')
    go_bp = res.get('go', {}).get('BP', [])
    if isinstance(go_bp, dict):  # Cas d'un seul terme
        go_bp = [go_bp]
    go_terms = [go['id'] for go in go_bp if 'id' in go]
    if gene and go_terms:
        gene_to_go[gene] = go_terms
        

gene_to_go

{'H3-3A': ['GO:0001556',
  'GO:0001649',
  'GO:0006334',
  'GO:0006334',
  'GO:0006997',
  'GO:0007283',
  'GO:0007286',
  'GO:0007338',
  'GO:0007566',
  'GO:0008283',
  'GO:0008584',
  'GO:0030307',
  'GO:0031508',
  'GO:0031509',
  'GO:0032200',
  'GO:0035264',
  'GO:0042692',
  'GO:0048477',
  'GO:0090230',
  'GO:1902340'],
 'JAK3': ['GO:0002250',
  'GO:0002376',
  'GO:0002731',
  'GO:0007167',
  'GO:0007259',
  'GO:0007259',
  'GO:0007260',
  'GO:0010561',
  'GO:0019221',
  'GO:0019221',
  'GO:0022407',
  'GO:0030154',
  'GO:0030183',
  'GO:0032693',
  'GO:0032695',
  'GO:0035556',
  'GO:0035556',
  'GO:0035556',
  'GO:0035723',
  'GO:0035771',
  'GO:0035771',
  'GO:0038110',
  'GO:0038110',
  'GO:0038111',
  'GO:0038113',
  'GO:0042981',
  'GO:0043029',
  'GO:0043029',
  'GO:0045087',
  'GO:0045626',
  'GO:0046425',
  'GO:0050865',
  'GO:0050868',
  'GO:0060397',
  'GO:0060397',
  'GO:0070232',
  'GO:0070244',
  'GO:0070669',
  'GO:0070670',
  'GO:0070672',
  'GO:0071104',
  'GO:2000329'],
 'ASXL1': ['GO:0000902',
  'GO:0003007',
  'GO:0006325',
  'GO:0006355',
  'GO:0009887',
  'GO:0009887',
  'GO:0030097',
  'GO:0032526',
  'GO:0032526',
  'GO:0035359',
  'GO:0035359',
  'GO:0035564',
  'GO:0045599',
  'GO:0045599',
  'GO:0045944',
  'GO:0045944',
  'GO:0045944',
  'GO:0048386',
  'GO:0048386',
  'GO:0048534',
  'GO:0048538',
  'GO:0048539',
  'GO:0048872',
  'GO:0060348',
  'GO:0060430',
  'GO:0072015'],
 'IDH2': ['GO:0005975',
  'GO:0006097',
  'GO:0006099',
  'GO:0006102',
  'GO:0006102',
  'GO:0006103',
  'GO:0006739',
  'GO:0006741',
  'GO:0060253',
  'GO:1903976',
  'GO:1904465'],
 'JARID2': ['GO:0000122',
  'GO:0001889',
  'GO:0006325',
  'GO:0006338',
  'GO:0007417',
  'GO:0008283',
  'GO:0010468',
  'GO:0030154',
  'GO:0042127',
  'GO:0045892',
  'GO:0048536',
  'GO:0048538',
  'GO:0048863',
  'GO:0048863',
  'GO:0060038',
  'GO:0060044',
  'GO:0060816',
  'GO:0140718',
  'GO:1902682',
  'GO:1990830'],
 'ROBO2': ['GO:0001656',
  'GO:0001657',
  'GO:0003129',
  'GO:0003148',
  'GO:0003180',
  'GO:0003184',
  'GO:0003272',
  'GO:0006935',
  'GO:0007156',
  'GO:0007399',
  'GO:0007411',
  'GO:0007417',
  'GO:0007420',
  'GO:0016199',
  'GO:0021891',
  'GO:0030154',
  'GO:0031290',
  'GO:0032870',
  'GO:0035904',
  'GO:0045747',
  'GO:0050772',
  'GO:0050925',
  'GO:0051964',
  'GO:0060412',
  'GO:0061364',
  'GO:0098609'],
 'IDH1': ['GO:0006097',
  'GO:0006099',
  'GO:0006102',
  'GO:0006102',
  'GO:0006102',
  'GO:0006103',
  'GO:0006103',
  'GO:0006739',
  'GO:0006740',
  'GO:0006749',
  'GO:0006979',
  'GO:0008585',
  'GO:0048545',
  'GO:0060696',
  'GO:0071071'],
 'SUZ12': ['GO:0000122',
  'GO:0006325',
  'GO:0006325',
  'GO:0008283',
  'GO:0008284',
  'GO:0045596',
  'GO:0048709',
  'GO:0060816',
  'GO:0140718'],
 'SETBP1': ['GO:0006338', 'GO:0006355'],
 'GATA2': ['GO:0000122',
  'GO:0000122',
  'GO:0001525',
  'GO:0001655',
  'GO:0001709',
  'GO:0001764',
  'GO:0001892',
  'GO:0002067',
  'GO:0002071',
  'GO:0002244',
  'GO:0006355',
  'GO:0006357',
  'GO:0006366',
  'GO:0006909',
  'GO:0007204',
  'GO:0007405',
  'GO:0007406',
  'GO:0009653',
  'GO:0010628',
  'GO:0010629',
  'GO:0010725',
  'GO:0021514',
  'GO:0021533',
  'GO:0021902',
  'GO:0021953',
  'GO:0021954',
  'GO:0021983',
  'GO:0030099',
  'GO:0030154',
  'GO:0030182',
  'GO:0033993',
  'GO:0035019',
  'GO:0035854',
  'GO:0042472',
  'GO:0042551',
  'GO:0043306',
  'GO:0043536',
  'GO:0045165',
  'GO:0045444',
  'GO:0045638',
  'GO:0045648',
  'GO:0045650',
  'GO:0045654',
  'GO:0045666',
  'GO:0045746',
  'GO:0045766',
  'GO:0045766',
  'GO:0045766',
  'GO:0045766',
  'GO:0045893',
  'GO:0045944',
  'GO:0045944',
  'GO:0045944',
  'GO:0045944',
  'GO:0045944',
  'GO:0045944',
  'GO:0048663',
  'GO:0048731',
  'GO:0048873',
  'GO:0050766',
  'GO:0050766',
  'GO:0050793',
  'GO:0050873',
  'GO:0060100',
  'GO:0060129',
  'GO:0060216',
  'GO:0060872',
  'GO:0061042',
  'GO:0061101',
  'GO:0061351',
  'GO:0061484',
  'GO:0090050',
  'GO:0090102',
  'GO:0097154',
  'GO:1901533',
  'GO:1902895',
  'GO:1902895',
  'GO:1902895',
  'GO:1903444',
  'GO:1903589',
  'GO:2000178',
  'GO:2000352',
  'GO:2000977'],
 'TERT': ['GO:0000722',
  'GO:0000723',
  'GO:0000723',
  'GO:0001172',
  'GO:0006278',
  'GO:0006606',
  'GO:0007004',
  'GO:0007004',
  'GO:0007004',
  'GO:0007004',
  'GO:0007005',
  'GO:0007507',
  'GO:0022616',
  'GO:0030177',
  'GO:0030177',
  'GO:0030422',
  'GO:0031647',
  'GO:0031647',
  'GO:0032092',
  'GO:0042635',
  'GO:0042635',
  'GO:0043066',
  'GO:0043524',
  'GO:0045766',
  'GO:0046326',
  'GO:0046686',
  'GO:0070200',
  'GO:0071456',
  'GO:0071456',
  'GO:0071897',
  'GO:0090399',
  'GO:0140745',
  'GO:1900087',
  'GO:1902895',
  'GO:1903620',
  'GO:1904707',
  'GO:1904751',
  'GO:1904754',
  'GO:2000352',
  'GO:2000648',
  'GO:2000648',
  'GO:2000773',
  'GO:2000773',
  'GO:2001240'],
 'NF2': ['GO:0000165',
  'GO:0001707',
  'GO:0001953',
  'GO:0007398',
  'GO:0007420',
  'GO:0008285',
  'GO:0008285',
  'GO:0008285',
  'GO:0008285',
  'GO:0008360',
  'GO:0010626',
  'GO:0014010',
  'GO:0014010',
  'GO:0014013',
  'GO:0014013',
  'GO:0021766',
  'GO:0022408',
  'GO:0030036',
  'GO:0030336',
  'GO:0031647',
  'GO:0033687',
  'GO:0033689',
  'GO:0035330',
  'GO:0035330',
  'GO:0042127',
  'GO:0042475',
  'GO:0042981',
  'GO:0043409',
  'GO:0045216',
  'GO:0045597',
  'GO:0046426',
  'GO:0050767',
  'GO:0051128',
  'GO:0051496',
  'GO:0051726',
  'GO:0070306',
  'GO:0072091',
  'GO:1900180',
  'GO:1902115',
  'GO:1902966',
  'GO:2000177',
  'GO:2000643'],
 'STAG2': ['GO:0007059',
  'GO:0007062',
  'GO:0007062',
  'GO:0034087',
  'GO:0051301',
  'GO:0051321',
  'GO:0090307'],
 'SH2B3': ['GO:0001780',
  'GO:0001780',
  'GO:0007165',
  'GO:0007169',
  'GO:0008285',
  'GO:0008285',
  'GO:0030097',
  'GO:0035162',
  'GO:0035162',
  'GO:0035556',
  'GO:0035556',
  'GO:0035702',
  'GO:0035702',
  'GO:0035855',
  'GO:0035855',
  'GO:0036016',
  'GO:0036016',
  'GO:0038163',
  'GO:0038163',
  'GO:0038163',
  'GO:0038163',
  'GO:0043409',
  'GO:0043409',
  'GO:0046426',
  'GO:0048821',
  'GO:0051898',
  'GO:0051898',
  'GO:0060218',
  'GO:0060761',
  'GO:0070100',
  'GO:0070100',
  'GO:0090331',
  'GO:0090331',
  'GO:1900235',
  'GO:1900235',
  'GO:1904893',
  'GO:1904893',
  'GO:1990869',
  'GO:1990869'],
 'BCL10': ['GO:0001783',
  'GO:0001819',
  'GO:0001843',
  'GO:0001843',
  'GO:0002224',
  'GO:0002250',
  'GO:0002250',
  'GO:0002250',
  'GO:0002250',
  'GO:0002376',
  'GO:0002906',
  'GO:0006915',
  'GO:0006968',
  'GO:0009620',
  'GO:0012501',
  'GO:0016064',
  'GO:0031398',
  'GO:0031663',
  'GO:0032094',
  'GO:0032496',
  'GO:0032755',
  'GO:0032757',
  'GO:0032761',
  'GO:0032765',
  'GO:0038061',
  'GO:0042327',
  'GO:0042981',
  'GO:0043065',
  'GO:0043065',
  'GO:0043123',
  'GO:0043123',
  'GO:0045087',
  'GO:0045087',
  'GO:0045893',
  'GO:0050852',
  'GO:0050856',
  'GO:0050862',
  'GO:0050870',
  'GO:0051092',
  'GO:0051260',
  'GO:0061760',
  'GO:0061760',
  'GO:0070231',
  'GO:0071222',
  'GO:0071260',
  'GO:0097190',
  'GO:2001238',
  'GO:2001238',
  'GO:2001238'],
 'NOTCH2': ['GO:0000122',
  'GO:0001701',
  'GO:0001709',
  'GO:0001889',
  'GO:0001890',
  'GO:0001947',
  'GO:0002011',
  'GO:0002315',
  'GO:0002315',
  'GO:0002437',
  'GO:0003162',
  'GO:0003184',
  'GO:0006355',
  'GO:0006357',
  'GO:0006915',
  'GO:0006915',
  'GO:0006959',
  'GO:0007219',
  'GO:0007219',
  'GO:0007219',
  'GO:0007219',
  'GO:0007219',
  'GO:0007368',
  'GO:0007399',
  'GO:0007411',
  'GO:0008283',
  'GO:0008284',
  'GO:0009887',
  'GO:0010629',
  'GO:0010838',
  'GO:0030097',
  'GO:0030154',
  'GO:0030326',
  'GO:0030509',
  'GO:0030513',
  'GO:0035264',
  'GO:0035556',
  'GO:0035622',
  'GO:0042060',
  'GO:0042742',
  'GO:0043011',
  'GO:0043065',
  'GO:0043066',
  'GO:0045672',
  'GO:0045944',
  'GO:0046579',
  'GO:0046849',
  'GO:0050793',
  'GO:0051152',
  'GO:0060413',
  'GO:0060674',
  'GO:0061073',
  'GO:0070374',
  'GO:0070986',
  'GO:0071228',
  'GO:0071228',
  'GO:0072014',
  'GO:0072015',
  'GO:0072104',
  'GO:0072574',
  'GO:0072576',
  'GO:1902895',
  'GO:1990705',
  'GO:2001204'],
 'LUC7L2': ['GO:0006376', 'GO:0006376'],
 'NRAS': ['GO:0000165',
  'GO:0001938',
  'GO:0007165',
  'GO:0007265',
  'GO:0007265'],
 'CBL': ['GO:0000209',
  'GO:0006511',
  'GO:0006511',
  'GO:0006513',
  'GO:0006974',
  'GO:0007165',
  'GO:0007166',
  'GO:0008584',
  'GO:0010332',
  'GO:0014823',
  'GO:0016567',
  'GO:0016567',
  'GO:0016567',
  'GO:0016567',
  'GO:0019221',
  'GO:0023051',
  'GO:0032487',
  'GO:0033574',
  'GO:0036120',
  'GO:0042059',
  'GO:0042059',
  'GO:0042059',
  'GO:0042059',
  'GO:0042594',
  'GO:0043066',
  'GO:0043066',
  'GO:0043303',
  'GO:0045471',
  'GO:0045742',
  'GO:0046718',
  'GO:0048260',
  'GO:0051865',
  'GO:0051897',
  'GO:0070086',
  'GO:0071456',
  'GO:1990090',
  'GO:2000583',
  'GO:2000583'],
 'ZRSR2': ['GO:0000245',
  'GO:0000398',
  'GO:0000398',
  'GO:0000398',
  'GO:0006397',
  'GO:0008380',
  'GO:0008380'],
 'CDKN1B': ['GO:0000079',
  'GO:0000082',
  'GO:0000082',
  'GO:0000082',
  'GO:0001890',
  'GO:0006813',
  'GO:0006915',
  'GO:0007096',
  'GO:0007219',
  'GO:0007346',
  'GO:0007507',
  'GO:0007507',
  'GO:0007605',
  'GO:0008284',
  'GO:0008285',
  'GO:0008285',
  'GO:0030308',
  'GO:0030330',
  'GO:0030334',
  'GO:0031116',
  'GO:0033673',
  'GO:0045732',
  'GO:0045736',
  'GO:0045740',
  'GO:0045892',
  'GO:0045930',
  'GO:0048102',
  'GO:0048839',
  'GO:0050680',
  'GO:0050680',
  'GO:0051168',
  'GO:0051726',
  'GO:0051726',
  'GO:0051726',
  'GO:0060767',
  'GO:0060770',
  'GO:0071236',
  'GO:0071285',
  'GO:0090398',
  'GO:1902746',
  'GO:1902806',
  'GO:1904019',
  'GO:1904030',
  'GO:1904036',
  'GO:1904706',
  'GO:1905179',
  'GO:1905179',
  'GO:2000045'],
 'ROBO1': ['GO:0002042',
  'GO:0003129',
  'GO:0003148',
  'GO:0003180',
  'GO:0003184',
  'GO:0003272',
  'GO:0006935',
  'GO:0007155',
  'GO:0007156',
  'GO:0007399',
  'GO:0007399',
  'GO:0007411',
  'GO:0010628',
  'GO:0010629',
  'GO:0016199',
  'GO:0016199',
  'GO:0021836',
  'GO:0030154',
  'GO:0030336',
  'GO:0030949',
  'GO:0033600',
  'GO:0035025',
  'GO:0035385',
  'GO:0035385',
  'GO:0035904',
  'GO:0043410',
  'GO:0045747',
  'GO:0050772',
  'GO:0050925',
  'GO:0060412',
  'GO:0070100',
  'GO:1900748'],
 'NOTCH1': ['GO:0000122',
  'GO:0000122',
  'GO:0000122',
  'GO:0001525',
  'GO:0001554',
  'GO:0001701',
  'GO:0001837',
  'GO:0001837',
  'GO:0001837',
  'GO:0001889',
  'GO:0001947',
  'GO:0001947',
  'GO:0002040',
  'GO:0002052',
  'GO:0002085',
  'GO:0002437',
  'GO:0003151',
  'GO:0003157',
  'GO:0003157',
  'GO:0003160',
  'GO:0003160',
  'GO:0003162',
  'GO:0003169',
  'GO:0003169',
  'GO:0003180',
  'GO:0003180',
  'GO:0003180',
  'GO:0003180',
  'GO:0003181',
  'GO:0003181',
  'GO:0003182',
  'GO:0003184',
  'GO:0003184',
  'GO:0003184',
  'GO:0003192',
  'GO:0003197',
  'GO:0003198',
  'GO:0003198',
  'GO:0003203',
  'GO:0003203',
  'GO:0003207',
  'GO:0003207',
  'GO:0003208',
  'GO:0003208',
  'GO:0003209',
  'GO:0003209',
  'GO:0003213',
  'GO:0003213',
  'GO:0003214',
  'GO:0003214',
  'GO:0003219',
  'GO:0003222',
  'GO:0003222',
  'GO:0003241',
  'GO:0003241',
  'GO:0003252',
  'GO:0003252',
  'GO:0003264',
  'GO:0003270',
  'GO:0003273',
  'GO:0003273',
  'GO:0003332',
  'GO:0003332',
  'GO:0003344',
  'GO:0003344',
  'GO:0006355',
  'GO:0006355',
  'GO:0006357',
  'GO:0006357',
  'GO:0006366',
  'GO:0006606',
  'GO:0006915',
  'GO:0006955',
  'GO:0006959',
  'GO:0007219',
  'GO:0007219',
  'GO:0007219',
  'GO:0007219',
  'GO:0007219',
  'GO:0007219',
  'GO:0007219',
  'GO:0007221',
  'GO:0007221',
  'GO:0007221',
  'GO:0007283',
  'GO:0007368',
  'GO:0007368',
  'GO:0007386',
  'GO:0007409',
  'GO:0007411',
  'GO:0007440',
  'GO:0007492',
  'GO:0007507',
  'GO:0008283',
  'GO:0008284',
  'GO:0008284',
  'GO:0008285',
  'GO:0008544',
  'GO:0008593',
  'GO:0009912',
  'GO:0009957',
  'GO:0010001',
  'GO:0010467',
  'GO:0010468',
  'GO:0010614',
  'GO:0010614',
  'GO:0010628',
  'GO:0010628',
  'GO:0010629',
  'GO:0010667',
  'GO:0010718',
  'GO:0010812',
  'GO:0010832',
  'GO:0014031',
  'GO:0014031',
  'GO:0014807',
  'GO:0017156',
  'GO:0021515',
  'GO:0021915',
  'GO:0021953',
  'GO:0030154',
  'GO:0030154',
  'GO:0030163',
  'GO:0030182',
  'GO:0030216',
  'GO:0030279',
  'GO:0030279',
  'GO:0030324',
  'GO:0030326',
  'GO:0030334',
  'GO:0030335',
  'GO:0030335',
  'GO:0030513',
  'GO:0030513',
  'GO:0030514',
  'GO:0030514',
  'GO:0030900',
  'GO:0031069',
  'GO:0031100',
  'GO:0032495',
  'GO:0032496',
  'GO:0032966',
  'GO:0035116',
  'GO:0035148',
  'GO:0035914',
  'GO:0035924',
  'GO:0042127',
  'GO:0042246',
  'GO:0042670',
  'GO:0043065',
  'GO:0043069',
  'GO:0043086',
  'GO:0045070',
  'GO:0045603',
  'GO:0045607',
  'GO:0045608',
  'GO:0045618',
  'GO:0045662',
  'GO:0045665',
  'GO:0045665',
  'GO:0045668',
  'GO:0045668',
  'GO:0045687',
  'GO:0045747',
  'GO:0045892',
  'GO:0045892',
  'GO:0045893',
  'GO:0045893',
  'GO:0045944',
  'GO:0045944',
  'GO:0045944',
  'GO:0045944',
  'GO:0045955',
  'GO:0046427',
  'GO:0046427',
  'GO:0046533',
  'GO:0046579',
  'GO:0048103',
  'GO:0048663',
  'GO:0048708',
  'GO:0048709',
  'GO:0048709',
  'GO:0048711',
  'GO:0048711',
  'GO:0048715',
  'GO:0048715',
  'GO:0048754',
  'GO:0048845',
  'GO:0048873',
  'GO:0048873',
  'GO:0050673',
  'GO:0050678',
  'GO:0050679',
  'GO:0050680',
  'GO:0050767',
  'GO:0050768',
  'GO:0050768',
  'GO:0050793',
  'GO:0051152',
  'GO:0055008',
  'GO:0055008',
  'GO:0060038',
  'GO:0060045',
  'GO:0060045',
  'GO:0060253',
  'GO:0060253',
  'GO:0060271',
  'GO:0060317',
  'GO:0060317',
  'GO:0060354',
  'GO:0060379',
  'GO:0060379',
  'GO:0060411',
  'GO:0060411',
  'GO:0060412',
  'GO:0060412',
  'GO:0060528',
  'GO:0060740',
  'GO:0060768',
  'GO:0060842',
  'GO:0060842',
  'GO:0060843',
  'GO:0060843',
  'GO:0060948',
  'GO:0060948',
  'GO:0060956',
  'GO:0060956',
  'GO:0060979',
  'GO:0060979',
  'GO:0060982',
  'GO:0060982',
  'GO:0061101',
  'GO:0061344',
  'GO:0061384',
  'GO:0061384',
  'GO:0062043',
  'GO:0062043',
  'GO:0070168',
  'GO:0070168',
  'GO:0070374',
  'GO:0070986',
  'GO:0071228',
  'GO:0071372',
  'GO:0071456',
  'GO:0071456',
  'GO:0072017',
  'GO:0072044',
  'GO:0072091',
  'GO:0072144',
  'GO:0072148',
  'GO:0072538',
  'GO:0090051',
  'GO:0090090',
  'GO:0097150',
  'GO:0097400',
  'GO:0099565',
  'GO:0120163',
  'GO:0120163',
  'GO:1901201',
  'GO:1901201',
  'GO:1902263',
  'GO:1902339',
  'GO:1902339',
  'GO:1903849',
  'GO:2000048',
  'GO:2000737',
  'GO:2000811',
  'GO:2000974',
  'GO:2000974',
  'GO:2001027'],
 'CALR': ['GO:0000122',
  'GO:0002502',
  'GO:0002502',
  'GO:0002502',
  'GO:0006355',
  'GO:0006457',
  'GO:0006457',
  'GO:0006457',
  'GO:0006457',
  'GO:0006611',
  'GO:0006874',
  'GO:0007283',
  'GO:0008284',
  'GO:0009410',
  'GO:0010595',
  'GO:0010628',
  'GO:0017148',
  'GO:0017148',
  'GO:0030866',
  'GO:0032355',
  'GO:0033144',
  'GO:0033574',
  'GO:0034504',
  'GO:0034504',
  'GO:0034975',
  'GO:0036503',
  'GO:0040020',
  'GO:0042921',
  'GO:0042981',
  'GO:0045665',
  'GO:0045787',
  'GO:0045787',
  'GO:0045892',
  'GO:0048387',
  'GO:0050766',
  'GO:0050766',
  'GO:0050821',
  'GO:0050821',
  'GO:0050821',
  'GO:0050821',
  'GO:0051208',
  'GO:0051604',
  'GO:0055007',
  'GO:0071257',
  'GO:0071285',
  'GO:0090398',
  'GO:0090398',
  'GO:0098586',
  'GO:1900026',
  'GO:1901164',
  'GO:1901224',
  'GO:1901652',
  'GO:1903416',
  'GO:1904614',
  'GO:2000510'],
 'STAT3': ['GO:0000122',
  'GO:0001659',
  'GO:0001659',
  'GO:0001666',
  'GO:0001754',
  'GO:0002931',
  'GO:0006355',
  'GO:0006355',
  'GO:0006357',
  'GO:0006357',
  'GO:0006357',
  'GO:0006366',
  'GO:0006606',
  'GO:0006952',
  'GO:0006953',
  'GO:0006954',
  'GO:0006954',
  'GO:0007165',
  'GO:0007165',
  'GO:0007179',
  'GO:0007259',
  'GO:0007259',
  'GO:0007259',
  'GO:0007259',
  'GO:0007399',
  'GO:0008283',
  'GO:0008284',
  'GO:0008285',
  'GO:0009410',
  'GO:0010467',
  'GO:0010507',
  'GO:0010575',
  'GO:0010628',
  'GO:0010628',
  'GO:0010628',
  'GO:0010629',
  'GO:0010730',
  'GO:0016310',
  'GO:0019221',
  'GO:0019221',
  'GO:0019953',
  'GO:0019953',
  'GO:0030154',
  'GO:0030335',
  'GO:0030522',
  'GO:0032355',
  'GO:0032355',
  'GO:0032731',
  'GO:0032733',
  'GO:0032755',
  'GO:0032755',
  'GO:0032757',
  'GO:0032760',
  'GO:0032870',
  'GO:0033210',
  'GO:0033210',
  'GO:0033210',
  'GO:0034097',
  'GO:0035019',
  'GO:0035723',
  'GO:0038110',
  'GO:0038113',
  'GO:0038154',
  'GO:0038155',
  'GO:0040014',
  'GO:0042127',
  'GO:0042593',
  'GO:0042593',
  'GO:0042755',
  'GO:0042755',
  'GO:0042789',
  'GO:0043123',
  'GO:0043123',
  'GO:0043124',
  'GO:0043124',
  'GO:0043434',
  'GO:0043434',
  'GO:0043491',
  'GO:0043491',
  'GO:0044320',
  'GO:0044321',
  'GO:0044321',
  'GO:0045471',
  'GO:0045648',
  'GO:0045747',
  'GO:0045747',
  'GO:0045766',
  'GO:0045820',
  'GO:0045893',
  'GO:0045893',
  'GO:0045893',
  'GO:0045944',
  'GO:0045944',
  'GO:0045944',
  'GO:0045944',
  'GO:0045944',
  'GO:0045944',
  'GO:0046902',
  'GO:0048708',
  'GO:0048708',
  'GO:0050728',
  'GO:0050728',
  'GO:0050766',
  'GO:0050804',
  'GO:0051726',
  'GO:0051726',
  'GO:0060019',
  'GO:0060019',
  'GO:0060221',
  'GO:0060259',
  'GO:0060259',
  'GO:0060396',
  'GO:0060397',
  'GO:0060397',
  'GO:0060397',
  'GO:0060397',
  'GO:0070102',
  'GO:0070102',
  'GO:0071345',
  'GO:0072538',
  'GO:0072540',
  'GO:0072540',
  'GO:0090091',
  'GO:0097009',
  'GO:0097009',
  'GO:0097398',
  'GO:0097696',
  'GO:0099527',
  'GO:0106015',
  'GO:0106015',
  'GO:0140105',
  'GO:1900016',
  'GO:1900016',
  'GO:1900017',
  'GO:1900037',
  'GO:1902728',
  'GO:1902895',
  'GO:1902895',
  'GO:1905564',
  'GO:2000635',
  'GO:2000737',
  'GO:2001171',
  'GO:2001223'],
 'SF3B1': ['GO:0000245',
  'GO:0000245',
  'GO:0000375',
  'GO:0000398',
  'GO:0000398',
  'GO:0000398',
  'GO:0000398',
  'GO:0006338',
  'GO:0006397',
  'GO:0008380',
  'GO:0008380',
  'GO:0045943',
  'GO:0045944',
  'GO:0045945',
  'GO:1903241'],
 'MYC': ['GO:0000082',
  'GO:0000122',
  'GO:0000122',
  'GO:0000122',
  'GO:0000165',
  'GO:0001658',
  'GO:0001658',
  'GO:0001783',
  'GO:0001866',
  'GO:0002053',
  'GO:0002053',
  'GO:0002904',
  'GO:0006338',
  'GO:0006355',
  'GO:0006357',
  'GO:0006366',
  'GO:0006879',
  'GO:0006974',
  'GO:0006974',
  'GO:0008283',
  'GO:0008284',
  'GO:0008284',
  'GO:0008284',
  'GO:0008630',
  'GO:0009314',
  'GO:0009410',
  'GO:0010468',
  'GO:0010468',
  'GO:0010564',
  'GO:0010628',
  'GO:0010628',
  'GO:0014902',
  'GO:0016055',
  'GO:0016072',
  'GO:0016485',
  'GO:0032204',
  'GO:0032206',
  'GO:0032206',
  'GO:0032873',
  'GO:0032986',
  'GO:0034644',
  'GO:0035457',
  'GO:0035914',
  'GO:0042474',
  'GO:0042981',
  'GO:0043066',
  'GO:0043279',
  'GO:0043473',
  'GO:0044027',
  'GO:0044346',
  'GO:0045656',
  'GO:0045893',
  'GO:0045893',
  'GO:0045944',
  'GO:0045944',
  'GO:0045944',
  'GO:0045944',
  'GO:0048146',
  'GO:0048146',
  'GO:0048147',
  'GO:0048705',
  'GO:0050679',
  'GO:0050910',
  'GO:0051276',
  'GO:0051782',
  'GO:0060261',
  'GO:0060633',
  'GO:0070371',
  'GO:0070848',
  'GO:0071456',
  'GO:0071466',
  'GO:0090096',
  'GO:0090096',
  'GO:1902255',
  'GO:1902895',
  'GO:1904672',
  'GO:1904672',
  'GO:1904699',
  'GO:1990863',
  'GO:2001235'],
 'KMT2D': ['GO:0001555',
  'GO:0006325',
  'GO:0006355',
  'GO:0008284',
  'GO:0031507',
  'GO:0032259',
  'GO:0033148',
  'GO:0043627',
  'GO:0045944',
  'GO:0045944',
  'GO:0048477',
  'GO:1904837'],
 'NXF1': ['GO:0006405',
  'GO:0006406',
  'GO:0006406',
  'GO:0006406',
  'GO:0015031',
  'GO:0016973',
  'GO:0016973',
  'GO:0051028'],
 'SMC1A': ['GO:0000070',
  'GO:0006281',
  'GO:0006281',
  'GO:0006974',
  'GO:0007062',
  'GO:0007062',
  'GO:0007062',
  'GO:0007064',
  'GO:0009314',
  'GO:0034087',
  'GO:0034089',
  'GO:0035019',
  'GO:0051276',
  'GO:0051301',
  'GO:0051321',
  'GO:0051321',
  'GO:0051321',
  'GO:0072423',

In [128]:
from sklearn.preprocessing import MultiLabelBinarizer

# 4. Créer une matrice binaire gène × GO term
mlb = MultiLabelBinarizer()
go_matrix = mlb.fit_transform(gene_to_go.values())
go_df = pd.DataFrame(go_matrix, index=gene_to_go.keys(), columns=mlb.classes_)

# 5. Filtrer les GO terms peu fréquents (seuil = 5 gènes)
min_gene_count = 5
filtered_go_df = go_df.loc[:, (go_df.sum(axis=0) >= min_gene_count)]

# 6. Résultat final
print(f"Dimensions finales : {filtered_go_df.shape}")
filtered_go_df

Dimensions finales : (124, 100)

,GO:0000082,GO:0000122,GO:0000165,GO:0000398,GO:0001666,GO:0001701,GO:0001889,GO:0002376,GO:0006281,GO:0006302,...,GO:0060038,GO:0060253,GO:0070374,GO:0071222,GO:0071456,GO:0071466,GO:0090307,GO:0090398,GO:1902895,GO:2000045
H3-3A,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
JAK3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
ASXL1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
IDH2,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
JARID2,0,1,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
HIPK2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
SF1,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DICER1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
KIT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CDKN2B,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1

In [129]:
mol_df_pd = mol_df.to_pandas()

df_merged = mol_df_pd.merge(filtered_go_df, left_on='GENE', right_index=True, how='left')

In [130]:
df_merged = pl.from_pandas(df_merged)

In [131]:
df_merged

shape: (10_935, 138)
┌─────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ ID      ┆ CHR  ┆ START      ┆ END        ┆ … ┆ GO:0090307 ┆ GO:0090398 ┆ GO:1902895 ┆ GO:2000045 │
│ ---     ┆ ---  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ str     ┆ f64  ┆ f64        ┆ f64        ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
╞═════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ P100000 ┆ 11.0 ┆ 1.19149248 ┆ 1.19149248 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 5.0  ┆ 1.31822301 ┆ 1.31822301 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 3.0  ┆ 7.769406e7 ┆ 7.769406e7 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ P100000 ┆ 4.0  ┆ 1.06164917 ┆ 1.06164917 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 2.0  ┆ 2.5468147e ┆ 2.5468163e ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│         ┆      ┆ 7          ┆ 7          ┆   ┆            ┆            ┆            ┆            │
│ …       ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ P131472 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ P131505 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ P131816 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ P132717 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ P132724 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
└─────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [132]:
df_merged.filter(pl.col("GENE") == "FLT3")

shape: (56, 138)
┌─────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ ID      ┆ CHR  ┆ START      ┆ END        ┆ … ┆ GO:0090307 ┆ GO:0090398 ┆ GO:1902895 ┆ GO:2000045 │
│ ---     ┆ ---  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ str     ┆ f64  ┆ f64        ┆ f64        ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
╞═════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ P102824 ┆ 13.0 ┆ 2.8592641e ┆ 2.8592641e ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│         ┆      ┆ 7          ┆ 7          ┆   ┆            ┆            ┆            ┆            │
│ P102954 ┆ 13.0 ┆ 2.8608107e ┆ 2.8608107e ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│         ┆      ┆ 7          ┆ 7          ┆   ┆            ┆            ┆            ┆            │
│ P103084 ┆ 13.0 ┆ 2.860242e7 ┆ 2.860242e7 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ P105773 ┆ 13.0 ┆ 2.8592642e ┆ 2.8592642e ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│         ┆      ┆ 7          ┆ 7          ┆   ┆            ┆            ┆            ┆            │
│ P105775 ┆ 13.0 ┆ 2.8592642e ┆ 2.8592642e ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│         ┆      ┆ 7          ┆ 7          ┆   ┆            ┆            ┆            ┆            │
│ …       ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ P118243 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ P120352 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ P116526 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ P116588 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ P120980 ┆ null ┆ null       ┆ null       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
└─────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [133]:
# not_found_gene = ['MLL', 'WHSC1', 'H3F3A', 'PAPD5', 'FAM175A']

# df_merged = df_merged.with_columns(
#     pl.when(pl.col("GENE").is_in(not_found_gene))
#     .then(pl.col("GENE"))
#     .otherwise(None)
#     .alias("not_found_gene")
# )

# PARLER DE CA

In [134]:
# df_merged = df_merged.with_columns(
#     pl.when(pl.col("GENE").is_in(not_found_gene))
#     .then(0)
#     .otherwise(1)
#     .alias("Found_in_my_Gene")
# )

In [135]:
mol_df = df_merged

# NULL VALUES : CHR , START , END

In [136]:
quant_vars = ["CHR" , "START" , "END"]
sub_df = mol_df.select(quant_vars)

# Convert to pandas
sub_pd = sub_df.to_pandas()
 
# Apply Model-Based Imputation (Random Forest)
imputer = IterativeImputer(estimator=RandomForestRegressor(), random_state=42)
imputed_data = imputer.fit_transform(sub_pd)

# 4. To Polars
imputed_pl = pl.DataFrame(imputed_data, schema=sub_df.columns)

# 5. Replace nulls
mol_df = mol_df.with_columns([imputed_pl[col].alias(col) for col in quant_vars])

In [137]:
mol_df

shape: (10_935, 138)
┌─────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ ID      ┆ CHR  ┆ START      ┆ END        ┆ … ┆ GO:0090307 ┆ GO:0090398 ┆ GO:1902895 ┆ GO:2000045 │
│ ---     ┆ ---  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ str     ┆ f64  ┆ f64        ┆ f64        ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
╞═════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ P100000 ┆ 11.0 ┆ 1.19149248 ┆ 1.19149248 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 5.0  ┆ 1.31822301 ┆ 1.31822301 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 3.0  ┆ 7.769406e7 ┆ 7.769406e7 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ P100000 ┆ 4.0  ┆ 1.06164917 ┆ 1.06164917 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 2.0  ┆ 2.5468147e ┆ 2.5468163e ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│         ┆      ┆ 7          ┆ 7          ┆   ┆            ┆            ┆            ┆            │
│ …       ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ P131472 ┆ 3.0  ┆ 7.9008e7   ┆ 7.9009e7   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ P131505 ┆ 3.0  ┆ 7.9008e7   ┆ 7.9009e7   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ P131816 ┆ 3.0  ┆ 7.9008e7   ┆ 7.9009e7   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ P132717 ┆ 3.0  ┆ 7.9008e7   ┆ 7.9009e7   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ P132724 ┆ 3.0  ┆ 7.9008e7   ┆ 7.9009e7   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
└─────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

# PROTEIN_CHANGE

In [138]:

# ON GERE LES PROTEIN CHANGE QUI COMMENCE PAR p.

import re 


protein_change = list(mol_df["PROTEIN_CHANGE"].unique())


protein_change

uppercase_alphabet = [chr(i) for i in range(ord('A'), ord('Z') + 1)]

aa_fullname = {
    'A': 'Alanine',
    'C': 'Cystéine',
    'D': 'Acide aspartique',
    'E': 'Acide glutamique',
    'F': 'Phénylalanine',
    'G': 'Glycine',
    'H': 'Histidine',
    'I': 'Isoleucine',
    'K': 'Lysine',
    'L': 'Leucine',
    'M': 'Méthionine',
    'N': 'Asparagine',
    'P': 'Proline',
    'Q': 'Glutamine',
    'R': 'Arginine',
    'S': 'Sérine',
    'T': 'Thréonine',
    'V': 'Valine',
    'W': 'Tryptophane',
    'Y': 'Tyrosine'
}




def protein_name(protein_changes, ch):
    lst_prot = []
    pattern = rf"p\.{ch}\d+.*"

    for prot in protein_changes:
        if isinstance(prot, str): 
            prot_name = re.findall(pattern, prot)
            if prot_name:
                lst_prot+=prot_name
                
    return lst_prot
        
        
dico_protein_changes = {}
        
for ch in uppercase_alphabet:
    lst  = protein_name(protein_change , ch)
    if(len(lst) >=1):
        ch_name = aa_fullname.get(ch)
        dico_protein_changes[ch_name] = lst

print(dico_protein_changes)


# A , C , D , E , F , G , H , I , K , L , M , N , P , Q , R , S , T , V , W , Y

{'Alanine': ['p.A858fs*29', 'p.A36V', 'p.A435S', 'p.A640fs*14', 'p.A571fs*5', 'p.A138T', 'p.A59E', 'p.A671fs*29', 'p.A809fs*13', 'p.A1810fs*10', 'p.A146V', 'p.A377G', 'p.A1158V', 'p.A51fs*36', 'p.A324fs*276', 'p.A1196delA', 'p.A59H', 'p.A716fs*9', 'p.A871T', 'p.A59G', 'p.A286T', 'p.A68fs*70', 'p.A787V', 'p.A972V', 'p.A658*', 'p.A159P', 'p.A147fs*13', 'p.A338fs*262', 'p.A1341P', 'p.A620V', 'p.A1331T', 'p.A113fs*86', 'p.A1189fs*4', 'p.A1166fs*56', 'p.A1505T', 'p.A159V', 'p.A235fs*1', 'p.A72S', 'p.A1196fs*2', 'p.A142fs*4', 'p.A382fs*6', 'p.A380T', 'p.A1159_I1160delinsV', 'p.A377V', 'p.A187_T188delAT', 'p.A85T', 'p.A368fs*39', 'p.A696V', 'p.A488T', 'p.A385fs*57', 'p.A161D', 'p.A1618fs*56', 'p.A996fs*13', 'p.A1224E', 'p.A277fs*16', 'p.A952fs*6', 'p.A64fs*64', 'p.A972T', 'p.A258fs*3', 'p.A707fs*10', 'p.A1240V', 'p.A213V', 'p.A60V', 'p.A187T', 'p.A322fs*4', 'p.A187G', 'p.A520fs*4', 'p.A550fs*11', 'p.A903T', 'p.A1219fs*4', 'p.A382fs*69', 'p.A1512V', 'p.A1224delA', 'p.A40fs*120', 'p.A216G', 'p.A382fs*7', 'p.A2356fs*7', 'p.A275fs*7', 'p.A142fs*6', 'p.A270V', 'p.A84fs*112', 'p.A309fs*21', 'p.A912fs*9', 'p.A124fs*35', 'p.A470fs*131', 'p.A575V', 'p.A570T', 'p.A1822fs*11', 'p.A582fs*6', 'p.A696E', 'p.A280V', 'p.A186fs*10', 'p.A375fs*11', 'p.A1379D', 'p.A20G', 'p.A461G', 'p.A1341E', 'p.A234fs*5', 'p.A650T', 'p.A876fs*3', 'p.A72V', 'p.A1328fs*29', 'p.A380V', 'p.A161T', 'p.A435G', 'p.A76T', 'p.A377P', 'p.A1471fs*100', 'p.A130I', 'p.A202fs*17', 'p.A357fs*50', 'p.A621fs*10', 'p.A163V', 'p.A162_A163insVA', 'p.A572_K577delAQAAIK', 'p.A1863V', 'p.A572fs*2', 'p.A864V', 'p.A1344V', 'p.A1341fs*22', 'p.A72T', 'p.A1080fs*24', 'p.A18D', 'p.A410V', 'p.A1837fs*50', 'p.A746fs*22', 'p.A1080fs*25', 'p.A910V', 'p.A20V', 'p.A18fs*8', 'p.A121T', 'p.A329fs*271', 'p.A59T', 'p.A372T', 'p.A385P', 'p.A78_R83delAVLDGR', 'p.A26V', 'p.A1685fs*32', 'p.A750E', 'p.A912fs*10', 'p.A481fs*2', 'p.A680V', 'p.A274fs*48', 'p.A319G', 'p.A671fs*6', 'p.A744P', 'p.A627fs*8', 'p.A199L', 'p.A636fs*22', 'p.A359P', 'p.A223T', 'p.A910P', 'p.A75T', 'p.A1273_Y1274ins*', 'p.A85S', 'p.A584fs*17', 'p.A345T', 'p.A199fs*114', 'p.A146T', 'p.A8fs*10', 'p.A159fs*3', 'p.A461T', 'p.A970E', 'p.A827T', 'p.A1341fs*3', 'p.A470fs*121', 'p.A1262fs*16', 'p.A1837G', 'p.A352fs*248', 'p.A658fs*49', 'p.A956fs*7', 'p.A88fs*35', 'p.A340V', 'p.A1080fs*2', 'p.A149fs*3', 'p.A146P', 'p.A1562fs*9', 'p.A214fs*12', 'p.A1876G', 'p.A933V', 'p.A358fs*63', 'p.A79fs*29', 'p.A17E', 'p.A382fs*4', 'p.A324fs*277', 'p.A53T', 'p.A895T', 'p.A332T', 'p.A234_L235insVA', 'p.A140T', 'p.A330fs*10', 'p.A1508fs*60', 'p.A330fs*42', 'p.A142fs*3', 'p.A571fs*80', 'p.A20T', 'p.A404D', 'p.A619fs*84', 'p.A36T', 'p.A654fs*4', 'p.A884fs*37', 'p.A246fs*70', 'p.A66T', 'p.A603fs*8', 'p.A761fs*13', 'p.A671fs*1', 'p.A1434fs*14'], 'Cystéine': ['p.C135F', 'p.C1378_R1383delins*', 'p.C407fs*2', 'p.C527*', 'p.C370F', 'p.C1164fs*63', 'p.C1378R', 'p.C1298S', 'p.C1273F', 'p.C1289S', 'p.C88*', 'p.C381R', 'p.C478*', 'p.C396Y', 'p.C1396W', 'p.C181R', 'p.C22*', 'p.C549Y', 'p.C594fs*25', 'p.C381A', 'p.C1164Y', 'p.C172Y', 'p.C1211Y', 'p.C1211fs*14', 'p.C1711fs*5', 'p.C1095*', 'p.C632fs*15', 'p.C176R', 'p.C419Y', 'p.C396F', 'p.C1298R', 'p.C672fs*40', 'p.C585fs*90', 'p.C1289F', 'p.C457fs*5', 'p.C296fs*12', 'p.C1790fs*9', 'p.C1089*', 'p.C410*', 'p.C856fs*12', 'p.C283*', 'p.C292W', 'p.C124fs*25', 'p.C401Y', 'p.C324Y', 'p.C992fs*15', 'p.C1281fs*82', 'p.C1221Y', 'p.C353fs*2', 'p.C396R', 'p.C975*', 'p.C579fs*14', 'p.C730fs*14', 'p.C277*', 'p.C594*', 'p.C181W', 'p.C432fs*166', 'p.C1378W', 'p.C494*', 'p.C299fs*4', 'p.C141*', 'p.C687*', 'p.C384R', 'p.C666Y', 'p.C1271Y', 'p.C320Y', 'p.C187Y', 'p.C1271*', 'p.C186fs*45', 'p.C784fs*5', 'p.C632*', 'p.C332fs*15', 'p.C1358W', 'p.C1225Y', 'p.C181S', 'p.C784fs*30', 'p.C125W', 'p.C973fs*3', 'p.C772fs*13', 'p.C320S', 'p.C381F', 'p.C416S', 'p.C973fs*34', 'p.C1271fs*29', 'p.C238Y', 'p.C640fs*1', 'p.C1289_N1296delCSWSMYYN', 'p.C1341fs*28', 'p.C672*', 'p.C987fs*22', 'p.C1273S', 'p.C571S', 'p.C99*', 'p.C1707fs*37', 'p.C292Y', 'p.C275Y', 'p.C135W', 'p.C1289Y', 'p.C514fs*137', 'p.C385F', 'p.C20W', 'p.C275R', 'p.C351fs*56', 'p.C1193W', 'p.C1221S', 'p.C818G', 'p.C1642fs*19', 'p.C312Y', 'p.C238S', 'p.C1594F', 'p.C1400*', 'p.C1875G', 'p.C1374Y', 'p.C1135Y', 'p.C135Y', 'p.C381Y', 'p.C163_T164insC', 'p.C176fs*1', 'p.C677fs*23', 'p.C384Y', 'p.C915fs*16', 'p.C275W', 'p.C1594R', 'p.C404G', 'p.C1298Y', 'p.C1221*', 'p.C242R', 'p.C1271S', 'p.C404Y', 'p.C1464fs*6', 'p.C277Y', 'p.C700Y', 'p.C517R', 'p.C1271W', 'p.C384S', 'p.C176W', 'p.C724*', 'p.C527Y', 'p.C99G', 'p.C297Y', 'p.C710S', 'p.C497Y', 'p.C1358G', 'p.C1193Y', 'p.C135S', 'p.C20S', 'p.C557*', 'p.C20F', 'p.C1201Y', 'p.C1633*', 'p.C242F', 'p.C541F', 'p.C416W', 'p.C283Y', 'p.C350R', 'p.C987fs*2', 'p.C784*', 'p.C419W', 'p.C401R', 'p.C172F', 'p.C562Y', 'p.C527fs*49', 'p.C141Y', 'p.C1298fs*65', 'p.C176S', 'p.C357fs*65', 'p.C1811*', 'p.C559fs*92', 'p.C125Y', 'p.C687fs*30', 'p.C353fs*12', 'p.C1221F', 'p.C1732fs*4', 'p.C277F', 'p.C1080*', 'p.C1273Y', 'p.C238G', 'p.C1594Y', 'p.C263fs*4', 'p.C677fs*22', 'p.C1729fs*5', 'p.C1363fs*45', 'p.C529*', 'p.C1594W', 'p.C1378Y', 'p.C975fs*2', 'p.C499Y', 'p.C176G', 'p.C987*', 'p.C18W', 'p.C605*', 'p.C432fs*168', 'p.C176Y', 'p.C1606fs*12'], 'Acide aspartique': ['p.D2064fs*38', 'p.D233E', 'p.D664N', 'p.D392H', 'p.D1412fs*12', 'p.D596fs*1', 'p.D563fs*13', 'p.D123fs*11', 'p.D453G', 'p.D835N', 'p.D1635fs*5', 'p.D1598G', 'p.D1152fs*14', 'p.D2283fs*9', 'p.D527fs*6', 'p.D845N', 'p.D661V', 'p.D605Y', 'p.D664E', 'p.D155fs*2', 'p.D93Y', 'p.D868Y', 'p.D1113fs*17', 'p.D745fs*27', 'p.D816V', 'p.D868G', 'p.D614Y', 'p.D1598V', 'p.D594G', 'p.D271fs*45', 'p.D531G', 'p.D61N', 'p.D322_R323insSNND', 'p.D531delD', 'p.D1150N', 'p.D198G', 'p.D668G', 'p.D464N', 'p.D127V', 'p.D529N', 'p.D876G', 'p.D281V', 'p.D781E', 'p.D160Y', 'p.D198N', 'p.D1598N', 'p.D1844fs*2', 'p.D271fs*10', 'p.D1427V', 'p.D1615fs*14', 'p.D299fs*6', 'p.D322fs*1', 'p.D1598H', 'p.D835Y', 'p.D332fs*264', 'p.D835S', 'p.D657H', 'p.D69V', 'p.D832fs*6', 'p.D281N', 'p.D781G', 'p.D61G', 'p.D1322N', 'p.D118G', 'p.D1858fs*15', 'p.D594N', 'p.D198Y', 'p.D605V', 'p.D658fs*48', 'p.D835E', 'p.D605A', 'p.D281E', 'p.D1587fs*9', 'p.D868H', 'p.D855fs*11', 'p.D664delD', 'p.D835V', 'p.D515fs*6', 'p.D140A', 'p.D228fs*18', 'p.D123fs*15', 'p.D63fs*44', 'p.D25fs*9', 'p.D664G', 'p.D489fs*18', 'p.D1821fs*12', 'p.D1075fs*1', 'p.D1331fs*78', 'p.D269fs*9', 'p.D657Y', 'p.D282fs*1', 'p.D160G', 'p.D67Y', 'p.D1376N', 'p.D162fs*21', 'p.D756fs*11', 'p.D390Y', 'p.D1252fs*3', 'p.D185G', 'p.D281Y', 'p.D392Y', 'p.D390V', 'p.D198V', 'p.D1598A', 'p.D768Y', 'p.D57fs*66', 'p.D868N', 'p.D661Y', 'p.D63V', 'p.D1045H', 'p.D1437fs*16', 'p.D863fs*4', 'p.D137fs*5', 'p.D1536N', 'p.D51fs*75', 'p.D140fs*2', 'p.D61Y', 'p.D1136fs*10', 'p.D690fs*25', 'p.D677G', 'p.D1856fs*3', 'p.D107fs*54', 'p.D193G', 'p.D835H', 'p.D344E', 'p.D874N', 'p.D730fs*1', 'p.D61V', 'p.D1384V', 'p.D111fs*3', 'p.D1314fs*49', 'p.D228fs*1', 'p.D664H', 'p.D1143fs*9', 'p.D142V', 'p.D160H', 'p.D33E', 'p.D61A', 'p.D238fs*4', 'p.D218N', 'p.D438fs*213', 'p.D1807fs*13', 'p.D211fs*2', 'p.D868A', 'p.D757N', 'p.D372V', 'p.D432G', 'p.D93fs*1', 'p.D69N', 'p.D146Y', 'p.D254N', 'p.D784fs*1', 'p.D388delD', 'p.D148fs*22', 'p.D1376Y', 'p.D39fs*13', 'p.D160fs*1', 'p.D650fs*7', 'p.D605E', 'p.D299fs*2', 'p.D146V', 'p.D741fs*3', 'p.D839G', 'p.D656fs*2'], 'Acide glutamique': ['p.E404K', 'p.E143fs*2', 'p.E227fs*1', 'p.E513fs*16', 'p.E343fs*2', 'p.E877*', 'p.E1128fs*7', 'p.E476fs*7', 'p.E480*', 'p.E622D', 'p.E543_D544delED', 'p.E773fs*12', 'p.E294fs*22', 'p.E109fs*56', 'p.E1265fs*54', 'p.E664*', 'p.E76A', 'p.E947*', 'p.E420fs*36', 'p.E1437fs*11', 'p.E622V', 'p.E1918fs*15', 'p.E728fs*16', 'p.E1428K', 'p.E219fs*5', 'p.E576*', 'p.E954*', 'p.E1057*', 'p.E705fs*20', 'p.E365*', 'p.E645K', 'p.E2fs*27', 'p.E1137fs*15', 'p.E208Q', 'p.E395*', 'p.E287fs*58', 'p.E76V', 'p.E797*', 'p.E537fs*30', 'p.E5434K', 'p.E1344fs*22', 'p.E159Q', 'p.E858K', 'p.E472*', 'p.E790fs*1', 'p.E98G', 'p.E393D', 'p.E76G', 'p.E1144V', 'p.E1402*', 'p.E89fs*19', 'p.E733K', 'p.E798*', 'p.E902*', 'p.E733fs*8', 'p.E1413*', 'p.E914*', 'p.E258G', 'p.E335K', 'p.E382*', 'p.E1043*', 'p.E725*', 'p.E139D', 'p.E277*', 'p.E733fs*1', 'p.E1073*', 'p.E1165V', 'p.E422fs*175', 'p.E1918G', 'p.E1178fs*7', 'p.E156K', 'p.E783fs*30', 'p.E772fs*7', 'p.E263*', 'p.E886*', 'p.E510fs*23', 'p.E364*', 'p.E383*', 'p.E1352K', 'p.E1879A', 'p.E76K', 'p.E692fs*14', 'p.E856fs*8', 'p.E68*', 'p.E808fs*6', 'p.E259fs*19', 'p.E168fs*7', 'p.E28fs*14', 'p.E505fs*141', 'p.E801fs*17', 'p.E261fs*3', 'p.E888fs*10', 'p.E150fs*33', 'p.E1191*', 'p.E1166fs*60', 'p.E48*', 'p.E1879K', 'p.E773*', 'p.E1879fs*13', 'p.E433*', 'p.E154fs*3', 'p.E971fs*7', 'p.E754fs*59', 'p.E675D', 'p.E783K', 'p.E300*', 'p.E167fs*3', 'p.E782*', 'p.E1826K', 'p.E545G', 'p.E159G', 'p.E865*', 'p.E131fs*12', 'p.E928*', 'p.E204fs*43', 'p.E219fs*4', 'p.E1186*', 'p.E523*', 'p.E820fs*5', 'p.E990fs*6', 'p.E1318fs*45', 'p.E728*', 'p.E1436*', 'p.E376K', 'p.E1429fs*67', 'p.E878*', 'p.E1689fs*28', 'p.E337*', 'p.E54K', 'p.E109fs*52', 'p.E278fs*27', 'p.E429*', 'p.E37*', 'p.E1428*', 'p.E303fs*49', 'p.E1709*', 'p.E534*', 'p.E166*', 'p.E47*', 'p.E1318D', 'p.E1093*', 'p.E545K', 'p.E532fs*47', 'p.E98A', 'p.E362Q', 'p.E523fs*23', 'p.E1879G', 'p.E1887*', 'p.E167*', 'p.E1144Q', 'p.E856fs*7', 'p.E143fs*1', 'p.E219fs*31', 'p.E475fs*8', 'p.E817*', 'p.E396fs*>93', 'p.E1483*', 'p.E1025fs*54', 'p.E1851*', 'p.E93fs*15', 'p.E227fs*7', 'p.E1382fs*26', 'p.E862K', 'p.E711fs*40', 'p.E705*', 'p.E1323_S1324delinsD', 'p.E1357fs*14', 'p.E540fs*7', 'p.E1020fs*13', 'p.E201D', 'p.E382K', 'p.E240fs*8', 'p.E769*', 'p.E504fs*10', 'p.E113fs*52', 'p.E451*', 'p.E249K', 'p.E33K', 'p.E137D', 'p.E493*', 'p.E1874*', 'p.E98D', 'p.E76L', 'p.E566*', 'p.E475*', 'p.E318fs*58', 'p.E149fs*1', 'p.E139*', 'p.E1250*', 'p.E11*', 'p.E820*', 'p.E1459fs*18', 'p.E628fs*10', 'p.E406*', 'p.E69K', 'p.E133fs*11', 'p.E756*', 'p.E537*', 'p.E1099K', 'p.E283*', 'p.E1250fs*11', 'p.E931*', 'p.E366K', 'p.E159_M160insYE', 'p.E391*', 'p.E403fs*9', 'p.E610*', 'p.E865G', 'p.E525*', 'p.E1319*', 'p.E1178fs*9', 'p.E330*', 'p.E122*', 'p.E1165fs*62', 'p.E1411fs*37', 'p.E297_R300delELER', 'p.E1518*', 'p.E376*', 'p.E316fs*283', 'p.E906fs*3', 'p.E420fs*35', 'p.E176*', 'p.E719fs*6', 'p.E547fs*27', 'p.E421fs*22', 'p.E947fs*4', 'p.E362*', 'p.E820Q', 'p.E378*', 'p.E477*', 'p.E783*', 'p.E1643fs*34', 'p.E229*', 'p.E286G', 'p.E1162*', 'p.E599*', 'p.E523fs*25', 'p.E120fs*24', 'p.E50fs*58', 'p.E59*', 'p.E194fs*12', 'p.E423*', 'p.E1728*', 'p.E667G', 'p.E862fs*45', 'p.E271G', 'p.E697_K700delinsDP', 'p.E676*', 'p.E63_Y64insLDG', 'p.E1267fs*1', 'p.E628fs*11', 'p.E1242*', 'p.E961*', 'p.E381_A382insE', 'p.E15*', 'p.E271K', 'p.E401fs*22', 'p.E256K', 'p.E877K', 'p.E733G', 'p.E1405*', 'p.E69V', 'p.E76Q', 'p.E118fs*27', 'p.E35*', 'p.E27*', 'p.E208*', 'p.E41*', 'p.E740fs*12', 'p.E1119fs*10', 'p.E537K', 'p.E463fs*188', 'p.E330K', 'p.E678*', 'p.E303fs*14', 'p.E567fs*40', 'p.E611D', 'p.E343*', 'p.E1144*', 'p.E285*', 'p.E223*', 'p.E91*', 'p.E292*', 'p.E449K', 'p.E657fs*11', 'p.E788fs*30', 'p.E443*', 'p.E400*', 'p.E756fs*23', 'p.E984*', 'p.E1555fs*22', 'p.E657*', 'p.E616delE', 'p.E473*', 'p.E727*', 'p.E95fs*12', 'p.E180*', 'p.E67*', 'p.E212*', 'p.E284*', 'p.E1178*', 'p.E449Q', 'p.E613fs*2', 'p.E635fs*15', 'p.E246*', 'p.E98V', 'p.E808*', 'p.E1178fs*48', 'p.E1178G', 'p.E98Q', 'p.E543fs*7', 'p.E711fs*9', 'p.E159_M160insNE', 'p.E1224fs*3', 'p.E621*', 'p.E592K', 'p.E583*', 'p.E297fs*4', 'p.E767fs*28', 'p.E782fs*32', 'p.E842*', 'p.E950fs*12', 'p.E854fs*27', 'p.E744Q', 'p.E1106*', 'p.E1356*', 'p.E1315*', 'p.E1224*', 'p.E1643fs*31', 'p.E635*', 'p.E602*', 'p.E1573*', 'p.E347fs*76'], 'Phénylalanine': ['p.F468fs*5', 'p.F158fs*18', 'p.F183fs*23', 'p.F1104fs*2', 'p.F909I', 'p.F1706fs*5', 'p.F180fs*31', 'p.F1043fs*6', 'p.F1300C', 'p.F331Y', 'p.F396fs*205', 'p.F368L', 'p.F909S', 'p.F776fs*37', 'p.F212fs*3', 'p.F396fs*204', 'p.F1429fs*19', 'p.F868L', 'p.F732C', 'p.F113C', 'p.F116C', 'p.F1104fs*3', 'p.F534fs*5', 'p.F751fs*28', 'p.F1309L', 'p.F40fs*14', 'p.F1419fs*65', 'p.F531L_P532S', 'p.F751C', 'p.F133fs*76', 'p.F1377S', 'p.F329fs*1', 'p.F125fs*3', 'p.F794S', 'p.F48fs*12', 'p.F513fs*57', 'p.F670S', 'p.F1300I', 'p.F158C', 'p.F194fs*6', 'p.F182fs*15', 'p.F468S', 'p.F1419fs*40', 'p.F752C', 'p.F519fs*14', 'p.F788fs*6', 'p.F640fs*1', 'p.F270L', 'p.F416fs*185', 'p.F330fs*271', 'p.F603C', 'p.F1289fs*1', 'p.F1600fs*18', 'p.F1210fs*7', 'p.F270I', 'p.F731L', 'p.F116S', 'p.F152fs*32', 'p.F1377I', 'p.F365L', 'p.F332fs*6', 'p.F1104fs*25', 'p.F1689fs*6', 'p.F40fs*5', 'p.F865fs*14', 'p.F330fs*269', 'p.F603L', 'p.F1300S', 'p.F1287S', 'p.F365fs*20', 'p.F52fs*2', 'p.F78fs*15', 'p.F163V', 'p.F1168fs*8', 'p.F57fs*11', 'p.F418S', 'p.F73fs*89', 'p.F854fs*19', 'p.F732S', 'p.F548fs*2', 'p.F710fs*7', 'p.F365I', 'p.F293fs*10', 'p.F732L', 'p.F82fs*80', 'p.F734I', 'p.F341S', 'p.F418L', 'p.F752S', 'p.F768fs*17', 'p.F224fs*17', 'p.F760fs*8', 'p.F438L', 'p.F868fs*13', 'p.F183I', 'p.F155L', 'p.F71L', 'p.F732delF', 'p.F285C', 'p.F331I', 'p.F97fs*42', 'p.F534fs*1', 'p.F755S', 'p.F82fs*78', 'p.F670L', 'p.F1377fs*23', 'p.F1901fs*4', 'p.F357L', 'p.F729fs*11', 'p.F1683fs*3', 'p.F414fs*7', 'p.F379I', 'p.F1285delF', 'p.F331L', 'p.F1377V', 'p.F116fs*30', 'p.F245fs*20', 'p.F1287fs*13', 'p.F285L', 'p.F149fs*2', 'p.F514fs*38', 'p.F165fs*65', 'p.F1287fs*76', 'p.F134L', 'p.F303L', 'p.F341C'], 'Glycine': ['p.G1152E', 'p.G12D', 'p.G244D', 'p.G422fs*5', 'p.G406R', 'p.G170fs*7', 'p.G870fs*38', 'p.G447D', 'p.G72R', 'p.G685R', 'p.G251R', 'p.G1590fs*6', 'p.G298R', 'p.G244V', 'p.G824D', 'p.G726V', 'p.G13V', 'p.G1590fs*24', 'p.G643fs*15', 'p.G787fs*26', 'p.G628fs*48', 'p.G1275A', 'p.G251E', 'p.G60D', 'p.G165fs*12', 'p.G686V', 'p.G989fs*6', 'p.G135R', 'p.G1223V', 'p.G1275R', 'p.G245S', 'p.G412fs*182', 'p.G740V', 'p.G354fs*>135', 'p.G12A', 'p.G645fs*55', 'p.G1370E', 'p.G503E', 'p.G220R', 'p.G50fs*4', 'p.G375R', 'p.G685W', 'p.G375V', 'p.G728D', 'p.G1361S', 'p.G1288S', 'p.G413S', 'p.G229fs*47', 'p.G429R', 'p.G870D', 'p.G859fs*48', 'p.G503W', 'p.G699D', 'p.G6*', 'p.G268D', 'p.G686C', 'p.G397V', 'p.G257fs*61', 'p.G179R', 'p.G905D', 'p.G36fs*122', 'p.G306V', 'p.G244S', 'p.G218D', 'p.G1152R', 'p.G1034fs*45', 'p.G751V', 'p.G646E', 'p.G892E', 'p.G643fs*9', 'p.G60E', 'p.G340S', 'p.G1370R', 'p.G543fs*18', 'p.G12S', 'p.G135S', 'p.G726S', 'p.G646fs*12', 'p.G1370V', 'p.G972R', 'p.G695V', 'p.G13R', 'p.G268V', 'p.G738*', 'p.G868E', 'p.G387fs*207', 'p.G742D', 'p.G669fs*2', 'p.G850R', 'p.G130S', 'p.G1131R', 'p.G744fs*30', 'p.G1376*', 'p.G1189fs*12', 'p.G421fs*169', 'p.G1288D', 'p.G796fs*15', 'p.G36fs*67', 'p.G469A', 'p.G714R', 'p.G168*', 'p.G1861E', 'p.G856fs*17', 'p.G777fs*4', 'p.G777fs*5', 'p.G1682fs*20', 'p.G160_D161insG', 'p.G266V', 'p.G1297*', 'p.G349fs*23', 'p.G130fs*23', 'p.G114R', 'p.G109*', 'p.G530A', 'p.G1361V', 'p.G130V', 'p.G676D', 'p.G1288V', 'p.G160R', 'p.G415S', 'p.G387fs*213', 'p.G543D', 'p.G740R', 'p.G667V', 'p.G870V', 'p.G743fs*20', 'p.G93_H100delGRPPDSHH', 'p.G39D', 'p.G262delG', 'p.G660R', 'p.G1361fs*3', 'p.G644fs*12', 'p.G199fs*17', 'p.G613fs*25', 'p.G168fs*41', 'p.G12V', 'p.G248D', 'p.G266E', 'p.G13C', 'p.G266R', 'p.G699R', 'p.G332R', 'p.G870C', 'p.G738fs*6', 'p.G648R', 'p.G199E', 'p.G165fs*13', 'p.G843A', 'p.G660E', 'p.G41fs*18', 'p.G287S', 'p.G165S', 'p.G436fs*>53', 'p.G135D', 'p.G320D', 'p.G685fs*33', 'p.G649*', 'p.G19*', 'p.G194fs*27', 'p.G1282V', 'p.G24R', 'p.G826fs*12', 'p.G122R', 'p.G13D', 'p.G287D', 'p.G325fs*18', 'p.G57E', 'p.G738fs*16', 'p.G800fs*2', 'p.G46fs*41', 'p.G268S', 'p.G39_V40insG', 'p.G375A', 'p.G1393fs*103', 'p.G662D', 'p.G165C', 'p.G1814*', 'p.G543A', 'p.G50fs*88', 'p.G1192V', 'p.G104V', 'p.G645fs*13', 'p.G244R', 'p.G12R', 'p.G122fs*16', 'p.G1282D', 'p.G1861*', 'p.G143fs*4', 'p.G12C', 'p.G289*', 'p.G179fs*59', 'p.G680fs*38', 'p.G165D', 'p.G151E', 'p.G60A', 'p.G1620fs*38', 'p.G168fs*40', 'p.G870S', 'p.G571S', 'p.G135*', 'p.G114fs*5', 'p.G1365V', 'p.G649fs*9', 'p.G69S', 'p.G520fs*13', 'p.G868fs*10', 'p.G422_Q423delGQ', 'p.G245D', 'p.G543C', 'p.G629fs*7', 'p.G1007fs*17', 'p.G856R', 'p.G275A', 'p.G530D', 'p.G724fs*2', 'p.G1235*', 'p.G1187fs*39', 'p.G697fs*102', 'p.G618R', 'p.G986fs*21', 'p.G235fs*11', 'p.G740E', 'p.G1152_A1153insG', 'p.G438S', 'p.G742fs*1', 'p.G643fs*16', 'p.G170E', 'p.G532R', 'p.G707D', 'p.G245V', 'p.G168fs*9', 'p.G187S', 'p.G13_V14insG', 'p.G629R', 'p.G173R', 'p.G503R', 'p.G796D', 'p.G1198*', 'p.G1113fs*94', 'p.G368fs*>121', 'p.G1869fs*7', 'p.G1154fs*72', 'p.G190*', 'p.G570V', 'p.G679*', 'p.G1235R', 'p.G511D', 'p.G412fs*189', 'p.G1361R', 'p.G154fs*16', 'p.G308D', 'p.G413C', 'p.G521fs*55', 'p.G550R', 'p.G1309E', 'p.G1192_C1193ins*', 'p.G479R', 'p.G68fs*65', 'p.G367S', 'p.G1192fs*34', 'p.G367_M368insIG', 'p.G60V', 'p.G1275V', 'p.G356fs*68', 'p.G39V', 'p.G158R', 'p.G503A', 'p.G67R', 'p.G291R', 'p.G57R', 'p.G320V', 'p.G87fs*52', 'p.G13A', 'p.G511E', 'p.G287V', 'p.G710fs*15'], 'Histidine': ['p.H302P', 'p.H568D', 'p.H1416D', 'p.H839fs*2', 'p.H1150fs*1', 'p.H1727fs*18', 'p.H1881R', 'p.H345D', 'p.H662D', 'p.H573fs*7', 'p.H1904L', 'p.H1150fs*2', 'p.H193R', 'p.H398Y', 'p.H717fs*6', 'p.H502fs*9', 'p.H990fs*17', 'p.H1868D', 'p.H191R', 'p.H135fs*74', 'p.H922fs*31', 'p.H355fs*52', 'p.H1380P', 'p.H214R', 'p.H762fs*51', 'p.H193D', 'p.H191L', 'p.H724fs*29', 'p.H329R', 'p.H1382L', 'p.H1386D', 'p.H1881Y', 'p.H1745P', 'p.H184N', 'p.H1732fs*9', 'p.H698fs*4', 'p.H2480fs*4', 'p.H24fs*84', 'p.H330Y', 'p.H1386fs*15', 'p.H1761fs*5', 'p.H1036fs*19', 'p.H1778fs*43', 'p.H546fs*15', 'p.H800fs*13', 'p.H239R', 'p.H662Q', 'p.H1219Y', 'p.H329L', 'p.H330D', 'p.H105fs*33', 'p.H1732fs*7', 'p.H1875R', 'p.H404fs*197', 'p.H1148fs*12', 'p.H369Y', 'p.H168L', 'p.H637fs*5', 'p.H179D', 'p.H404fs*196', 'p.H1380fs*18', 'p.H179Q', 'p.H630fs*4', 'p.H995fs*25', 'p.H786fs*27', 'p.H717fs*5', 'p.H302fs*50', 'p.H1416Y', 'p.H125fs*44', 'p.H1778fs*1', 'p.H414Y', 'p.H1912P', 'p.H1717fs*13', 'p.H1380Y', 'p.H1912fs*9', 'p.H1757fs*6', 'p.H658fs*22', 'p.H661fs*37', 'p.H995fs*3', 'p.H1792fs*28', 'p.H990fs*18', 'p.H1912R', 'p.H1727fs*14', 'p.H410R', 'p.H434fs*13', 'p.H897fs*7', 'p.H242fs*14', 'p.H191fs*130', 'p.H1904Y', 'p.H717fs*34', 'p.H398Q', 'p.H1868R', 'p.H662Y', 'p.H413Q', 'p.H1904R', 'p.H1036fs*7', 'p.H1380R', 'p.H682fs*9', 'p.H330R', 'p.H137fs*20', 'p.H193L', 'p.H179R', 'p.H329fs*22', 'p.H1676fs*19', 'p.H258N', 'p.H239L', 'p.H1382Q', 'p.H624D', 'p.H1881N', 'p.H160P', 'p.H588fs*63', 'p.H1492fs*77', 'p.H1904N', 'p.H184Q', 'p.H243P', 'p.H43fs*38', 'p.H360Y', 'p.H632fs*17', 'p.H1584fs*30', 'p.H178D', 'p.H398R', 'p.H448fs*29', 'p.H179L', 'p.H169fs*14', 'p.H588fs*62', 'p.H800fs*15', 'p.H1912fs*38', 'p.H1047R', 'p.H26fs*159', 'p.H314fs*15', 'p.H115fs*32', 'p.H190fs*24', 'p.H506fs*40', 'p.H1792fs*3', 'p.H18fs*91', 'p.H243Q', 'p.H302R', 'p.H863fs*3', 'p.H345Y', 'p.H169fs*2', 'p.H717fs*2', 'p.H258Q', 'p.H789fs*8', 'p.H105Y', 'p.H418fs*>71', 'p.H1904Q', 'p.H506P', 'p.H1281fs*8', 'p.H821R', 'p.H445fs*12', 'p.H1817fs*5', 'p.H1380N', 'p.H1382R', 'p.H193fs*14', 'p.H178fs*3'], 'Isoleucine': ['p.I1873S', 'p.I451fs*2', 'p.I254fs*32', 'p.I1897fs*11', 'p.I1236S', 'p.I1139fs*13', 'p.I410fs*46', 'p.I292T', 'p.I2548M', 'p.I921fs*32', 'p.I274V', 'p.I705fs*74', 'p.I234fs*2', 'p.I833V', 'p.I679fs*21', 'p.I1163fs*63', 'p.I146fs*2', 'p.I281fs*3', 'p.I621fs*15', 'p.I146T', 'p.I254N', 'p.I292fs*24', 'p.I1689fs*36', 'p.I254S', 'p.I36M', 'p.I342fs*258', 'p.I715T', 'p.I715fs*19', 'p.I80T', 'p.I130fs*2', 'p.I827L', 'p.I713M', 'p.I822fs*19', 'p.I193fs*22', 'p.I62fs*46', 'p.I780T', 'p.I195S', 'p.I177fs*35', 'p.I423S', 'p.I191_K195delINQDK', 'p.I750fs*62', 'p.I251L', 'p.I520F', 'p.I655T', 'p.I195fs*17', 'p.I637fs*28', 'p.I396T', 'p.I780N', 'p.I207T', 'p.I846V', 'p.I254T', 'p.I162fs*19', 'p.I307fs*4', 'p.I652fs*9', 'p.I855fs*18', 'p.I824fs*2', 'p.I383M', 'p.I497V', 'p.I255T', 'p.I1937fs*7', 'p.I195T', 'p.I122fs*7', 'p.I451fs*1', 'p.I695N', 'p.I913fs*5', 'p.I227fs*14', 'p.I2053fs*11', 'p.I694fs*24', 'p.I589fs*13', 'p.I314T', 'p.I899fs*8', 'p.I771fs*15', 'p.I294fs*57', 'p.I294V', 'p.I1566fs*9', 'p.I597fs*106', 'p.I255delI', 'p.I482fs*17', 'p.I617_K618delins*', 'p.I1160F', 'p.I661N', 'p.I407T', 'p.I383T', 'p.I679fs*10', 'p.I201L', 'p.I68fs*41', 'p.I1873T', 'p.I539fs*4', 'p

In [139]:

acide_aminee = {}

for elem in protein_change:
    for aa_name , mutations in dico_protein_changes.items():
        if elem in mutations:
            acide_aminee[elem] = aa_name
            

print(acide_aminee)

{'p.R1878fs*2': 'Arginine', 'p.P904Q': 'Proline', 'p.G1152E': 'Glycine', 'p.D2064fs*38': 'Acide aspartique', 'p.D233E': 'Acide aspartique', 'p.S210*': 'Sérine', 'p.G12D': 'Glycine', 'p.G244D': 'Glycine', 'p.S100*': 'Sérine', 'p.V41I': 'Valine', 'p.T590fs*29': 'Thréonine', 'p.S327fs*4': 'Sérine', 'p.S1255*': 'Sérine', 'p.S1598fs*28': 'Sérine', 'p.N460fs*5': 'Asparagine', 'p.E404K': 'Acide glutamique', 'p.Q1687*': 'Glutamine', 'p.Q317*': 'Glutamine', 'p.C135F': 'Cystéine', 'p.L286_F287insSLSL': 'Leucine', 'p.R583*': 'Arginine', 'p.Y220C': 'Tyrosine', 'p.Q124*': 'Glutamine', 'p.R1262L': 'Arginine', 'p.L98fs*24': 'Leucine', 'p.D664N': 'Acide aspartique', 'p.L1694*': 'Leucine', 'p.N253fs*41': 'Asparagine', 'p.G422fs*5': 'Glycine', 'p.W408C': 'Tryptophane', 'p.H302P': 'Histidine', 'p.V371fs*18': 'Valine', 'p.Y346C': 'Tyrosine', 'p.L161P': 'Leucine', 'p.Q432*': 'Glutamine', 'p.V360fs*234': 'Valine', 'p.R174fs*4': 'Arginine', 'p.I1873S': 'Isoleucine', 'p.K1173*': 'Lysine', 'p.R267W': 'Arginine', 'p.L591*': 'Leucine', 'p.S206fs*1': 'Sérine', 'p.Y2285fs*1': 'Tyrosine', 'p.M701V': 'Méthionine', 'p.G406R': 'Glycine', 'p.D392H': 'Acide aspartique', 'p.V509fs*14': 'Valine', 'p.A858fs*29': 'Alanine', 'p.S1107*': 'Sérine', 'p.L546fs*1': 'Leucine', 'p.M725fs*16': 'Méthionine', 'p.R370fs*7': 'Arginine', 'p.I451fs*2': 'Isoleucine', 'p.Q61P': 'Glutamine', 'p.P678T': 'Proline', 'p.R169fs*56': 'Arginine', 'p.Y63C': 'Tyrosine', 'p.P96A': 'Proline', 'p.R341Q': 'Arginine', 'p.R397Q': 'Arginine', 'p.P1496fs*75': 'Proline', 'p.P491A': 'Proline', 'p.C1378_R1383delins*': 'Cystéine', 'p.P489fs*40': 'Proline', 'p.R198fs*8': 'Arginine', 'p.S867R': 'Sérine', 'p.N477H': 'Asparagine', 'p.Q1031*': 'Glutamine', 'p.V116fs*28': 'Valine', 'p.P2326Q': 'Proline', 'p.E143fs*2': 'Acide glutamique', 'p.K291fs*18': 'Lysine', 'p.R152*': 'Arginine', 'p.R399H': 'Arginine', 'p.F468fs*5': 'Phénylalanine', 'p.C407fs*2': 'Cystéine', 'p.E227fs*1': 'Acide glutamique', 'p.L291P': 'Leucine', 'p.Y205D': 'Tyrosine', 'p.R450fs*20': 'Arginine', 'p.V1213G': 'Valine', 'p.Y355fs*1': 'Tyrosine', 'p.S1431fs*17': 'Sérine', 'p.P442fs*16': 'Proline', 'p.E513fs*16': 'Acide glutamique', 'p.K228fs*25': 'Lysine', 'p.H568D': 'Histidine', 'p.D1412fs*12': 'Acide aspartique', 'p.Q1117fs*18': 'Glutamine', 'p.L85fs*28': 'Leucine', 'p.T1884I': 'Thréonine', 'p.E343fs*2': 'Acide glutamique', 'p.L380P': 'Leucine', 'p.K139N_T140delT': 'Lysine', 'p.G170fs*7': 'Glycine', 'p.E877*': 'Acide glutamique', 'p.L1418fs*7': 'Leucine', 'p.S121fs*2': 'Sérine', 'p.K110R': 'Lysine', 'p.T1085fs*19': 'Thréonine', 'p.D596fs*1': 'Acide aspartique', 'p.E1128fs*7': 'Acide glutamique', 'p.R15fs*82': 'Arginine', 'p.S1630*': 'Sérine', 'p.F158fs*18': 'Phénylalanine', 'p.D563fs*13': 'Acide aspartique', 'p.C527*': 'Cystéine', 'p.L1413fs*83': 'Leucine', 'p.K110Q': 'Lysine', 'p.K1018N': 'Lysine', 'p.E476fs*7': 'Acide glutamique', 'p.H1416D': 'Histidine', 'p.N492fs*9': 'Asparagine', 'p.Q769fs*44': 'Glutamine', 'p.R380fs*72': 'Arginine', 'p.G870fs*38': 'Glycine', 'p.R82H': 'Arginine', 'p.N730Y': 'Asparagine', 'p.S402*': 'Sérine', 'p.S1059fs*1': 'Sérine', 'p.E480*': 'Acide glutamique', 'p.K618fs*1': 'Lysine', 'p.L703V': 'Leucine', 'p.W279*': 'Tryptophane', 'p.V238fs*16': 'Valine', 'p.D123fs*11': 'Acide aspartique', 'p.Q289fs*11': 'Glutamine', 'p.S349*': 'Sérine', 'p.N822K': 'Asparagine', 'p.A36V': 'Alanine', 'p.N405fs*21': 'Asparagine', 'p.A435S': 'Alanine', 'p.W1016*': 'Tryptophane', 'p.R238Q': 'Arginine', 'p.Q1445*': 'Glutamine', 'p.Q269fs*12': 'Glutamine', 'p.F183fs*23': 'Phénylalanine', 'p.Y331*': 'Tyrosine', 'p.D453G': 'Acide aspartique', 'p.S825fs*1': 'Sérine', 'p.D835N': 'Acide aspartique', 'p.G447D': 'Glycine', 'p.P250fs*3': 'Proline', 'p.S336fs*45': 'Sérine', 'p.D1635fs*5': 'Acide aspartique', 'p.L743fs*57': 'Leucine', 'p.E622D': 'Acide glutamique', 'p.R73W': 'Arginine', 'p.N1573fs*6': 'Asparagine', 'p.D1598G': 'Acide aspartique', 'p.T377I': 'Thréonine', 'p.H839fs*2': 'Histidine', 'p.F1104fs*2': 'Phénylalanine', 'p.E543_D544delED': 'Acide glutamique', 'p.Q2230fs*114': 'Glutamine', 'p.Y220H': 'Tyrosine', 'p.N1504fs*67': 'Asparagine', 'p.S597fs*41': 'Sérine', 'p.R172K': 'Arginine', 'p.R103fs*9': 'Arginine', 'p.R122*': 'Arginine', 'p.A640fs*14': 'Alanine', 'p.I254fs*32': 'Isoleucine', 'p.V157G': 'Valine', 'p.G72R': 'Glycine', 'p.L335fs*69': 'Leucine', 'p.Y64C': 'Tyrosine', 'p.G685R': 'Glycine', 'p.W340*': 'Tryptophane', 'p.I1897fs*11': 'Isoleucine', 'p.D1152fs*14': 'Acide aspartique', 'p.S1982fs*30': 'Sérine', 'p.R1359H': 'Arginine', 'p.R1196*': 'Arginine', 'p.I1236S': 'Isoleucine', 'p.F909I': 'Phénylalanine', 'p.E773fs*12': 'Acide glutamique', 'p.T212S': 'Thréonine', 'p.K57E': 'Lysine', 'p.V360fs*239': 'Valine', 'p.E294fs*22': 'Acide glutamique', 'p.Q1548*': 'Glutamine', 'p.R1383G': 'Arginine', 'p.P368S': 'Proline', 'p.E109fs*56': 'Acide glutamique', 'p.I1139fs*13': 'Isoleucine', 'p.L1515fs*56': 'Leucine', 'p.C370F': 'Cystéine', 'p.R107fs*30': 'Arginine', 'p.G251R': 'Glycine', 'p.P153fs*28': 'Proline', 'p.L158fs*3': 'Leucine', 'p.R1164*': 'Arginine', 'p.R334fs*266': 'Arginine', 'p.G1590fs*6': 'Glycine', 'p.A571fs*5': 'Alanine', 'p.H1150fs*1': 'Histidine', 'p.S2816fs*6': 'Sérine', 'p.H1727fs*18': 'Histidine', 'p.R786*': 'Arginine', 'p.S321N': 'Sérine', 'p.N587fs*1': 'Asparagine', 'p.V332M': 'Valine', 'p.R676W': 'Arginine', 'p.N293delN': 'Asparagine', 'p.I410fs*46': 'Isoleucine', 'p.A138T': 'Alanine', 'p.R148*': 'Arginine', 'p.A59E': 'Alanine', 'p.Q705fs*7': 'Glutamine', 'p.Q1542_R1543ins*': 'Glutamine', 'p.W930*': 'Tryptophane', 'p.W694C': 'Tryptophane', 'p.V418I': 'Valine', 'p.R844H': 'Arginine', 'p.Q481*': 'Glutamine', 'p.S1601fs*9': 'Sérine', 'p.L1212S': 'Leucine', 'p.E1265fs*54': 'Acide glutamique', 'p.E664*': 'Acide glutamique', 'p.L1872fs*3': 'Leucine', 'p.N308D': 'Asparagine', 'p.V2306fs*2': 'Valine', 'p.S424fs*19': 'Sérine', 'p.M371fs*229': 'Méthionine', 'p.L70M': 'Leucine', 'p.R693*': 'Arginine', 'p.V1199fs*16': 'Valine', 'p.E76A': 'Acide glutamique', 'p.L462*': 'Leucine', 'p.E947*': 'Acide glutamique', 'p.A671fs*29': 'Alanine', 'p.E420fs*36': 'Acide glutamique', 'p.K62fs*16': 'Lysine', 'p.Y65fs*46': 'Tyrosine', 'p.L1244P': 'Leucine', 'p.P278A': 'Proline', 'p.R27P': 'Arginine', 'p.M904fs*2': 'Méthionine', 'p.L204R': 'Leucine', 'p.A809fs*13': 'Alanine', 'p.V1446fs*2': 'Valine', 'p.R1007*': 'Arginine', 'p.E1437fs*11': 'Acide glutamique', 'p.R655Q': 'Arginine', 'p.R525H': 'Arginine', 'p.P479fs*7': 'Proline', 'p.Q952*': 'Glutamine', 'p.A1810fs*10': 'Alanine', 'p.A146V': 'Alanine', 'p.I292T': 'Isoleucine', 'p.G298R': 'Glycine', 'p.Y365H': 'Tyrosine', 'p.M504V': 'Méthionine', 'p.K1299R': 'Lysine', 'p.I2548M': 'Isoleucine', 'p.S665fs*1': 'Sérine', 'p.A377G': 'Alanine', 'p.R110P': 'Arginine', 'p.E622V': 'Acide glutamique', 'p.K1472*': 'Lysine', 'p.E1918fs*15': 'Acide glutamique', 'p.D2283fs*9': 'Acide aspartique', 'p.Y104*': 'Tyrosine', 'p.T738fs*48': 'Thréonine', 'p.R116*': 'Arginine', 'p.R392W': 'Arginine', 'p.H1881R': 'Histidine', 'p.Y322C': 'Tyrosine', 'p.M1319T': 'Méthionine', 'p.T50I': 'Thréonine', 'p.A1158V': 'Alanine', 'p.N857fs*15': 'Asparagine', 'p.K318*': 'Lysine', 'p.Q404*': 'Glutamine', 'p.P433L': 'Proline', 'p.Y259C': 'Tyrosine', 'p.S1486*': 'Sérine', 'p.S1798*': 'Sérine', 'p.W440*': 'Tryptophane', 'p.R1359L': 'Arginine', 'p.T468M': 'Thréonine', 'p.L370F': 'Leucine', 'p.R625fs*12': 'Arginine', 'p.I921fs*32': 'Isoleucine', 'p.S34Y': 'Sérine', 'p.S1518*': 'Sérine', 'p.Q1348R': 'Glutamine', 'p.Q7fs*4': 'Glutamine', 'p.D527fs*6': 'Acide aspartique', 'p.H345D': 'Histidine', 'p.W1065*': 'Tryptophane', 'p.Y1294H': 'Tyrosine', 'p.Y103fs*1': 'Tyrosine', 'p.T196I': 'Thréonine', 'p.S172fs*4': 'Sérine', 'p.S805fs*50': 'Sérine', 'p.G244V': 'Glycine', 'p.A51fs*36': 'Alanine', 'p.Y1608*': 'Tyrosine', 'p.N477S': 'Asparagine', 'p.H662D': 'Histidine', 'p.R191fs*21': 'Arginine', 'p.Q591fs*10': 'Glutamine', 'p.N244H': 'Asparagine', 'p.I274V': 'Isoleucine', 'p.Q623fs*7': 'Glutamine', 'p.E728fs*16': 'Acide glutamique', 'p.D845N': 'Acide aspartique', 'p.C1164fs*63': 'Cystéine', 'p.E1428K': 'Acide glutamique', 'p.P274fs*8': 'Proline', 'p.S139fs*14': 'Sérine', 'p.P390fs*32': 'Proline', 'p.D661V': 'Acide aspartique', 'p.Y636fs*1': 'Tyrosine', 'p.N92K': 'Asparagine', 'p.C1378R': 'Cystéine', 'p.R690C': 'Arginine', 'p.L146fs*14': 'Leucine', 'p.P1108fs*22': 'Proline', 'p.R326H': 'Arginine', 'p.E219fs*5': 'Acide glutamique', 'p.Y1245fs*21': 'Tyrosine', 'p.H573fs*7': 'Histidine', 'p.R655G': 'Arginine', 'p.D605Y': 'Acide aspartique', 'p.Q1191*': 'Glutamine', 'p.L737R': 'Leucine', 'p.K1877fs*10': 'Lysine', 'p.E576*': 'Acide glutamique', 'p.N837fs*1': 'Asparagine', 'p.S340fs*37': 'Sérine', 'p.R729W': 'Arginine', 'p.F1706fs*5': 'Phénylalanine', 'p.H1904L': 'Histidine', 'p.K227fs*52': 'Lysine', 'p.S794*': 'Sérine', 'p.P1232fs*7': 'Proline', 'p.P848L': 'Proline', 'p.F180fs*31': 'Phénylalanine', 'p.T361I': 'Thréonine', 'p.Y1245N': 'Tyrosine', 'p.I705fs*74': 'Isoleucine', 'p.R550Q': 'Arginine', 'p.G824D': 'Glycine', 'p.H1150fs*2': 'Histidine', 'p.Q2876*': 'Glutamine', 'p.R2436H': 'Arginine', 'p.R1007fs*63': 'Arginine', 'p.Q144*': 'Glutamine', 'p.A324fs*276': 'Alanine', 'p.A1196delA': 'Alanine', 'p.E954*': 'Acide glutamique', 'p.G726V': 'Glycine', 'p.P206A': 'Proline', 'p.C1298S': 'Cystéine', 'p.Q929H': 'Glutamine', 'p.M1T': 'Méthionine', 'p.S2090fs*1': 'Sérine', 'p.E1057*': 'Acide glutamique', 'p.D664E': 'Acide aspartique', 'p.W10C': 'Tryptophane', 'p.S101C': 'Sérine', 'p.L344Q': 'Leucine', 'p.R736C': 'Arginine', 'p.C1273F': 'Cystéine', 'p.G13V': 'Glycine', 'p.P851fs*22': 'Proline', 'p.V220M': 'Valine', 'p.F1043fs*6': 'Phénylalanine', 'p.L1046fs*9': 'Leucine', 'p.F1300C': 'Phénylalanine', 'p.D155fs*2': 'Acide aspartique', 'p.K666N': 'Lysine', 'p.G1590fs*24': 'Glycine', 'p.K1516fs*3': 'Lysine', 'p.S315fs*33': 'Sérine', 'p.W327*': 'Tryptophane', 'p.Q1825*': 'Glutamine', 'p.E705fs*20': 'Acide glutamique', 'p.F331Y': 'Phénylalanine', 'p.Q317fs*30': 'Glutamine', 'p.C1289S': 'Cystéine', 'p.R273C': 'Arginine', 'p.T395fs*32': 'Thréonine', 'p.L862V': 'Leucine', 'p.L179fs*60': 'Leucine', 'p.Q588fs*29': 'Glutamine', 'p.E365*': 'Acide glutamique', 'p.A59H': 'Alanine', 'p.R259*': 'Arginine', 'p.I234fs*2': 'Isoleucine', 'p.P1367S': 'Proline', 'p.R172N': 'Arginine', 'p.S958*': 'Sérine', 'p.P95_H99delPPDSH': 'Proline', 'p.L329delL': 'Leucine', 'p.G643fs*15': 'Glycine', 'p.Y65fs*45': 'Tyrosine', 'p.E645K': 'Acide glutamique', 'p.E2fs*27': 'Acide glutamique', 'p.P384fs*215': 'Proline', 'p.C88*': 'Cystéine', 'p.A716fs*9': 'Alanine', 'p.L161fs*51': 'Leucine', 'p.H193R': 'Histidine', 'p.I833V': 'Isoleucine', 'p.Y1618*': 'Tyrosine', 'p.P499fs*47': 'Proline', 'p.I679fs*21': 'Isoleucine', 'p.G787fs*26': 'Glycine', 'p.S770L': 'Sérine', 'p.R72fs*66': 'Arginine', 'p.D93Y': 'Acide aspartique', 'p.D868Y': 'Acide aspartique', 'p.P278R': 'Proline', 'p.C381R': 'Cystéine', 'p.Q63*': 'Glutamine', 'p.I1163fs*63': 'Isoleucine', 'p.M629fs*20': 'Méthionine', 'p.P278S': 'Proline', 'p.F396fs*205': 'Phénylalanine', 'p.A871T': 'Alanine', 'p.Q1624*': 'Glutamine', 'p.A59G': 'Alanine', 'p.L432fs*16': 'Leucine', 'p.G628fs*48': 'Glycine', 'p.H398Y': 'Histidine', 'p.G1275A': 'Glycine', 'p.Q771R': 'Glutamine', 'p.P628fs*22': 'Proline', 'p.A286T': 'Alanine', 'p.N260fs*1': 'Asparagine', 'p.A68fs*70': 'Alanine', 'p.V665L': 'Valine', 'p.P321L': 'Proline', 'p.S420*': 'Sérine', 'p.F368L': 'Phénylalanine', 'p.W1182*': 'Tryptophane', 'p.R625C': 'Arginine', 'p.K111fs*2': 'Lysine', 'p.D1113fs*17': 'Acide aspartique', 'p.D745fs*27': 'Acide aspartique', 'p.R166Q': 'Arginine', 'p.G251E': 'Glycine', 'p.E1137fs*15': 'Acide glutamique', 'p.R604*': 'Arginine', 'p.H717fs*6': 'Histidine', 'p.A787V': 'Alanine', 'p.P395H': 'Proline', 'p.M317delM': 'Méthionine', 'p.R319*': 'Arginine', 'p.P799R': 'Proline', 'p.Y322S': 'Tyrosine', 'p.P96T': 'Proline', 'p.G60D': 'Glycine', 'p.P452fs*25': 'Proline', 'p.Q179*': 'Glutamine', 'p.E208Q': 'Acide glutamique', 'p.M151fs*2': 'Méthionine', 'p.Q373*': 'Glutamine', 'p.K793fs*24': 'Lysine', 'p.A972V': 'Alanine', 'p.R1547*': 'Arginine', 'p.Y248delins*': 'Tyrosine', 'p.H502fs*9': 'Histidine', 'p.T606M': 'Thréonine', 'p.V1864fs*23': 'Valine', 'p.S87fs*12': 'Sérine', 'p.K901*': 'Lysine', 'p.H990fs*17': 'Histidine', 'p.A658*': 'Alanine', 'p.F909S': 'Phénylalanine', 'p.N139K': 'Asparagine', 'p.R844C': 'Arginine', 'p.R430*': 'Arginine', 'p.M3389fs*32': 'Méthionine', 'p.R158P': 'Arginine', 'p.E395*': 'Acide glutamique', 'p.Q392fs*208': 'Glutamine', 'p.R544*': 'Arginine', 'p.E287fs*58': 'Acide glutamique', 'p.Q2147*': 'Glutamine', 'p.V1900_Y1902delVFYinsH': 'Valine', 'p.G165fs*12': 'Glycine', 'p.S127Y': 'Sérine', 'p.D816V': 'Acide aspartique', 'p.H1868D': 'Histidine', 'p.Q361*': 'Glutamine', 'p.N198fs*1': 'Asparagine', 'p.E76V': 'Acide glutamique', 'p.R354fs*8': 'Arginine', 'p.G686V': 'Glycine', 'p.I146fs*2': 'Isoleucine', 'p.Y1279*': 'Tyrosine', 'p.G989fs*6': 'Glycine', 'p.R1896G': 'Arginine', 'p.E797*': 'Acide glutamique', 'p.Y64D': 'Tyrosine', 'p.Y414fs*186': 'Tyrosine', 'p.Q1524*': 'Glutamine', 'p.T227A': 'Thréonine', 'p.Y701*': 'Tyrosine', 'p.R1261C': 'Arginine', 'p.E537fs*30': 'Acide glutamique', 'p.R162T': 'Arginine', 'p.T178fs*34': 'Thréonine', 'p.S388N': 'Sérine', 'p.R659G': 'Arginine', 'p.A159P': 'Alanine', 'p.R339P': 'Arginine', 'p.A147fs*13': 'Alanine', 'p.S82fs*2': 'Sérine', 'p.T377fs*73': 'Thréonine', 'p.C478*': 'Cystéine', 'p.S131fs*78': 'Sérine', 'p.T529fs*12': 'Thréonine', 'p.S469fs*132': 'Sérine', 'p.R63*': 'Arginine', 'p.Y355fs*245': 'Tyrosine', 'p.S604P': 'Sérine', 'p.K912*': 'Lysine', 'p.I281fs*3': 'Isoleucine', 'p.A338fs*262': 'Alanine', 'p.R710Q': 'Arginine', 'p.C396Y': 'Cystéine', 'p.D868G': 'Acide aspartique', 'p.I621fs*15': 'Isoleucine', 'p.G135R': 'Glycine', 'p.Y340N': 'Tyrosine', 'p.F776fs*37': 'Phénylalanine', 'p.D614Y': 'Acide aspartique', 'p.R2396*': 'Arginine', 'p.S799fs*4': 'Sérine', 'p.C1396W': 'Cystéine', 'p.H191R': 'Histidine', 'p.L992fs*2': 'Leucine', 'p.A1341P': 'Alanine', 'p.V1199fs*27': 'Valine', 'p.E5434K': 'Acide glutamique', 'p.K663R': 'Lysine', 'p.K98fs*10': 'Lysine', 'p.A620V': 'Alanine', 'p.G1223V': 'Glycine', 'p.Q1654fs*6': 'Glutamine', 'p.L815V': 'Leucine', 'p.G1275R': 'Glycine', 'p.R1359C': 'Arginine', 'p.W130*': 'Tryptophane', 'p.A1331T': 'Alanine', 'p.L477fs*51': 'Leucine', 'p.L2711fs*28': 'Leucine', 'p.R250fs*5': 'Arginine', 'p.R506*': 'Arginine', 'p.T377N': 'Thréonine', 'p.W495*': 'Tryptophane', 'p.R201Q': 'Arginine', 'p.M1226fs*4': 'Méthionine', 'p.R580*': 'Arginine', 'p.G245S': 'Glycine', 'p.Y1902fs*6': 'Tyrosine', 'p.C181R': 'Cystéine', 'p.Y666*': 'Tyrosine', 'p.L597*': 'Leucine', 'p.C22*': 'Cystéine', 'p.F212fs*3': 'Phénylalanine', 'p.H135fs*74': 'Histidine', 'p.P282fs*33': 'Proline', 'p.E1344fs*22': 'Acide glutamique', 'p.Q780*': 'Glutamine', 'p.R1306Q': 'Arginine', 'p.T1112fs*6': 'Thréonine', 'p.G412fs*182': 'Glycine', 'p.Q61H': 'Glutamine', 'p.E159Q': 'Acide glutamique', 'p.E858K': 'Acide glutamique', 'p.S1101fs*4': 'Sérine', 'p.S1054*': 'Sérine', 'p.Q835*': 'Glutamine', 'p.L1210fs*8': 'Leucine', 'p.R105G': 'Arginine', 'p.L1872delL': 'Leucine', 'p.N1484fs*87': 'Asparagine', 'p.S451F': 'Sérine', 'p.K110T': 'Lysine', 'p.K1206*': 'Lysine', 'p.G740V': 'Glycine', 'p.P2514fs*4': 'Proline', 'p.C549Y': 'Cystéine', 'p.L565fs*86': 'Leucine', 'p.F396fs*204': 'Phénylalanine', 'p.N243_T244insN': 'Asparagine', 'p.W515L': 'Tryptophane', 'p.H922fs*31': 'Histidine', 'p.F1429fs*19': 'Phénylalanine', 'p.L1740*': 'Leucine', 'p.G354fs*>135': 'Glycine', 'p.A113fs*86': 'Alanine', 'p.V469fs*5': 'Valine', 'p.V1900delV': 'Valine', 'p.C594fs*25': 'Cystéine', 'p.I146T': 'Isoleucine', 'p.L765fs*7': 'Leucine', 'p.A1189fs*4': 'Alanine', 'p.E472*': 'Acide glutamique', 'p.I254N': 'Isoleucine', 'p.C381A': 'Cystéine', 'p.Q302*': 'Glutamine', 'p.L153fs*4': 'Leucine', 'p.A1166fs*56': 'Alanine', 'p.P214L': 'Proline', 'p.C1164Y': 'Cystéine', 'p.N676T': 'Asparagine', 'p.F868L': 'Phénylalanine', 'p.L952fs*20': 'Leucine', 'p.Q255fs*12': 'Glutamine', 'p.R518*': 'Arginine', 'p.C172Y': 'Cystéine', 'p.E790fs*1': 'Acide glutamique', 'p.F732C': 'Phénylalanine', 'p.R313W': 'Arginine', 'p.S100P': 'Sérine', 'p.S364fs*6': 'Sérine', 'p.C1211Y': 'Cystéine', 'p.N1156I': 'Asparagine', 'p.N1154S': 'Asparagine', 'p.S66fs*15': 'Sérine', 'p.P107fs*16': 'Proline', 'p.W75*': 'Tryptophane', 'p.E98G': 'Acide glutamique', 'p.A1505T': 'Alanine', 'p.E393D': 'Acide glutamique', 'p.L405_T406insCL': 'Leucine', 'p.E76G': 'Acide glutamique', 'p.R1012*': 'Arginine', 'p.N1524fs*45': 'Asparagine', 'p.R326C': 'Arginine', 'p.A159V': 'Alanine', 'p.W898fs*10': 'Tryptophane', 'p.G12A': 'Glycine', 'p.G645fs*55': 'Glycine', 'p.E1144V': 'Acide glutamique', 'p.G1370E': 'Glycine', 'p.N248fs*11': 'Asparagine', 'p.N830fs*9': 'Asparagine', 'p.C1211fs*14': 'Cystéine', 'p.F113C': 'Phénylalanine', 'p.E1402*': 'Acide glutamique', 'p.K406fs*17': 'Lysine', 'p.W515S': 'Tryptophane', 'p.Q860*': 'Glutamine', 'p.Q157P': 'Glutamine', 'p.H355fs*52': 'Histidine', 'p.Q778fs*10': 'Glutamine', 'p.R881fs*40': 'Arginine', 'p.R101*': 'Arginine', 'p.V1454I': 'Valine', 'p.V502fs*44': 'Valine', 'p.Y138fs*32': 'Tyrosine', 'p.S577*': 'Sérine', 'p.R701C': 'Arginine', 'p.C1711fs*5': 'Cystéine', 'p.K1173fs*1': 'Lysine', 'p.P1722fs*23': 'Proline', 'p.E89fs*19': 'Acide glutamique', 'p.P257fs*8': 'Proline', 'p.P580delP': 'Proline', 'p.C1095*': 'Cystéine', 'p.S1039fs*2': 'Sérine', 'p.Q958*': 'Glutamine', 'p.K740*': 'Lysine', 'p.S949*': 'Sérine', 'p.G503E': 'Glycine', 'p.S669R': 'Sérine', 'p.R1617Q': 'Arginine', 'p.F116C': 'Phénylalanine', 'p.Q933*': 'Glutamine', 'p.P531A': 'Proline', 'p.F1104fs*3': 'Phénylalanine', 'p.T62fs*25': 'Thréonine', 'p.H1380P': 'Histidine', 'p.G220R': 'Glycine', 'p.Q1157*': 'Glutamine', 'p.Q623fs*9': 'Glutamine', 'p.C632fs*15': 'Cystéine', 'p.G50fs*4': 'Glycine', 'p.Y638C': 'Tyrosine', 'p.I292fs*24': 'Isoleucine', 'p.L513fs*6': 'Leucine', 'p.L257V': 'Leucine', 'p.T940fs*13': 'Thréonine', 'p.V45L': 'Valine', 'p.D1598V': 'Acide aspartique', 'p.Q963*': 'Glutamine', 'p.S708*': 'Sérine', 'p.G375R': 'Glycine', 'p.V386fs*7': 'Valine', 'p.R1362*': 'Arginine', 'p.Q548*': 'Glutamine', 'p.Q1390*': 'Glutamine', 'p.A235fs*1': 'Alanine', 'p.A72S': 'Alanine', 'p.Q776*': 'Glutamine', 'p.W795*': 'Tryptophane', 'p.F534fs*5': 'Phénylalanine', 'p.Q652*': 'Glutamine', 'p.G685W': 'Glycine', 'p.G375V': 'Glycine', 'p.C176R': 'Cystéine', 'p.G728D': 'Glycine', 'p.R1213*': 'Arginine', 'p.A1196fs*2': 'Alanine', 'p.D594G': 'Acide aspartique', 'p.E733K': 'Acide glutamique', 'p.G1361S': 'Glycine', 'p.Y301*': 'Tyrosine', 'p.P530fs*9': 'Proline', 'p.T1280fs*83': 'Thréonine', 'p.A142fs*4': 'Alanine', 'p.H214R': 'Histidine', 'p.F751fs*28': 'Phénylalanine', 'p.R1272*': 'Arginine', 'p.P75R': 'Proline', 'p.S1497fs*7': 'Sérine', 'p.R784L': 'Arginine', 'p.Q1937*': 'Glutamine', 'p.C419Y': 'Cystéine', 'p.A382fs*6': 'Alanine', 'p.V81fs*57': 'Valine', 'p.A380T': 'Alanine', 'p.Y1733fs*8': 'Tyrosine', 'p.S381fs*8': 'Sérine', 'p.V430fs*1': 'Valine', 'p.L1209R': 'Leucine', 'p.G1288S': 'Glycine', 'p.K1785*': 'Lysine', 'p.L757fs*12': 'Leucine', 'p.E798*': 'Acide glutamique', 'p.F1309L': 'Phénylalanine', 'p.A1159_I1160delinsV': 'Alanine', 'p.A377V': 'Alanine', 'p.R807H': 'Arginine', 'p.G413S': 'Glycine', 'p.S471fs*23': 'Sérine', 'p.Q615*': 'Glutamine', 'p.I1689fs*36': 'Isoleucine', 'p.N58Y': 'Asparagine', 'p.Q367P': 'Glutamine', 'p.Y1552fs*17': 'Tyrosine', 'p.K20fs*28': 'Lysine', 'p.L1151_G1152insE': 'Leucine', 'p.R1223Q': 'Arginine', 'p.C396F': 'Cystéine', 'p.A187_T188delAT': 'Alanine', 'p.K685Q': 'Lysine', 'p.P250L': 'Proline', 'p.E902*': 'Acide glutamique', 'p.R586W': 'Arginine', 'p.G229fs*47': 'Glycine', 'p.Q174*': 'Glutamine', 'p.Q1034*': 'Glutamine', 'p.C1298R': 'Cystéine', 'p.Y1693*': 'Tyrosine', 'p.Q1507*': 'Glutamine', 'p.Q688*': 'Glutamine', 'p.P1644fs*51': 'Proline', 'p.H762fs*51': 'Histidine', 'p.E733fs*8': 'Acide glutamique', 'p.L419fs*13': 'Leucine', 'p.R265Q': 'Arginine', 'p.P103S': 'Proline', 'p.L144fs*14': 'Leucine', 'p.K2733fs*6': 'Lysine', 'p.I254S': 'Isoleucine', 'p.Q967*': 'Glutamine', 'p.Y1015fs*7': 'Tyrosine', 'p.W629fs*46': 'Tryptophane', 'p.R418S

In [140]:
# KMT2A => MLL PTD => Lysine 
# FLT3-ID => FLT3 => tyrosine

acide_aminee["MLL_PTD"] = "Lysine"
acide_aminee["FLT3_ITD"] = "Tyrosine"
acide_aminee["p.?"] = "Unknown"

In [141]:
mol_df = mol_df.with_columns(
    pl.col("PROTEIN_CHANGE").map_elements(lambda x: acide_aminee.get(x, None)).alias("AA_TYPE")
)

C:\Users\zakar\AppData\Local\Temp\ipykernel_16716\1629844449.py:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  mol_df = mol_df.with_columns(

In [142]:
mol_df["AA_TYPE"].value_counts()

shape: (22, 2)
┌──────────────────┬───────┐
│ AA_TYPE          ┆ count │
│ ---              ┆ ---   │
│ str              ┆ u32   │
╞══════════════════╪═══════╡
│ null             ┆ 16    │
│ Tryptophane      ┆ 255   │
│ Lysine           ┆ 904   │
│ Glutamine        ┆ 783   │
│ Acide aspartique ┆ 339   │
│ …                ┆ …     │
│ Valine           ┆ 318   │
│ Phénylalanine    ┆ 165   │
│ Thréonine        ┆ 267   │
│ Unknown          ┆ 529   │
│ Histidine        ┆ 272   │
└──────────────────┴───────┘

In [143]:
mol_df.filter(pl.col("AA_TYPE").is_null())['PROTEIN_CHANGE'].value_counts()

shape: (5, 2)
┌────────────────┬───────┐
│ PROTEIN_CHANGE ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ p.*342S        ┆ 1     │
│ null           ┆ 12    │
│ p.*636W        ┆ 1     │
│ p.*636C        ┆ 1     │
│ p.*342*        ┆ 1     │
└────────────────┴───────┘

In [144]:

protein_remove = ["p.*636C"	 , "p.*342*" , "p.*342S" , "p.*636W" ]

for elem in protein_remove:
    mol_df = mol_df.remove(pl.col("PROTEIN_CHANGE") == elem)

In [145]:
mol_df.filter(pl.col("AA_TYPE").is_null())['PROTEIN_CHANGE'].value_counts()

shape: (1, 2)
┌────────────────┬───────┐
│ PROTEIN_CHANGE ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ null           ┆ 12    │
└────────────────┴───────┘

In [146]:
mol_df = mol_df.drop_nulls(subset="PROTEIN_CHANGE")

In [147]:
mol_df.filter(pl.col("AA_TYPE").is_null())['PROTEIN_CHANGE'].value_counts()

shape: (0, 2)
┌────────────────┬───────┐
│ PROTEIN_CHANGE ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
└────────────────┴───────┘

In [148]:
mol_df = mol_df.with_columns(
    pl.when(pl.col("PROTEIN_CHANGE") == "p.?")
    .then(1)
    .otherwise(0)
    .alias("IS_PT_UKNOWN")
)

In [149]:
import category_encoders as ce

mol_df_pd = mol_df.to_pandas()

encoder = ce.BinaryEncoder(cols=["AA_TYPE"])
mol_df = encoder.fit_transform(mol_df_pd)



mol_df = pl.from_pandas(mol_df)

mol_df

shape: (10_919, 144)
┌─────────┬──────┬─────────────┬─────────────┬───┬───────────┬───────────┬───────────┬─────────────┐
│ ID      ┆ CHR  ┆ START       ┆ END         ┆ … ┆ AA_TYPE_2 ┆ AA_TYPE_3 ┆ AA_TYPE_4 ┆ IS_PT_UKNOW │
│ ---     ┆ ---  ┆ ---         ┆ ---         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ N           │
│ str     ┆ f64  ┆ f64         ┆ f64         ┆   ┆ i64       ┆ i64       ┆ i64       ┆ ---         │
│         ┆      ┆             ┆             ┆   ┆           ┆           ┆           ┆ i32         │
╞═════════╪══════╪═════════════╪═════════════╪═══╪═══════════╪═══════════╪═══════════╪═════════════╡
│ P100000 ┆ 11.0 ┆ 1.19149248e ┆ 1.19149248e ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 0           │
│         ┆      ┆ 8           ┆ 8           ┆   ┆           ┆           ┆           ┆             │
│ P100000 ┆ 5.0  ┆ 1.31822301e ┆ 1.31822301e ┆ … ┆ 0         ┆ 1         ┆ 0         ┆ 0           │
│         ┆      ┆ 8           ┆ 8           ┆   ┆           ┆           ┆           ┆             │
│ P100000 ┆ 3.0  ┆ 7.769406e7  ┆ 7.769406e7  ┆ … ┆ 0         ┆ 1         ┆ 1         ┆ 1           │
│ P100000 ┆ 4.0  ┆ 1.06164917e ┆ 1.06164917e ┆ … ┆ 1         ┆ 0         ┆ 0         ┆ 0           │
│         ┆      ┆ 8           ┆ 8           ┆   ┆           ┆           ┆           ┆             │
│ P100000 ┆ 2.0  ┆ 2.5468147e7 ┆ 2.5468163e7 ┆ … ┆ 1         ┆ 0         ┆ 1         ┆ 0           │
│ …       ┆ …    ┆ …           ┆ …           ┆ … ┆ …         ┆ …         ┆ …         ┆ …           │
│ P131472 ┆ 3.0  ┆ 7.9008e7    ┆ 7.9009e7    ┆ … ┆ 1         ┆ 1         ┆ 0         ┆ 0           │
│ P131505 ┆ 3.0  ┆ 7.9008e7    ┆ 7.9009e7    ┆ … ┆ 1         ┆ 1         ┆ 0         ┆ 0           │
│ P131816 ┆ 3.0  ┆ 7.9008e7    ┆ 7.9009e7    ┆ … ┆ 1         ┆ 1         ┆ 0         ┆ 0           │
│ P132717 ┆ 3.0  ┆ 7.9008e7    ┆ 7.9009e7    ┆ … ┆ 1         ┆ 1         ┆ 0         ┆ 0           │
│ P132724 ┆ 3.0  ┆ 7.9008e7    ┆ 7.9009e7    ┆ … ┆ 1         ┆ 1         ┆ 0         ┆ 0           │
└─────────┴──────┴─────────────┴─────────────┴───┴───────────┴───────────┴───────────┴─────────────┘

In [150]:
# Frameshift : a sequence change between the translation initiation (start) and termination (stop) codon where, compared to a reference sequence, 
# translation shifts to another reading frame.


# FrameShift protein_change
for elem in protein_change:
    if elem is not None and 'fs' in elem:
        print(elem)
        
mol_df = mol_df.with_columns(
    pl.when(pl.col("PROTEIN_CHANGE").str.contains('fs'))
    .then(1)
    .otherwise(0)
    .alias("is_frameshift")
)

p.R1878fs*2
p.D2064fs*38
p.T590fs*29
p.S327fs*4
p.S1598fs*28
p.N460fs*5
p.L98fs*24
p.N253fs*41
p.G422fs*5
p.V371fs*18
p.V360fs*234
p.R174fs*4
p.S206fs*1
p.Y2285fs*1
p.V509fs*14
p.A858fs*29
p.L546fs*1
p.M725fs*16
p.R370fs*7
p.I451fs*2
p.R169fs*56
p.P1496fs*75
p.P489fs*40
p.R198fs*8
p.V116fs*28
p.E143fs*2
p.K291fs*18
p.F468fs*5
p.C407fs*2
p.E227fs*1
p.R450fs*20
p.Y355fs*1
p.S1431fs*17
p.P442fs*16
p.E513fs*16
p.K228fs*25
p.D1412fs*12
p.Q1117fs*18
p.L85fs*28
p.E343fs*2
p.G170fs*7
p.L1418fs*7
p.S121fs*2
p.T1085fs*19
p.D596fs*1
p.E1128fs*7
p.R15fs*82
p.F158fs*18
p.D563fs*13
p.L1413fs*83
p.E476fs*7
p.N492fs*9
p.Q769fs*44
p.R380fs*72
p.G870fs*38
p.S1059fs*1
p.K618fs*1
p.V238fs*16
p.D123fs*11
p.Q289fs*11
p.N405fs*21
p.Q269fs*12
p.F183fs*23
p.S825fs*1
p.P250fs*3
p.S336fs*45
p.D1635fs*5
p.L743fs*57
p.N1573fs*6
p.H839fs*2
p.F1104fs*2
p.Q2230fs*114
p.N1504fs*67
p.S597fs*41
p.R103fs*9
p.A640fs*14
p.I254fs*32
p.L335fs*69
p.I1897fs*11
p.D1152fs*14
p.S1982fs*30
p.E773fs*12
p.V360fs*239
p.E294fs*22
p.E109fs*56
p.I1139fs*13
p.L1515fs*56
p.R107fs*30
p.P153fs*28
p.L158fs*3
p.R334fs*266
p.G1590fs*6
p.A571fs*5
p.H1150fs*1
p.S2816fs*6
p.H1727fs*18
p.N587fs*1
p.I410fs*46
p.Q705fs*7
p.S1601fs*9
p.E1265fs*54
p.L1872fs*3
p.V2306fs*2
p.S424fs*19
p.M371fs*229
p.V1199fs*16
p.A671fs*29
p.E420fs*36
p.K62fs*16
p.Y65fs*46
p.M904fs*2
p.A809fs*13
p.V1446fs*2
p.E1437fs*11
p.P479fs*7
p.A1810fs*10
p.S665fs*1
p.E1918fs*15
p.D2283fs*9
p.T738fs*48
p.N857fs*15
p.R625fs*12
p.I921fs*32
p.Q7fs*4
p.D527fs*6
p.Y103fs*1
p.S172fs*4
p.S805fs*50
p.A51fs*36
p.R191fs*21
p.Q591fs*10
p.Q623fs*7
p.E728fs*16
p.C1164fs*63
p.P274fs*8
p.S139fs*14
p.P390fs*32
p.Y636fs*1
p.L146fs*14
p.P1108fs*22
p.E219fs*5
p.Y1245fs*21
p.H573fs*7
p.K1877fs*10
p.N837fs*1
p.S340fs*37
p.F1706fs*5
p.K227fs*52
p.P1232fs*7
p.F180fs*31
p.I705fs*74
p.H1150fs*2
p.R1007fs*63
p.A324fs*276
p.S2090fs*1
p.P851fs*22
p.F1043fs*6
p.L1046fs*9
p.D155fs*2
p.G1590fs*24
p.K1516fs*3
p.S315fs*33
p.E705fs*20
p.Q317fs*30
p.T395fs*32
p.L179fs*60
p.Q588fs*29
p.I234fs*2
p.G643fs*15
p.Y65fs*45
p.E2fs*27
p.P384fs*215
p.A716fs*9
p.L161fs*51
p.P499fs*47
p.I679fs*21
p.G787fs*26
p.R72fs*66
p.I1163fs*63
p.M629fs*20
p.F396fs*205
p.L432fs*16
p.G628fs*48
p.P628fs*22
p.N260fs*1
p.A68fs*70
p.K111fs*2
p.D1113fs*17
p.D745fs*27
p.E1137fs*15
p.H717fs*6
p.P452fs*25
p.M151fs*2
p.K793fs*24
p.H502fs*9
p.V1864fs*23
p.S87fs*12
p.H990fs*17
p.M3389fs*32
p.Q392fs*208
p.E287fs*58
p.G165fs*12
p.N198fs*1
p.R354fs*8
p.I146fs*2
p.G989fs*6
p.Y414fs*186
p.E537fs*30
p.T178fs*34
p.A147fs*13
p.S82fs*2
p.T377fs*73
p.S131fs*78
p.T529fs*12
p.S469fs*132
p.Y355fs*245
p.I281fs*3
p.A338fs*262
p.I621fs*15
p.F776fs*37
p.S799fs*4
p.L992fs*2
p.V1199fs*27
p.K98fs*10
p.Q1654fs*6
p.L477fs*51
p.L2711fs*28
p.R250fs*5
p.M1226fs*4
p.Y1902fs*6
p.F212fs*3
p.H135fs*74
p.P282fs*33
p.E1344fs*22
p.T1112fs*6
p.G412fs*182
p.S1101fs*4
p.L1210fs*8
p.N1484fs*87
p.P2514fs*4
p.L565fs*86
p.F396fs*204
p.H922fs*31
p.F1429fs*19
p.G354fs*>135
p.A113fs*86
p.V469fs*5
p.C594fs*25
p.L765fs*7
p.A1189fs*4
p.L153fs*4
p.A1166fs*56
p.L952fs*20
p.Q255fs*12
p.E790fs*1
p.S364fs*6
p.S66fs*15
p.P107fs*16
p.N1524fs*45
p.W898fs*10
p.G645fs*55
p.N248fs*11
p.N830fs*9
p.C1211fs*14
p.K406fs*17
p.H355fs*52
p.Q778fs*10
p.R881fs*40
p.V502fs*44
p.Y138fs*32
p.C1711fs*5
p.K1173fs*1
p.P1722fs*23
p.E89fs*19
p.P257fs*8
p.S1039fs*2
p.F1104fs*3
p.T62fs*25
p.Q623fs*9
p.C632fs*15
p.G50fs*4
p.I292fs*24
p.L513fs*6
p.T940fs*13
p.V386fs*7
p.A235fs*1
p.F534fs*5
p.A1196fs*2
p.P530fs*9
p.T1280fs*83
p.A142fs*4
p.F751fs*28
p.S1497fs*7
p.A382fs*6
p.V81fs*57
p.Y1733fs*8
p.S381fs*8
p.V430fs*1
p.L757fs*12
p.S471fs*23
p.I1689fs*36
p.Y1552fs*17
p.K20fs*28
p.G229fs*47
p.P1644fs*51
p.H762fs*51
p.E733fs*8
p.L419fs*13
p.L144fs*14
p.K2733fs*6
p.Y1015fs*7
p.W629fs*46
p.N501fs*45
p.S791fs*27
p.Q554fs*27
p.T848fs*19
p.V60fs*13
p.T711fs*7
p.C672fs*40
p.C585fs*90
p.D271fs*45
p.G859fs*48
p.N377fs*50
p.S239fs*17
p.Q764fs*5
p.S3fs*4
p.F40fs*14
p.L657fs*49
p.S364fs*55
p.S892fs*2
p.Q847fs*25
p.R7fs*58
p.F1419fs*65
p.R1739fs*1
p.A368fs*39
p.V1743fs*1
p.M1164fs*62
p.L2408fs*14
p.S73fs*49
p.S317fs*9
p.S424fs*3
p.S167fs*4
p.C457fs*5
p.K655fs*45
p.S432fs*4
p.N608fs*31
p.S142fs*4
p.Q232fs*18
p.K102fs*32
p.P531fs*6
p.N801fs*12
p.K389fs*38
p.E733fs*1
p.I342fs*258
p.C296fs*12
p.L992fs*1
p.K206fs*15
p.N528fs*5
p.C1790fs*9
p.K755fs*29
p.Q390fs*212
p.P251fs*21
p.L1899fs*7
p.V1114fs*22
p.Q373fs*15
p.Q19fs*46
p.S2231fs*7
p.P681fs*34
p.G257fs*61
p.A385fs*57
p.T246fs*15
p.R322fs*17
p.V70fs*11
p.V730fs*14
p.S303fs*296
p.Q642fs*58
p.F133fs*76
p.I715fs*19
p.T532fs*7
p.T970fs*37
p.E422fs*175
p.S131fs*23
p.N2305fs*47
p.Q527fs*124
p.S276fs*30
p.A1618fs*56
p.M1050fs*35
p.R766fs*18
p.S689fs*16
p.M1522fs*61
p.H724fs*29
p.V1059fs*3
p.R617fs*21
p.T769fs*3
p.E1178fs*7
p.T1047fs*11
p.C856fs*12
p.V1639fs*45
p.T1007fs*25
p.A996fs*13
p.M1050fs*37
p.I130fs*2
p.P594fs*44
p.M368fs*231
p.V873fs*4
p.Y1255fs*13
p.L215fs*11
p.G36fs*122
p.W288fs*12
p.A277fs*16
p.A952fs*6
p.I822fs*19
p.C124fs*25
p.L225fs*24
p.V101fs*22
p.M749fs*27
p.L89fs*49
p.I193fs*22
p.M1729fs*21
p.M406fs*3
p.F329fs*1
p.F125fs*3
p.A64fs*64
p.T248fs*15
p.N374fs*1
p.G1034fs*45
p.E783fs*30
p.S22fs*11
p.Y1631fs*64
p.P1394fs*102
p.L237fs*1
p.M906fs*15
p.S88fs*14
p.N1524fs*46
p.I62fs*46
p.E772fs*7
p.M347fs*254
p.S276fs*142
p.G643fs*9
p.C992fs*15
p.V253fs*14
p.A258fs*3
p.T92fs*31
p.C1281fs*82
p.E510fs*23
p.P409fs*14
p.F48fs*12
p.Q1687fs*8
p.L1046fs*13
p.P813fs*7
p.N1018fs*11
p.F513fs*57
p.L1515fs*62
p.V36fs*35
p.N403fs*4
p.S314fs*285
p.N292fs*30
p.S971fs*11
p.N423fs*14
p.S293fs*11
p.T1710fs*3
p.A707fs*10
p.P808fs*10
p.L235fs*9
p.M1115fs*21
p.G543fs*18
p.L1514fs*56
p.Y301fs*1
p.N281fs*37
p.V1100fs*5
p.C353fs*2
p.Q960fs*26
p.K1208fs*18
p.L82fs*57
p.H1732fs*9
p.Q696fs*9
p.T1056fs*6
p.S280fs*36
p.E692fs*14
p.L207fs*6
p.T162fs*16
p.G646fs*12
p.L757fs*56
p.I177fs*35
p.H698fs*4
p.E856fs*8
p.R103fs*19
p.D1844fs*2
p.A322fs*4
p.F194fs*6
p.Q731fs*22
p.L1418fs*31
p.D271fs*10
p.T655fs*3
p.S1297fs*75
p.L567fs*14
p.L1418fs*30
p.Q1529fs*42
p.F182fs*15
p.Y491fs*20
p.H2480fs*4
p.L347fs*46
p.L82fs*43
p.D1615fs*14
p.R344fs*6
p.T1248fs*15
p.R110fs*13
p.P1410fs*38
p.V1656fs*16
p.S44fs*13
p.S276fs*141
p.S1853fs*29
p.N2246fs*21
p.H24fs*84
p.S322fs*277
p.C579fs*14
p.T693fs*5
p.Y414fs*27
p.V1461fs*9
p.V626fs*25
p.T1007fs*2
p.E808fs*6
p.A520fs*4
p.P22fs*78
p.E259fs*19
p.M695fs*17
p.R119fs*45
p.T1554fs*16
p.L484fs*2
p.E168fs*7
p.E28fs*14
p.E505fs*141
p.Y1255fs*1
p.T350fs*74
p.S708fs*38
p.N986fs*7
p.E801fs*17
p.D299fs*6
p.D322fs*1
p.A550fs*11
p.R774fs*12
p.L951fs*11
p.T273fs*5
p.Q501fs*77
p.K849fs*6
p.D332fs*264
p.Y240fs*2
p.E261fs*3
p.G387fs*207
p.Y1598fs*12
p.S798fs*2
p.E888fs*10
p.F1419fs*40
p.E150fs*33
p.R620fs*14
p.P277fs*34
p.C730fs*14
p.G669fs*2
p.W796fs*29
p.L625fs*25
p.A1219fs*4
p.E1166fs*60
p.L859fs*22
p.H1386fs*15
p.Y636fs*6
p.S846fs*5
p.P1617fs*6
p.T162fs*52
p.L367fs*46
p.L221fs*44
p.T433fs*7
p.C432fs*166
p.S1551fs*4
p.A382fs*69
p.N842fs*2
p.G744fs*30
p.K1339fs*25
p.N729fs*3
p.E1879fs*13
p.I750fs*62
p.L445fs*179
p.K1491fs*80
p.S532fs*3
p.V1461fs*12
p.N506fs*3
p.Y591fs*1
p.S318fs*283
p.G1189fs*12
p.H1761fs*5
p.G421fs*169
p.E154fs*3
p.E971fs*7
p.W1003fs*4
p.P643fs*6
p.C299fs*4
p.L178fs*2
p.M1869fs*10
p.L831fs*2
p.R137fs*5
p.P1123fs*14
p.S189fs*7
p.L462fs*1
p.Y1618fs*1
p.H1036fs*19
p.H1778fs*43
p.M890fs*3
p.I195fs*17
p.E754fs*59
p.N333fs*18
p.K305fs*10
p.G796fs*15
p.G36fs*67
p.V1006fs*27
p.Y685fs*15
p.D832fs*6
p.H546fs*15
p.F519fs*14
p.V1113fs*9
p.V371fs*5
p.H800fs*13
p.F788fs*6
p.I637fs*28
p.N1823fs*11
p.P920fs*4
p.A40fs*120
p.F640fs*1
p.P678fs*10
p.S331fs*269
p.T1592fs*22
p.T1122fs*8
p.F416fs*185
p.E167fs*3
p.T229fs*21
p.V238fs*15
p.T1585fs*10
p.F330fs*271
p.G856fs*17
p.A382fs*7
p.A2356fs*7
p.A275fs*7
p.N1118fs*19
p.T503fs*42
p.A142fs*6
p.G777fs*4
p.G777fs*5
p.T737fs*4
p.P1410fs*2
p.T1220fs*17
p.G1682fs*20
p.M548fs*97
p.T1069fs*36
p.L57fs*1
p.L210fs*3
p.E131fs*12
p.L431fs*1
p.S1441fs*37
p.R1354fs*46
p.H105fs*33
p.S215fs*1
p.R167fs*67
p.V200fs*10
p.G349fs*23
p.E204fs*43
p.S1369fs*79
p.K500fs*14
p.N260fs*339
p.H1732fs*7
p.M865fs*5
p.G130fs*23
p.L129fs*13
p.A84fs*112
p.E219fs*4
p.V1297fs*32
p.F1289fs*1
p.Q1654fs*7
p.S315fs*31
p.V662fs*13
p.V48fs*1
p.R1451fs*7
p.I162fs*19
p.N1845fs*122
p.K1439fs*9
p.C186fs*45
p.S247fs*7
p.A309fs*21
p.Y1044fs*1
p.R380fs*5
p.V1862fs*25
p.S348fs*75
p.I307fs*4
p.Y355fs*3
p.T229fs*25
p.H404fs*197
p.V101fs*21
p.T1331fs*32
p.Y121fs*15
p.W608fs*11
p.R528fs*11
p.V172fs*2
p.A912fs*9
p.H1148fs*12
p.C784fs*5
p.I652fs*9
p.I855fs*18
p.K2525fs*1
p.A124fs*35
p.A470fs*131
p.F1600fs*18
p.F1210fs*7
p.E820fs*5
p.I824fs*2
p.P400fs*28
p.C332fs*15
p.V388fs*6
p.Q958fs*13
p.Y1552fs*3
p.T361fs*237
p.D1858fs*15
p.Y452fs*1
p.L1886fs*6
p.P133fs*10
p.E990fs*6
p.K959fs*48
p.T1985fs*30
p.S519fs*5
p.L1329fs*34
p.N376fs*48
p.Y2285fs*5
p.E1318fs*45
p.Q1360fs*20
p.L436fs*5
p.S672fs*1
p.T477fs*58
p.Y1498fs*1
p.N903fs*21
p.H637fs*5
p.M1575fs*11
p.S729fs*15
p.D658fs*48
p.M695fs*5
p.R655fs*6
p.T944fs*5
p.L412fs*15
p.T174fs*35
p.G387fs*213
p.S70fs*4
p.R376fs*224
p.Q909fs*11
p.H404fs*196
p.V1053fs*35
p.I1937fs*7
p.N575fs*14
p.N202fs*5
p.E1429fs*67
p.T754fs*18
p.L615fs*23
p.C784fs*30
p.Q281fs*22
p.Q129fs*16
p.H1380fs*18
p.Q599fs*2
p.I122fs*7
p.Y327fs*10
p.Y167fs*53
p.P874fs*42
p.A1822fs*11
p.T1809fs*12
p.E1689fs*28
p.C973fs*3
p.Y107fs*1
p.Q171fs*38
p.T1139fs*4
p.N275fs*18
p.S969fs*52
p.C772fs*13
p.I451fs*1
p.Q749fs*2
p.H630fs*4
p.L390fs*21
p.E109fs*52
p.S1448fs*10
p.N66fs*8
p.Q274fs*37
p.D1587fs*9
p.P1181fs*5
p.E278fs*27
p.Y407fs*193
p.G743fs*20
p.S222fs*15
p.A582fs*6
p.Q652fs*48
p.E303fs*49
p.F152fs*32
p.V1100fs*2
p.Q902fs*5
p.H995fs*25
p.S800fs*17
p.G1361fs*3
p.H786fs*27
p.V1639fs*56
p.T849fs*25
p.N699fs*8
p.G644fs*12
p.R606fs*13
p.A186fs*10
p.S362fs*13
p.D855fs*11
p.T1232fs*10
p.R100fs*14
p.P27fs*17
p.R1440fs*38
p.Y1019fs*34
p.I913fs*5
p.A375fs*11
p.Q1726fs*6
p.S356fs*244
p.S301fs*77
p.G199fs*17
p.P184fs*29
p.K1025fs*8
p.F332fs*6
p.L315fs*6
p.N376fs*11
p.G613fs*25
p.Q695fs*22
p.S799fs*12
p.R105fs*17
p.N338fs*2
p.N1204fs*6
p.C973fs*34
p.Y65fs*20
p.C1271fs*29
p.M236fs*25
p.K113fs*15
p.L2007fs*1
p.P1014fs*11
p.Y636fs*15
p.S663fs*27
p.F1104fs*25
p.D515fs*6
p.K385fs*47
p.S989fs*1
p.T1399fs*2
p.R207fs*4
p.Y80fs*27
p.M52fs*28
p.M713fs*12
p.D228fs*18
p.T149fs*33
p.E532fs*47
p.K680fs*25
p.S141fs*4
p.R478fs*118
p.K1180fs*8
p.C640fs*1
p.I227fs*14
p.N202fs*8
p.H717fs*5
p.P127fs*26
p.I2053fs*11
p.H302fs*50
p.S194fs*24
p.D123fs*15
p.A234fs*5
p.P152fs*14
p.N240fs*16
p.Q209fs*109
p.W1847fs*10
p.Y120fs*1
p.G168fs*41
p.A876fs*3
p.C1341fs*28
p.Y1589fs*7
p.I694fs*24
p.K774fs*44
p.L179fs*30
p.V730fs*26
p.E523fs*23
p.P441fs*27
p.D63fs*44
p.D25fs*9
p.P1042fs*5
p.Y74fs*1
p.Q618fs*16
p.L748fs*6
p.L1622fs*1
p.L815fs*7
p.I589fs*13
p.S167fs*15
p.D489fs*18
p.A1328fs*29
p.E856fs*7
p.F1689fs*6
p.S631fs*8
p.E143fs*1
p.N1596fs*14
p.N820fs*17
p.E219fs*31
p.K238fs*12
p.T3500fs*12
p.E475fs*8
p.S321fs*3
p.V118fs*10
p.D1821fs*12
p.D1075fs*1
p.P1249fs*3
p.K751fs*61
p.E396fs*>93
p.C987fs*22
p.L500fs*151
p.L206fs*35
p.P264fs*6
p.S177fs*8
p.L405fs*195
p.L764fs*8
p.T1540fs*4
p.P77fs*34
p.S369fs*19
p.E1025fs*54
p.T132fs*5
p.K1022fs*11
p.T164fs*7
p.V1405fs*19
p.N1778fs*4
p.H125fs*44
p.P1866fs*5
p.I899fs*8
p.E93fs*15
p.F40fs*5
p.L922fs*20
p.E227fs*7
p.S764fs*15
p.I771fs*15
p.Y1245fs*22
p.V818fs*6
p.P725fs*8
p.I294fs*57
p.T196fs*15
p.T128fs*6
p.R182fs*56
p.E1382fs*26
p.Y327fs*9
p.V875fs*2
p.T52fs*7
p.V684fs*21
p.D1331fs*78
p.G738fs*6
p.D269fs*9
p.Q121fs*18
p.F865fs*14
p.R201fs*10
p.S1707fs*6
p.A1471fs*100
p.R693fs*27
p.Y93fs*5
p.R369fs*7
p.N553fs*7
p.I1566fs*9
p.V179fs*32
p.C1707fs*37
p.I597fs*106
p.P204fs*114
p.E711fs*40
p.H1778fs*1
p.L333fs*16
p.S810fs*6
p.F330fs*269
p.V296fs*305
p.A202fs*17
p.Y169fs*40
p.L203fs*3
p.G165fs*13
p.K1417fs*45
p.R903fs*3
p.E1357fs*14
p.L688fs*12
p.P941fs*6
p.R169fs*44
p.T1883fs*9
p.E540fs*7
p.A357fs*50
p.T218fs*8
p.Y1679fs*8
p.Q764fs*49
p.P869fs*3
p.N482fs*3
p.E1020fs*13
p.D282fs*1
p.S1104fs*1
p.P333fs*267
p.A621fs*10
p.R16fs*21
p.S293fs*307
p.Q1534fs*46
p.S218fs*19
p.H1717fs*13
p.N535fs*7
p.E240fs*8
p.Q2301fs*4
p.F365fs*20
p.P1370fs*10
p.T310fs*9
p.G41fs*18
p.P340fs*264
p.H1912fs*9
p.S1099fs*5
p.E504fs*10
p.S271fs*11
p.E113fs*52
p.Q684fs*16
p.S822fs*11
p.H1757fs*6
p.I482fs*17
p.R354fs*13
p.F52fs*2
p.F78fs*15
p.R161fs*7
p.K90fs*20
p.H658fs*22
p.H661fs*37
p.N23fs*10
p.Y1330fs*3
p.P298fs*80
p.P1061fs*5
p.S104fs*15
p.Y974fs*8
p.T81fs*42
p.D162fs*21
p.Q638fs*27
p.L436fs*13
p.G436fs*>53
p.F1168fs*8
p.H995fs*3
p.N139fs*5
p.S145fs*2
p.R113fs*29
p.T1093fs*12
p.Y657fs*1
p.N832fs*34
p.Q831fs*15
p.P938fs*7
p.Q1698fs*46
p.L576fs*127
p.T204fs*26
p.D756fs*11
p.H1792fs*28
p.S936fs*1
p.Q1208fs*8
p.P896fs*10
p.R419fs*115
p.F57fs*11
p.A572fs*2
p.N2340fs*2
p.Q266fs*333
p.K618fs*2
p.L1514fs*57
p.D1252fs*3
p.P267fs*15
p.G685fs*33
p.T170fs*2
p.P294fs*17
p.Q644fs*63
p.L1482fs*89
p.C514fs*137
p.A1341fs*22
p.H990fs*18
p.T246fs*8
p.G194fs*27
p.S381fs*3
p.K1308fs*55
p.E318fs*58
p.Y1783fs*11
p.L184fs*17
p.Y65fs*1
p.P761fs*52
p.C351fs*56
p.I679fs*10
p.K1055fs*3
p.S1096fs*9
p.T395fs*29
p.L43fs*1
p.L941fs*1
p.Y974fs*10
p.A1080fs*24
p.V1101fs*4
p.H1727fs*14
p.Y67fs*12
p.P231fs*6
p.G826fs*12
p.L3113fs*14
p.I68fs*41
p.E149fs*1
p.T898fs*15
p.T329fs*57
p.C1642fs*19
p.S1297fs*29
p.P326fs*51
p.Y89fs*44
p.K630fs*21
p.V371fs*14
p.G325fs*18
p.K1831fs*43
p.P1392fs*104
p.I539fs*4
p.S322fs*278
p.Q1765fs*201
p.Q886fs*20
p.R162fs*49
p.R620fs*15
p.P160fs*24
p.P989fs*18
p.I128fs*79
p.S817fs*7
p.Y380fs*215
p.F73fs*89
p.Y425fs*12
p.H434fs*13
p.K17fs*5
p.L991fs*25
p.W796fs*22
p.G738fs*16
p.K345fs*2
p.A1837fs*50
p.H897fs*7
p.D57fs*66
p.S851fs*5
p.Q71fs*2
p.H242fs*14
p.G800fs*2
p.I144fs*2
p.V1642fs*1
p.S918fs*19
p.T257fs*4
p.E1459fs*18
p.H191fs*130
p.R24fs*9
p.K29fs*26
p.E628fs*10
p.Q180fs*3
p.A746fs*22
p.G46fs*41
p.V141fs*2
p.K777fs*39
p.L112fs*26
p.K110fs*14
p.S227fs*20
p.M930fs*1
p.P499fs*34
p.S450fs*150
p.L855fs*23
p.A1080fs*25
p.P14fs*2
p.R566fs*23
p.E133fs*11
p.I595fs*16
p.T128fs*10
p.N767fs*2
p.H717fs*34
p.R86fs*99
p.P1621fs*53
p.R72fs*67
p.K1208fs*1
p.V876fs*19
p.V287fs*34
p.L1398fs*2
p.L98fs*16
p.R686fs*14
p.L764fs*10
p.A18fs*8
p.E1250fs*11
p.Q745fs*6
p.N374fs*2
p.A329fs*271
p.R369fs*2
p.Q735fs*12
p.N926fs*27
p.N336fs*>153
p.L1312fs*52
p.S77fs*62
p.N5397fs*63
p.N264fs*1
p.S1447fs*115
p.F854fs*19
p.V322fs*5
p.L1375fs*29
p.R1571fs*25
p.P167fs*41
p.Q512fs*9
p.Q1445fs*33
p.C176fs*1
p.G1393fs*103
p.I122fs*22
p.I191fs*15
p.E403fs*9
p.L484fs*1
p.Y1148fs*9
p.K326fs*21
p.Q958fs*14
p.T1114fs*16
p.Q692fs*28
p.G50fs*88
p.N159fs*5
p.D1437fs*16
p.Q177fs*25
p.Q83fs*77
p.V314fs*8
p.C677fs*23
p.F548fs*2
p.M1333fs*6
p.R165fs*10
p.H1036fs*7
p.E1178fs*9
p.T549fs*12
p.L2285fs*37
p.P737fs*33
p.I364fs*231
p.M15fs*91
p.R1026fs*7
p.T270fs*40
p.C915fs*16
p.I790fs*4
p.T347fs*31
p.L482fs*2
p.D863fs*4
p.G645fs*13
p.D137fs*5
p.V1900fs*4
p.L1996fs*51
p.Q622fs*17
p.Q1170fs*56
p.P899fs*8
p.E1165fs*62
p.E1411fs*37
p.V1227fs*15
p.D51fs*75
p.T596fs*18
p.A1685fs*32
p.Q172fs*152
p.P624fs*27
p.R1095fs*1
p.R369fs*16
p.R399fs*26
p.D140fs*2
p.W91fs*32
p.G122fs*16
p.L532fs*30
p.K755fs*7
p.R27fs*11
p.P1278fs*18
p.R346fs*254
p.S1310fs*59
p.R147fs*50
p.K459fs*192
p.P137fs*8
p.F710fs*7
p.L624fs*24
p.P125fs*8
p.R397fs*>92
p.R338fs*71
p.E316fs*283
p.P319fs*28
p.N2517fs*138
p.W581fs*70
p.S48fs*105
p.E906fs*3
p.S924fs*41
p.D1136fs*10
p.M1742fs*18
p.L461fs*19
p.N598fs*3
p.H682fs*9
p.E420fs*35
p.I486fs*2
p.D690fs*25
p.I1092fs*39
p.E719fs*6
p.M906fs*18
p.P647fs*9
p.K118fs*25
p.L329fs*10
p.E547fs*27
p.E421fs*22
p.A912fs*10
p.G143fs*4
p.E947fs*4
p.L513fs*9
p.Q1328fs*41
p.K382fs*25
p.I1024fs*13
p.R1179fs*7
p.F293fs*10
p.N1309fs*20
p.L31fs*3
p.A481fs*2
p.Y1579fs*17
p.P264fs*53
p.T1867fs*16
p.L193fs*1
p.I2221fs*3
p.L1740fs*5
p.S355fs*30
p.P347fs*3
p.I366fs*231
p.R403fs*>86
p.Q891fs*10
p.H137fs*20
p.E1643fs*34
p.P1038fs*14
p.L312fs*21
p.V232fs*86
p.P1568fs*11
p.D1856fs*3
p.A274fs*48
p.L791fs*4
p.F82fs*80
p.S53fs*84
p.P732fs*19
p.S1424fs*24
p.P1013fs*20
p.N560fs*115
p.I751fs*25
p.S436fs*170
p.T425fs*2
p.Y631fs*>5
p.G179fs*59
p.Q744fs*3
p.P537fs*55
p.L360fs*9
p.D107fs*54
p.G680fs*38
p.P1115fs*2
p.L101fs*24
p.I183fs*58
p.Q793fs*7
p.N811fs*11
p.F768fs*17
p.A671fs*6
p.F224fs*17
p.T979fs*19
p.E523fs*25
p.L156fs*28
p.I273fs*326
p.G1620fs*38
p.G168fs*40
p.R1161fs*13
p.T946fs*7
p.C1464fs*6
p.P985fs*18
p.Q1534fs*44
p.S265fs*335
p.S325fs*17
p.S714fs*37
p.E120fs*24
p.L686fs*2
p.S1050fs*6
p.R603fs*14
p.I109fs*1
p.H329fs*22
p.N311fs*34
p.E50fs*58
p.H1676fs*19
p.V99fs*2
p.N648fs*14
p.M1200fs*4
p.F760fs*8
p.P332fs*30
p.S44fs*81
p.E194fs*12
p.V453fs*145
p.L595fs*16
p.R1896fs*12
p.P483fs*48
p.T639fs*14
p.Y2285fs*21
p.Y502fs*1
p.G114fs*5
p.E862fs*45
p.P530fs*13
p.P480fs*6
p.P681fs*54
p.Y1598fs*17
p.T579fs*7
p.G649fs*9
p.F868fs*13
p.T323fs*278
p.A627fs*8
p.T1183fs*3
p.V151fs*10
p.I2304fs*2
p.Y779fs*1
p.E1267fs*1
p.L32fs*4
p.A636fs*22
p.Q1433fs*51
p.D730fs*1
p.G520fs*13
p.N139fs*8
p.T754fs*31
p.T551fs*2
p.Q962fs*45
p.N1888fs*1
p.L1229fs*12
p.S1518fs*1
p.G868fs*10
p.E628fs*11
p.L1621fs*2
p.M521fs*1
p.P1061fs*7
p.T1566fs*5
p.T477fs*20
p.I272fs*2
p.Y1245fs*1
p.S1760fs*6
p.R995fs*8
p.R139fs*19
p.Y248fs*2
p.T45fs*3
p.Y346fs*55
p.T503fs*43
p.S1143fs*16
p.I90fs*12
p.N360fs*34
p.S407fs*36
p.S846fs*21
p.L1067fs*12
p.A584fs*17
p.E401fs*22
p.S1691fs*4
p.Q591fs*8
p.S307fs*9
p.G629fs*7
p.K75fs*11
p.F97fs*42
p.Q442fs*17
p.L173fs*149
p.Y1128fs*1
p.N575fs*36
p.G1007fs*17
p.V447fs*7
p.N170fs*6
p.S1518fs*60
p.D111fs*3
p.K1138fs*1
p.T1883fs*4
p.S918fs*18
p.I824fs*30
p.F534fs*1
p.K766fs*15
p.T690fs*2
p.Q428fs*10
p.K201fs*7
p.V1371fs*77
p.V926fs*19
p.K1478fs*93
p.R528fs*8
p.R408fs*14
p.N1746fs*17
p.G724fs*2
p.A199fs*114
p.T199fs*10
p.A8fs*10
p.A159fs*3
p.D1314fs*49
p.N1369fs*10
p.D228fs*1
p.F82fs*78
p.M310fs*18
p.P994fs*30
p.R344fs*>145
p.P390fs*71
p.R1176fs*50
p.R1179fs*47
p.T789fs*7
p.Q397fs*197
p.K839fs*5
p.T691fs*22
p.R209fs*10
p.K917fs*15
p.F1377fs*23
p.Y628fs*6
p.T1248fs*16
p.Y591fs*27
p.T269fs*109
p.N1484fs*88
p.F1901fs*4
p.K21fs*1
p.L22fs*1
p.D1143fs*9
p.Q821fs*24
p.H588fs*63
p.G1187fs*39
p.F729fs*11
p.L615fs*24
p.E118fs*27
p.N595fs*5
p.F1683fs*3
p.H1492fs*77
p.Q296fs*8
p.G697fs*102
p.S666fs*21
p.L864fs*8
p.L205fs*12
p.K1785fs*35
p.T374fs*50
p.N325fs*6
p.P1108fs*6
p.Q1987fs*22
p.Y356fs*2
p.V218fs*32
p.E740fs*12
p.G986fs*21
p.A1341fs*3
p.A470fs*121
p.T377fs*8
p.K402fs*4
p.E1119fs*10
p.Q311fs*11
p.V195fs*108
p.N1743fs*10
p.P726fs*2
p.N96fs*26
p.Q475fs*13
p.S1424fs*1
p.A1262fs*16
p.N146fs*13
p.V73fs*76
p.G235fs*11
p.R81fs*4
p.T592fs*82
p.T264fs*14
p.A352fs*248
p.Y1679fs*7
p.Q623fs*11
p.S439fs*161
p.N1784fs*36
p.A658fs*49
p.K932fs*14
p.L805fs*3
p.I294fs*1
p.K1831fs*22
p.E463fs*188
p.S1686fs*8
p.A956fs*7
p.P885fs*40
p.I1349fs*2
p.T736fs*8
p.S480fs*13
p.L749fs*25
p.G742fs*1
p.G643fs*16
p.N263fs*8
p.Q909fs*37
p.A88fs*35
p.R502fs*19
p.T740fs*4
p.S448fs*13
p.K1720fs*25
p.T822fs*11
p.T148fs*2
p.L1213fs*3
p.F414fs*7
p.A1080fs*2
p.K778fs*16
p.E303fs*14
p.T443fs*4
p.S318fs*11
p.D238fs*4
p.V24fs*113
p.E567fs*40
p.P304fs*7
p.V1299fs*197
p.A149fs*3
p.S477fs*9
p.S308fs*292
p.H43fs*38
p.L722fs*5
p.T313fs*18
p.S402fs*198
p.S146fs*8
p.S1848fs*11
p.K1299fs*1
p.L823fs*1
p.D438fs*213
p.S1612fs*4
p.T779fs*2
p.C987fs*2
p.Q1534fs*37
p.Q397fs*203
p.P783fs*35
p.G168fs*9
p.L1646fs*6
p.S445fs*149
p.K812fs*5
p.V650fs*15
p.S221fs*18
p.H632fs*17
p.H1584fs*30
p.I139fs*36
p.Q172fs*149
p.K838fs*4
p.Q491fs*13
p.T514fs*15
p.P103fs*35
p.D1807fs*13
p.T880fs*7
p.E657fs*11
p.D211fs*2
p.V233fs*26
p.S215fs*32
p.S1559fs*12
p.E788fs*30
p.S1105fs*12
p.M906fs*16
p.T556fs*11
p.I530fs*10
p.L56fs*6
p.A1562fs*9
p.G1113fs*94
p.S158fs*45
p.G368fs*>121
p.L1780fs*40
p.A214fs*12
p.C527fs*49
p.N1018fs*15
p.S766fs*6
p.P1380fs*118
p.P617fs*32
p.Q573fs*13
p.F116fs*30
p.N512fs*15
p.G1869fs*7
p.G1154fs*72
p.T443fs*11
p.L503fs*6
p.L775fs*1
p.H448fs*29
p.E756fs*23
p.M1088fs*17
p.P385fs*22
p.Y370fs*37
p.S329fs*25
p.E1555fs*22
p.Q1539fs*39
p.S153fs*7
p.P2472fs*17
p.M906fs*10
p.F245fs*20
p.N1328fs*35
p.Y1560fs*1
p.L926fs*3
p.L330fs*15
p.C1298fs*65
p.R99fs*46
p.N970fs*28
p.H169fs*14
p.L809fs*7
p.S1688fs*4
p.M141fs*4
p.S318fs*282
p.L329fs*>160
p.L89fs*34
p.S149fs*21
p.S254fs*38
p.H588fs*62
p.A358fs*63
p.V343fs*35
p.D93fs*1
p.A79fs*29
p.Q1529fs*37
p.N542fs*10
p.H800fs*15
p.F1287fs*13
p.S315fs*32
p.Q1424fs*60
p.C357fs*65
p.H1912fs*38
p.V515fs*13
p.A382fs*4
p.E95fs*12

In [151]:
#NON_SENS_MUTATION


mol_df = mol_df.with_columns(
    pl.when(pl.col("PROTEIN_CHANGE").str.contains("\*"))
    .then(1)
    .otherwise(0)
    .alias("is_non_sens_mutation")
)

<>:5: SyntaxWarning: invalid escape sequence '\*'
<>:5: SyntaxWarning: invalid escape sequence '\*'
C:\Users\zakar\AppData\Local\Temp\ipykernel_16716\402174943.py:5: SyntaxWarning: invalid escape sequence '\*'
  pl.when(pl.col("PROTEIN_CHANGE").str.contains("\*"))

In [152]:
# IS MISSENSE

def ismissense(elem):
    if elem is not None and isinstance(elem, str):
        # Vérifie que le dernier caractère est une lettre majuscule (acide aminé)
        if elem.startswith("p.") and elem[-1].isalpha() and "*" not in elem and "fs" not in elem:
            return 1
    return 0

mol_df = mol_df.with_columns(
    pl.col("PROTEIN_CHANGE").map_elements(ismissense, return_dtype=pl.Int64).alias("IS_MISSENSE")
)

In [153]:
for elem in protein_change:
    if (elem is not None and "=" in elem):
        print(elem)

In [154]:
mol_df.filter(pl.col("EFFECT") == "PTD")



# j'ai déja traité : frameshift , stopgained , non_synonoumous_codon , splice_site_variant

shape: (89, 147)
┌─────────┬─────┬──────────┬──────────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ ID      ┆ CHR ┆ START    ┆ END      ┆ … ┆ IS_PT_UKNOWN ┆ is_frameshi ┆ is_non_sens ┆ IS_MISSENSE │
│ ---     ┆ --- ┆ ---      ┆ ---      ┆   ┆ ---          ┆ ft          ┆ _mutation   ┆ ---         │
│ str     ┆ f64 ┆ f64      ┆ f64      ┆   ┆ i32          ┆ ---         ┆ ---         ┆ i64         │
│         ┆     ┆          ┆          ┆   ┆              ┆ i32         ┆ i32         ┆             │
╞═════════╪═════╪══════════╪══════════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ P100014 ┆ 3.0 ┆ 7.9008e7 ┆ 7.9009e7 ┆ … ┆ 0            ┆ 0           ┆ 0           ┆ 0           │
│ P100015 ┆ 3.0 ┆ 7.9008e7 ┆ 7.9009e7 ┆ … ┆ 0            ┆ 0           ┆ 0           ┆ 0           │
│ P100026 ┆ 3.0 ┆ 7.9008e7 ┆ 7.9009e7 ┆ … ┆ 0            ┆ 0           ┆ 0           ┆ 0           │
│ P100209 ┆ 3.0 ┆ 7.9008e7 ┆ 7.9009e7 ┆ … ┆ 0            ┆ 0           ┆ 0           ┆ 0           │
│ P100210 ┆ 3.0 ┆ 7.9008e7 ┆ 7.9009e7 ┆ … ┆ 0            ┆ 0           ┆ 0           ┆ 0           │
│ …       ┆ …   ┆ …        ┆ …        ┆ … ┆ …            ┆ …           ┆ …           ┆ …           │
│ P131472 ┆ 3.0 ┆ 7.9008e7 ┆ 7.9009e7 ┆ … ┆ 0            ┆ 0           ┆ 0           ┆ 0           │
│ P131505 ┆ 3.0 ┆ 7.9008e7 ┆ 7.9009e7 ┆ … ┆ 0            ┆ 0           ┆ 0           ┆ 0           │
│ P131816 ┆ 3.0 ┆ 7.9008e7 ┆ 7.9009e7 ┆ … ┆ 0            ┆ 0           ┆ 0           ┆ 0           │
│ P132717 ┆ 3.0 ┆ 7.9008e7 ┆ 7.9009e7 ┆ … ┆ 0            ┆ 0           ┆ 0           ┆ 0           │
│ P132724 ┆ 3.0 ┆ 7.9008e7 ┆ 7.9009e7 ┆ … ┆ 0            ┆ 0           ┆ 0           ┆ 0           │
└─────────┴─────┴──────────┴──────────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

# EFFECT

In [155]:
temp_df = mol_df.to_pandas()

encoder  = ce.BinaryEncoder(cols=["EFFECT"])

temp_df = encoder.fit_transform(temp_df)

temp_df

,ID,CHR,START,END,REF,ALT,GENE,PROTEIN_CHANGE,EFFECT_0,EFFECT_1,...,GO:2000045,AA_TYPE_0,AA_TYPE_1,AA_TYPE_2,AA_TYPE_3,AA_TYPE_4,IS_PT_UKNOWN,is_frameshift,is_non_sens_mutation,IS_MISSENSE
0,P100000,11.0,1.191492e+08,1.191492e+08,G,A,CBL,p.C419Y,0,0,...,0,0,0,0,0,1,0,0,0,1
1,P100000,5.0,1.318223e+08,1.318223e+08,G,T,IRF1,p.Y164*,0,0,...,0,0,0,0,1,0,0,0,1,0
2,P100000,3.0,7.769406e+07,7.769406e+07,G,C,ROBO2,p.?,0,0,...,0,0,0,0,1,1,1,0,0,0
3,P100000,4.0,1.061649e+08,1.061649e+08,G,T,TET2,p.R1262L,0,0,...,0,0,0,1,0,0,0,0,0,1
4,P100000,2.0,2.546815e+07,2.546816e+07,ACGAAGAGGGGGTGTTC,A,DNMT3A,p.E505fs*141,0,1,...,0,0,0,1,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10914,P131472,3.0,7.900754e+07,7.900930e+07,None,None,KMT2A,MLL_PTD,1,1,...,0,0,1,1,1,0,0,0,0,0
10915,P131505,3.0,7.900754e+07,7.900930e+07,None,None,KMT2A,MLL_PTD,1,1,...,0,0,1,1,1,0,0,0,0,0
10916,P131816,3.0,7.900754e+07,7.900930e+07,None,None,KMT2A,MLL_PTD,1,1,...,0,0,1,1,1,0,0,0,0,0
10917,P132717,3.0,7.900754e+07,7.900930e+07,None,None,KMT2A,MLL_PTD,1,1,...,0,0,1,1,1,0,0,0,0,0
10918,P132724,3.0,7.900754e+07,7.900930e+07,None,None,KMT2A,MLL_PTD,1,1,...,0,0,1,1,1,0,0,0,0,0

# K-MER EXTRACT

In [156]:



mol_df = mol_df.with_columns(
    pl.when(pl.col("REF").str.len_chars() > k_mer_coef)
    .then(pl.col("REF").map_elements(lambda x: join_str(extract_kmers(x, k_mer_coef))))
    .otherwise(None)
    .alias(f"REF_{k_mer_coef}_mer")
)

C:\Users\zakar\AppData\Local\Temp\ipykernel_16716\2759431246.py:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
  mol_df = mol_df.with_columns(

In [157]:
mol_df

shape: (10_919, 148)
┌─────────┬──────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ ID      ┆ CHR  ┆ START      ┆ END        ┆ … ┆ is_framesh ┆ is_non_sen ┆ IS_MISSENS ┆ REF_4_mer  │
│ ---     ┆ ---  ┆ ---        ┆ ---        ┆   ┆ ift        ┆ s_mutation ┆ E          ┆ ---        │
│ str     ┆ f64  ┆ f64        ┆ f64        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ str        │
│         ┆      ┆            ┆            ┆   ┆ i32        ┆ i32        ┆ i64        ┆            │
╞═════════╪══════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ P100000 ┆ 11.0 ┆ 1.19149248 ┆ 1.19149248 ┆ … ┆ 0          ┆ 0          ┆ 1          ┆ null       │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 5.0  ┆ 1.31822301 ┆ 1.31822301 ┆ … ┆ 0          ┆ 1          ┆ 0          ┆ null       │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 3.0  ┆ 7.769406e7 ┆ 7.769406e7 ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ null       │
│ P100000 ┆ 4.0  ┆ 1.06164917 ┆ 1.06164917 ┆ … ┆ 0          ┆ 0          ┆ 1          ┆ null       │
│         ┆      ┆ e8         ┆ e8         ┆   ┆            ┆            ┆            ┆            │
│ P100000 ┆ 2.0  ┆ 2.5468147e ┆ 2.5468163e ┆ … ┆ 1          ┆ 1          ┆ 0          ┆ ACGA CGAA  │
│         ┆      ┆ 7          ┆ 7          ┆   ┆            ┆            ┆            ┆ GAAG AAGA  │
│         ┆      ┆            ┆            ┆   ┆            ┆            ┆            ┆ AGAG GAGG  │
│         ┆      ┆            ┆            ┆   ┆            ┆            ┆            ┆ …          │
│ …       ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ P131472 ┆ 3.0  ┆ 7.9008e7   ┆ 7.9009e7   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ null       │
│ P131505 ┆ 3.0  ┆ 7.9008e7   ┆ 7.9009e7   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ null       │
│ P131816 ┆ 3.0  ┆ 7.9008e7   ┆ 7.9009e7   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ null       │
│ P132717 ┆ 3.0  ┆ 7.9008e7   ┆ 7.9009e7   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ null       │
│ P132724 ┆ 3.0  ┆ 7.9008e7   ┆ 7.9009e7   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ null       │
└─────────┴──────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [158]:
ref_4_mer = mol_df.filter(pl.col("REF_4_mer").is_not_null())["REF_4_mer"].to_list()

ref_4_mer

['ACGA CGAA GAAG AAGA AGAG GAGG AGGG GGGG GGGG GGGT GGTG GTGT TGTT GTTC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'ACGC CGCG',
 'TCGC CGCG GCGG CGGC GGCC GCCG CCGT CGTC GTCC TCCA CCAG CAGC AGCA GCAC CACG ACGG',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CAGA AGAT GATT ATTA TTAA TAAC AACC ACCA CCAG CAGG AGGA GGAC GACA',
 'TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG GGGG GGGG GGGC GGCG GCGG CGGC GGCC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG GGGG GGGG GGGC GGCG',
 'AAAA AAAG AAGT',
 'CTGT TGTT',
 'ACAG CAGT',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CGCA GCAG CAGT AGTT',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'ACAG CAGC AGCA GCAG CAGA AGAT',
 'TGCA GCAC CACC ACCT CCTA CTAG TAGT AGTG GTGC TGCT GCTA',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'GCAG CAGC AGCG GCGC CGCC GCCG CCGG CGGC GGCG GCGT CGTC GTCC TCCG CCGG CGGG GGGG GGGC GGCG GCGC CGCC GCCC CCCA CCAG CAGC AGCG GCGG CGGC GGCA GCAA',
 'CTTC TTCT',
 'GGAT GATG ATGA',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'GGCG GCGG CGGC GGCG GCGT CGTG GTGA TGAA',
 'ATGA TGAT',
 'TGCA GCAG CAGG AGGT GGTC GTCC',
 'GGGG GGGA GGAC GACC ACCA CCAG CAGC AGCC GCCA CCAT CATG ATGC TGCC GCCA',
 'CTTC TTCT',
 'CGAC GACT ACTG CTGA TGAG GAGA',
 'TACA ACAA CAAA AAAT AATA ATAA',
 'CACC ACCA',
 'CAGA AGAT GATT ATTA TTAA TAAC AACC ACCA CCAG CAGG AGGA GGAC GACA',
 'CATG ATGC TGCC GCCG CCGA CGAT GATG ATGC TGCC GCCG CCGA CGAT',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'GTCC TCCA CCAT CATT ATTC',
 'AACT ACTC CTCT',
 'CCCT CCTG CTGA TGAC GACT',
 'CAGA AGAT GATT ATTA TTAA TAAC AACC ACCA CCAG CAGG AGGA GGAC GACA',
 'ACTG CTGC TGCC GCCA CCAT CATC ATCG TCGG CGGA GGAG GAGG AGGG',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CAGA AGAT GATT ATTA TTAA TAAC AACC ACCA CCAG CAGG AGGA GGAC GACA',
 'GGCT GCTA CTAA TAAA AAAC AACA ACAG CAGT',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CTCC TCCA CCAC CACA ACAG CAGT',
 'GAAT AATA',
 'CGCG GCGC CGCA GCAG CAGC AGCC GCCG CCGT CGTA GTAG TAGC AGCC GCCG CCGG CGGG GGGC GGCG GCGG CGGG GGGG',
 'AGCT GCTG CTGG TGGG GGGT GGTT GTTT TTTG TTGG',
 'CCTG CTGC TGCA GCAG CAGG AGGA GGAC GACC ACCT CCTC CTCG TCGT CGTA',
 'TGGC GGCC GCCC',
 'ACTC CTCC',
 'GTGG TGGT GGTT GTTC TTCG TCGC CGCA GCAG CAGA AGAA GAAG AAGC AGCA GCAG CAGC AGCA GCAG CAGT AGTG GTGA TGAA',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TAAA AAAG AAGG',
 'GGTG GTGA',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CTGA TGAT',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'ACTG CTGA TGAA GAAA AAAA AAAA AAAC AACT ACTT CTTA TTAT TATG ATGT TGTC GTCC',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'CACC ACCA CCAT CATG ATGC TGCC GCCC CCCA',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CTCT TCTA',
 'TCAG CAGA',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'AGCA GCAG CAGC AGCG GCGC CGCT GCTC CTCA TCAT CATG ATGG TGGT GGTG GTGG TGGG GGGG',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'GAGG AGGA GGAT',
 'GCTC CTCT',
 'TACT ACTG CTGT TGTG GTGT TGTT GTTT TTTG TTGG TGGT GGTG GTGC',
 'ATGT TGTG GTGC TGCA GCAG CAGC AGCA GCAA CAAA AAAA AAAG',
 'CAAC AACG ACGC CGCC GCCT CCTC CTCG TCGC CGCT GCTC CTCA TCAT CATC ATCT TCTT CTTG TTGC TGCC GCCT CCTG CTGG TGGG GGGC GGCT GCTC CTCA TCAG CAGC AGCG GCGC CGCG GCGG CGGT GGTG GTGG TGGA',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'GAGT AGTG GTGC TGCT GCTG CTGC TGCT GCTG CTGA TGAC GACA ACAG CAGC AGCA GCAC CACA ACAT CATG ATGG TGGC GGCG GCGA CGAC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CAGC AGCT',
 'ATAC TACT',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'TATT ATTC TTCT TCTC CTCC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'AAAG AAGG AGGA GGAA GAAC AACA ACAA CAAT AATG ATGG TGGG',
 'CAGC AGCG GCGG CGGC GGCA GCAA CAAC AACG ACGC CGCC GCCT CCTC CTCG TCGC CGCT GCTC CTCA TCAT CATC ATCT TCTT CTTG TTGC TGCC GCCT CCTG CTGG TGGG GGGC GGCT GCTC CTCA TCAG CAGC AGCG GCGC CGCG GCGG CGGT GGTG GTGG TGGA GGAA GAAG AAGG AGGC GGCG GCGG CGGC GGCG GCGT CGTG GTGA',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'CTGA TGAC GACA',
 'CACT ACTA',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'AGCA GCAG CAGC AGCG GCGC CGCT GCTC CTCA TCAT CATG ATGG TGGT GGTG GTGG TGGG GGGG',
 'AGAG GAGC AGCA GCAG CAGC AGCT',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'GATG ATGA TGAT GATG ATGC TGCT GCTG CTGA',
 'CAGT AGTA GTAT TATC ATCA',
 'CTTA TTAA TAAT AATG ATGG TGGC GGCT GCTG CTGC TGCC GCCT CCTG CTGG TGGG GGGC GGCA',
 'TACT ACTC',
 'TGGC GGCT GCTG CTGC TGCC GCCT CCTG',
 'CAGT AGTT GTTG TTGT TGTT GTTG TTGT TGTT GTTT TTTC TTCC TCCG CCGC CGCA GCAC CACA ACAT',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'GCTC CTCT',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CAGA AGAT GATT ATTA TTAA TAAC AACC ACCA CCAG CAGG AGGA GGAC GACA',
 'CAGA AGAT',
 'TGCC GCCA CCAT CATC ATCG TCGG CGGA GGAG GAGG',
 'TTCG TCGT CGTG GTGT TGTT GTTA TTAT TATA',
 'CAGA AGAT GATT ATTA TTAA TAAC AACC ACCA CCAG CAGG AGGA GGAC GACA',
 'TTCT TCTG',
 'TGTG GTGC TGCT GCTC CTCA TCAT CATG ATGC TGCC GCCC CCCA CCAC CACA',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'TTTG TTGG TGGT GGTA GTAA TAAC AACG ACGG CGGT GGTC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TTCA TCAG CAGC AGCC GCCA CCAT CATC ATCA TCAG CAGA AGAT GATT ATTA TTAT TATG',
 'GGCT GCTT CTTC TTCA TCAG CAGA AGAG GAGA AGAC GACT ACTG CTGA TGAG GAGC AGCC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'GAGT AGTT GTTT TTTC TTCC TCCA',
 'AAGA AGAG',
 'CTGA TGAG GAGC AGCA GCAG CAGT AGTC GTCC TCCC CCCC CCCA CCAT',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'GGCT GCTG CTGA',
 'ATGC TGCA GCAG CAGG AGGA GGAA GAAC',
 'CAGA AGAT GATT ATTA TTAA TAAC AACC ACCA CCAG CAGG AGGA GGAC GACA',
 'TTCT TCTT CTTC TTCA TCAT CATG ATGG',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'GCTC CTCT',
 'GGCT GCTG CTGA',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'CCTT CTTG',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CTCT TCTG CTGG TGGC GGCA GCAT CATG ATGT TGTC GTCA TCAT CATA ATAA TAAT AATT',
 'GATT ATTG TTGA',
 'GCAG CAGC AGCG GCGC CGCC GCCT',
 'GGAG GAGA AGAA',
 'GGTG GTGA TGAG GAGT AGTG GTGA TGAG GAGG AGGC GGCC GCCT',
 'TCCC CCCC CCCT CCTT CTTC',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'CAGC AGCG GCGG CGGC GGCA GCAA CAAC AACG ACGC CGCC GCCT CCTC CTCG TCGC CGCT GCTC CTCA TCAT CATC ATCT TCTT CTTG TTGC TGCC GCCT CCTG CTGG TGGG GGGC GGCT GCTC CTCA TCAG CAGC AGCG GCGC CGCG GCGG CGGT GGTG GTGG TGGA GGAA GAAG AAGG AGGC GGCG GCGG CGGC GGCG GCGT CGTG GTGA',
 'GCTC CTCT',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'CAGA AGAT GATT ATTA TTAA TAAC AACC ACCA CCAG CAGG AGGA GGAC GACA',
 'TCCA CCAT CATC ATCA TCAA',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'TGCC GCCA CCAT CATC ATCG TCGG CGGA GGAG GAGG',
 'GACA ACAT CATA',
 'ATTC TTCT TCTG CTGT TGTT GTTC TTCA TCAG CAGG',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'GATG ATGG TGGT GGTC GTCA TCAG CAGA AGAG GAGT',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CTGA TGAG GAGC AGCC GCCA CCAT',
 'GGGG GGGC GGCT GCTG CTGG TGGG GGGT GGTG GTGG TGGT GGTG GTGT',
 'GGGG GGGC GGCG GCGG CGGC GGCC GCCA CCAG CAGG AGGT GGTG GTGC TGCG GCGC',
 'AACT ACTC CTCT',
 'TCCA CCAG CAGC AGCG GCGC CGCT GCTC CTCG TCGC CGCC GCCC CCCA CCAT CATC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CGGC GGCG GCGC CGCT GCTG CTGC TGCT GCTG CTGG TGGG GGGC GGCG GCGC CGCG GCGT CGTG GTGC TGCG GCGG CGGG GGGG',
 'AATC ATCT',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'GCTC CTCA TCAT CATG ATGC TGCC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'TGCT GCTG CTGT TGTT GTTG TTGC TGCT GCTG CTGC TGCT GCTG CTGT TGTT GTTG TTGA TGAA',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CGTG GTGC TGCT GCTC CTCT TCTG CTGC TGCA GCAG',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'AGGG GGGG GGGG',
 'TGCT GCTG CTGT TGTT GTTG TTGC TGCT GCTG CTGC TGCT GCTG CTGT TGTT GTTG TTGA TGAA',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'AATA ATAG',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TTTC TTCT TCTG CTGC TGCT GCTG CTGC',
 'GTAA TAAA AAAG AAGC AGCT GCTA',
 'GGCA GCAG CAGC',
 'TTAA TAAC AACA ACAA CAAT AATA',
 'AGCA GCAG CAGA AGAG GAGG AGGC GGCT GCTT CTTA TTAA TAAG AAGG AGGA GGAG GAGG AGGA GGAG GAGG AGGA GGAA GAAG AAGA AGAA GAAG AAGA AGAC GACA ACAA CAAG AAGA AGAA GAAA AAAC AACG ACGC CGCA GCAA CAAA AAAG AAGA AGAG GAGG AGGA GGAG GAGG AGGA GGAG GAGG AGGA GGAG',
 'AACT ACTC CTCT',
 'TCGG CGGA GGAG GAGG AGGG GGGG GGGG GGGG GGGG GGGG GGGT GGTG GTGG TGGC GGCC',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'GTTA TTAA',
 'AGGA GGAC GACC ACCT CCTC CTCG TCGT CGTA GTAG TAGA AGAT',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'CAGA AGAT GATT ATTA TTAA TAAC AACC ACCA CCAG CAGG AGGA GGAC GACA',
 'CTGT TGTG',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'CATG ATGC TGCA',
 'CGGA GGAG GAGG',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'TGCG GCGT CGTC',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CAGT AGTA',
 'GCCG CCGG CGGG GGGC GGCC',
 'CTGA TGAG GAGT AGTC GTCC TCCT CCTC CTCA TCAC CACG ACGG',
 'ATGT TGTC GTCT TCTC CTCC TCCG CCGA CGAT GATT',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'ATGA TGAC',
 'GGGG GGGC GGCT GCTG CTGG TGGG GGGT GGTG GTGG TGGT GGTG GTGT',
 'CCAG CAGC AGCA GCAG CAGC AGCA GCAG CAGC AGCA GCAG CAGA AGAG GAGA AGAC GACC ACCC CCCC CCCA CCAG',
 'TCTG CTGG',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'CTTC TTCT TCTG',
 'CGGA GGAG GAGG',
 'TTCT TCTA CTAA TAAG AAGG AGGA GGAC GACC ACCA CCAT CATA ATAT TATA ATAC TACC ACCT CCTG CTGC',
 'ACTC CTCC',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'AAGT AGTG GTGA TGAT GATT ATTC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CAGA AGAT GATT ATTA TTAA TAAC AACC ACCA CCAG CAGG AGGA GGAC GACA',
 'TAGC AGCC',
 'CGAC GACG',
 'AGCA GCAG CAGA AGAG GAGG AGGC GGCT GCTT CTTA TTAA TAAG AAGG AGGA GGAG GAGG AGGA GGAG GAGG AGGA GGAA GAAG AAGA AGAA GAAG AAGA AGAC GACA ACAA CAAG AAGA AGAA GAAA AAAC AACG ACGC CGCA GCAA CAAA AAAG AAGA AGAG GAGG AGGA GGAG GAGG AGGA GGAG GAGG AGGA GGAG',
 'CCCA CCAA CAAG AAGG AGGC GGCA GCAA CAAG AAGC AGCT GCTT CTTA TTAC TACA',
 'TGGG GGGC',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'CTGG TGGG GGGC GGCT GCTT CTTT',
 'CTTC TTCT',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'AGCA GCAG CAGA AGAG GAGG AGGC GGCT GCTT CTTA TTAA TAAG AAGG AGGA GGAG GAGG AGGA GGAG GAGG AGGA GGAA GAAG AAGA AGAA GAAG AAGA AGAC GACA ACAA CAAG AAGA AGAA GAAA AAAC AACG ACGC CGCA GCAA CAAA AAAG AAGA AGAG GAGG AGGA GGAG GAGG AGGA GGAG GAGG AGGA GGAG',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'GAAA AAAA AAAG AAGT AGTG GTGC TGCT GCTA CTAA TAAT AATT ATTA TTAC TACC ACCA CCAT CATG ATGA TGAC GACA ACAA CAAG AAGA AGAA GAAC AACA ACAT CATT ATTG TTGT TGTA GTAT TATT ATTA TTAC TACT ACTT CTTA TTAA',
 'TGAG GAGA',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'ATAA TAAG',
 'AGCA GCAG CAGA AGAG GAGG AGGC GGCT GCTT CTTA TTAA TAAG AAGG AGGA GGAG GAGG AGGA GGAG GAGG AGGA GGAA GAAG AAGA AGAA GAAG AAGA AGAC GACA ACAA CAAG AAGA AGAA GAAA AAAC AACG ACGC CGCA GCAA CAAA AAAG AAGA AGAG GAGG AGGA GGAG GAGG AGGA GGAG GAGG AGGA GGAG',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'TTCT TCTC CTCA',
 'CGGG GGGG GGGG GGGT',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'AAAA AAAT AATA ATAG TAGA AGAG GAGG AGGG GGGT',
 'CCAA CAAG AAGC AGCA GCAG',
 'TAAA AAAG',
 'CAGA AGAT',
 'TAGC AGCC',
 'TCAC CACC ACCA CCAC CACT ACTG CTGC TGCC GCCA CCAT CATA ATAG TAGA AGAG GAGA AGAG GAGG AGGC GGCG GCGG CGGC',
 'TAGT AGTC',
 'ACAG CAGT',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',
 'ATAT TATA ATAT TATG ATGA TGAT GATG ATGA TGAG',
 'CGGC GGCG GCGG CGGC GGCT GCTG CTGT TGTG GTGG TGGT GGTG GTGT TGTG GTGA TGAG GAGT AGTC GTCC TCCG CCGG CGGG GGGG',

In [159]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(4,4))


X_ref_4_mer = cv.fit_transform(ref_4_mer)

X_ref_4_mer

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 6271 stored elements and shape (558, 1926)>

In [160]:
feature_names_4mer = cv.get_feature_names_out()

# Convertir la matrice sparse en DataFrame
ref_4mer_df = pd.DataFrame(
    X_ref_4_mer.toarray(),
    columns=feature_names_4mer
)

ref_4mer_df

,aaaa aaaa aaac aact,aaaa aaaa aaat aatt,aaaa aaac aaca acag,aaaa aaac aact actg,aaaa aaac aact actt,aaaa aaag aagc agct,aaaa aaag aagt agtg,aaaa aaat aata atag,aaaa aaat aatt attt,aaac aaca acag cagc,...,tttg ttga tgaa gaag,tttg ttga tgac gacc,tttg ttga tgat gatg,tttg ttgc tgct gctg,tttg ttgc tgct gctt,tttg ttgg tggt ggta,tttg ttgg tggt ggtg,tttt tttc ttca tcat,tttt tttg ttgc tgct,tttt tttt tttc ttca
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
553,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
554,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
555,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
556,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
557,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0